#include "def_schema.h"

namespace opennova::def {
namespace {

// Property syntax of the witnessed family parsers. The writer and inspector
// share these rows; parser-equivalence tests pin their native member mappings.
const std::vector<DefProperty> kItemProperties = {
    {"powerupdef", {"powerup_def"}},
    {"score", {"score"}},
    {"graphicenemy", {"graphic_enemy"}},
    {"textid", {"text_id"}},
	{"kz", {"kz"}},
	{"debris_scale", {"debris_scale"}},
	{"sid", {"sid"}, DefEncoding::Plain, 1.0, ""},
	{"graphic", {"graphic"}, DefEncoding::Plain, 1.0, ""},
	{"anim_def", {"anim_def"}, DefEncoding::Plain, 1.0, ""},
	{"husk", {"husk"}, DefEncoding::Plain, 1.0, ""},
	{"default_aip", {"default_aip"}, DefEncoding::Plain, 1.0, ""},
	{"ai_function", {"ai_function"}, DefEncoding::Plain, 1.0, ""},
	{"move_function", {"move_function"}, DefEncoding::Plain, 1.0, ""},
	{"render_function", {"render_function"}, DefEncoding::Plain, 1.0, ""},
	{"disk_function", {"disk_function"}, DefEncoding::Plain, 1.0, ""},
	{"input_function", {"input_function"}, DefEncoding::Plain, 1.0, ""},
	{"ammo_closeattack", {"ammo_closeattack"}, DefEncoding::Plain, 1.0, ""},
	{"ammo_marker3", {"ammo_marker3"}, DefEncoding::Plain, 1.0, ""},
	{"ammo_easyrocket", {"ammo_easyrocket"}, DefEncoding::Plain, 1.0, ""},
	{"ammo_advancedrocket", {"ammo_advancedrocket"}, DefEncoding::Plain, 1.0, ""},
	{"launchups_closeattack", {"launchups_closeattack"}, DefEncoding::Plain, 1.0, ""},
	{"launchups_rocket", {"launchups_rocket"}, DefEncoding::Plain, 1.0, ""},
	{"launchups_marker3", {"launchups_marker3"}, DefEncoding::Plain, 1.0, ""},
	{"weaplbup2", {"weapon_userpoints[6]"}, DefEncoding::Plain, 1.0, ""},
	{"weaplmup2", {"weapon_userpoints[7]"}, DefEncoding::Plain, 1.0, ""},
	{"weaplcup2", {"weapon_userpoints[8]"}, DefEncoding::Plain, 1.0, ""},
	{"weaprbup2", {"weapon_userpoints[9]"}, DefEncoding::Plain, 1.0, ""},
	{"weaprmup2", {"weapon_userpoints[10]"}, DefEncoding::Plain, 1.0, ""},
	{"weaprcup2", {"weapon_userpoints[11]"}, DefEncoding::Plain, 1.0, ""},
	{"weaplbup", {"weapon_userpoints[0]"}, DefEncoding::Plain, 1.0, ""},
	{"weaplmup", {"weapon_userpoints[1]"}, DefEncoding::Plain, 1.0, ""},
	{"weaplcup", {"weapon_userpoints[2]"}, DefEncoding::Plain, 1.0, ""},
	{"weaprbup", {"weapon_userpoints[3]"}, DefEncoding::Plain, 1.0, ""},
	{"weaprmup", {"weapon_userpoints[4]"}, DefEncoding::Plain, 1.0, ""},
	{"weaprcup", {"weapon_userpoints[5]"}, DefEncoding::Plain, 1.0, ""},
	{"primary_weapon", {"primary_weapon"}, DefEncoding::Plain, 1.0, ""},
	{"clipsize", {"clipsize"}, DefEncoding::Plain, 1.0, ""},
	{"climb_speed", {"climb_speed"}, DefEncoding::ScaledInteger, 293.0, ""},
	{"turnroll", {"turn_roll"}, DefEncoding::Plain, 1.0, ""},
	{"speedpitch", {"speed_pitch"}, DefEncoding::Plain, 1.0, ""},
	{"turn_rate2", {"turn_rate2"}, DefEncoding::ScaledInteger, 192426.0, ""},
	{"turn_rate", {"turn_rate"}, DefEncoding::ScaledInteger, 192426.0, ""},
	{"torque", {"torque"}, DefEncoding::Plain, 1.0, ""},
	{"lean_velocity", {"lean_velocity"}, DefEncoding::Plain, 1.0, ""},
	{"pitch_velocity", {"pitch_velocity"}, DefEncoding::Plain, 1.0, ""},
	{"mass", {"mass"}, DefEncoding::Plain, 1.0, ""},
	{"weathervane", {"weathervane"}, DefEncoding::Plain, 1.0, ""},
	{"minai", {"min_ai"}, DefEncoding::Plain, 1.0, ""},
	{"lean", {"lean"}, DefEncoding::Plain, 1.0, ""},
	{"pitch", {"pitch"}, DefEncoding::Plain, 1.0, ""},
	{"bob", {"bob"}, DefEncoding::Plain, 1.0, ""},
	{"flip", {"flip"}, DefEncoding::Plain, 1.0, ""},
	{"hand_brake", {"hand_brake"}, DefEncoding::Plain, 1.0, ""},
	{"tire_slip", {"tire_slip"}, DefEncoding::Plain, 1.0, ""},
	{"spring_comp", {"spring_comp"}, DefEncoding::Plain, 1.0, ""},
	{"spring", {"spring"}, DefEncoding::Plain, 1.0, ""},
	{"shock", {"shock"}, DefEncoding::Plain, 1.0, ""},
	{"top_heavy", {"top_heavy"}, DefEncoding::Plain, 1.0, ""},
	{"max_slope", {"max_slope"}, DefEncoding::ScaledInteger, 11930464.0, ""},
	{"slip_slope", {"slip_slope"}, DefEncoding::ScaledInteger, 11930464.0, ""},
	{"player_speed", {"player_speed"}, DefEncoding::ScaledInteger, 293.0, ""},
	{"water_speed", {"water_speed"}, DefEncoding::ScaledInteger, 293.0, ""},
	{"slip_speed", {"slip_speed"}, DefEncoding::ScaledInteger, 4.0, ""},
	{"physics", {"physics"}, DefEncoding::Plain, 1.0, ""},
	{"criticalhp", {"critical_hp"}, DefEncoding::Plain, 1.0, ""},
	{"criticaldrain", {"critical_drain"}, DefEncoding::Plain, 1.0, ""},
	{"noncriticalregen", {"non_critical_regen"}, DefEncoding::Plain, 1.0, ""},
	{"hud_image", {"hud_image"}, DefEncoding::Plain, 1.0, ""},
	{"unit_type", {"unit_type"}, DefEncoding::Plain, 1.0, ""},
	{"huskfinal", {"huskfinal"}, DefEncoding::Plain, 1.0, ""},
	{"husk_sub_parts", {"husk_sub_parts"}, DefEncoding::Plain, 1.0, ""},
	{"id", {"id"}, DefEncoding::Plain, 1.0, ""},
	{"mana", {"mana"}, DefEncoding::Plain, 1.0, ""},
	{"music", {"music_location"}, DefEncoding::Plain, 1.0, ""},
	{"hp", {"hp"}, DefEncoding::Plain, 1.0, ""},
	{"radarsig", {"radar_sig"}, DefEncoding::Plain, 1.0, ""},
	{"heatsig", {"heat_sig"}, DefEncoding::Plain, 1.0, ""},
	{"reverb", {"reverb"}, DefEncoding::Plain, 1.0, ""},
	{"sounddeath", {"sounddeath"}, DefEncoding::Plain, 1.0, ""},
	{"sound_profile", {"sound_profile"}, DefEncoding::Plain, 1.0, ""},
	{"sound_profilefemale", {"sound_profile_female"}, DefEncoding::Plain, 1.0, ""},
	{"acceleration", {"acceleration"}, DefEncoding::ScaledInteger, 4.0, ""},
	{"deceleration", {"deceleration"}, DefEncoding::ScaledInteger, 4.0, ""},
	{"type", {"type"}, DefEncoding::ItemType, 1.0, ""},
	{"attrib2", {"attrib2"}, DefEncoding::ItemAttrib2, 1.0, ""},
	{"parent", {"attrib_parent"}, DefEncoding::ItemParent, 1.0, ""},
	{"armor", {"armor_kz", "armor_impact"}, DefEncoding::Plain, 1.0, ""},
	{"damage_reduc_pp", {"damage_reduc_pp", "damage_reduc_max"}, DefEncoding::Plain, 1.0, ""},
	{"virtualdisplay", {"virtual_display", "virtual_display_userpoint"}, DefEncoding::Plain, 1.0, ""},
	{"shadow", {"shadow_texture", "shadow_width", "shadow_length", "shadow_offset_x", "shadow_offset_y"}, DefEncoding::Plain, 1.0, ""},
	{"light_transfer", {"light_transfer"}, DefEncoding::ScaledReal, 0.01, ""},
	{"scale", {"scale_q16"}, DefEncoding::ScaledReal, 65536.0, ""},
	{"phrase_set", {"phrase_set"}, DefEncoding::Plain, 1.0, "phrase_set_valid"},
	{"destroy_timing", {"destroy_timing_ticks[0]", "destroy_timing_ticks[1]", "destroy_timing_ticks[2]"}, DefEncoding::ScaledReal, 62.0, ""},
	{"dawnshot", {"dawnshot", "shot_delay_ticks[0][0]", "shot_delay_ticks[0][1]"}, DefEncoding::ScaledReal, 62.0, ""},
	{"dayshot", {"dayshot", "shot_delay_ticks[1][0]", "shot_delay_ticks[1][1]"}, DefEncoding::ScaledReal, 62.0, ""},
	{"duskshot", {"duskshot", "shot_delay_ticks[2][0]", "shot_delay_ticks[2][1]"}, DefEncoding::ScaledReal, 62.0, ""},
	{"nightshot", {"nightshot", "shot_delay_ticks[3][0]", "shot_delay_ticks[3][1]"}, DefEncoding::ScaledReal, 62.0, ""},
	{"soundloop_1", {"soundloops[0]"}, DefEncoding::Plain, 1.0, ""},
	{"soundloop_2", {"soundloops[1]"}, DefEncoding::Plain, 1.0, ""},
	{"soundloop_3", {"soundloops[2]"}, DefEncoding::Plain, 1.0, ""},
	{"soundloop_4", {"soundloops[3]"}, DefEncoding::Plain, 1.0, ""},
	{"soundloop_5", {"soundloops[4]"}, DefEncoding::Plain, 1.0, ""},
	{"soundloop_6", {"soundloops[5]"}, DefEncoding::Plain, 1.0, ""},
	{"soundloop_7", {"soundloops[6]"}, DefEncoding::Plain, 1.0, ""},
	{"particlefx", {"particlefx.effect", "particlefx.userpoint"}, DefEncoding::ParticleSlot, 1.0, ""},
	{"particlefxs", {"particlefxs.effect", "particlefxs.userpoint", "particlefxs.secondary_effect"}, DefEncoding::ParticleSlot, 1.0, ""},
	{"particlefxw1", {"particlefxw1.effect", "particlefxw1.userpoint", "particlefxw1.secondary_effect"}, DefEncoding::ParticleSlot, 1.0, ""},
	{"particlefxw2", {"particlefxw2.effect", "particlefxw2.userpoint", "particlefxw2.secondary_effect"}, DefEncoding::ParticleSlot, 1.0, ""},
	{"particlefxw3", {"particlefxw3.effect", "particlefxw3.userpoint"}, DefEncoding::ParticleSlot, 1.0, ""},
	{"particlefxw4", {"particlefxw4.effect", "particlefxw4.userpoint"}, DefEncoding::ParticleSlot, 1.0, ""},
	{"particledeath", {"particledeath"}, DefEncoding::Plain, 1.0, ""},
	{"particleh2odeath", {"particleh2odeath"}, DefEncoding::Plain, 1.0, ""},
	{"particlefire", {"particlefire"}, DefEncoding::Plain, 1.0, ""},
	{"particleother", {"particleother"}, DefEncoding::Plain, 1.0, ""},
	{"particlefinale", {"particlefinale"}, DefEncoding::Plain, 1.0, ""},
	{"particlespawn", {"particlespawn"}, DefEncoding::Plain, 1.0, ""},
	{"attrib:", {"attrib"}, DefEncoding::ItemAttrib, 1.0, ""},
	{"deathtime", {"deathtime_ticks"}, DefEncoding::ItemDeathTime, 1.0, ""},
	{"door_type", {"door_type"}, DefEncoding::DoorType, 1.0, ""},
	{"open_rate", {"door_open_rate_q16"}, DefEncoding::DoorOpenRate, 1.0, ""},
	{"max_angle", {"door_max_angle_bam"}, DefEncoding::DoorMaxAngle, 1.0, ""},
	{"husk_swap_at_sec", {"husk_swap_at_sec"}, DefEncoding::HuskSeconds, 1.0, ""},
	{"husk_swap_at", {"husk_swap_at"}, DefEncoding::HuskSwap, 1.0, ""},
	{"door_open_sound_id", {"door_open_sound"}, DefEncoding::Plain, 1.0, ""},
	{"door_close_sound_id", {"door_close_sound"}, DefEncoding::Plain, 1.0, ""},
	{"husk_sub_part_types", {"husk_sub_part_types[0]", "husk_sub_part_types[1]", "husk_sub_part_types[2]", "husk_sub_part_types[3]", "husk_sub_part_types[4]", "husk_sub_part_types[5]", "husk_sub_part_types[6]", "husk_sub_part_types[7]", "husk_sub_part_types[8]", "husk_sub_part_types[9]", "husk_sub_part_types[10]", "husk_sub_part_types[11]", "husk_sub_part_types[12]", "husk_sub_part_types[13]", "husk_sub_part_types[14]", "husk_sub_part_types[15]"}, DefEncoding::DeathPieces, 1.0, ""},
	{"pcvehicle_spawnlist", {"vehicle_spawn_mask"}, DefEncoding::SpawnMask, 1.0, ""},
};

const std::vector<DefProperty> kWeaponProperties = {
	{"attachtextid", {"attach_text_id"}},
	{"rank", {"rank"}, DefEncoding::Plain, 1.0, ""},
	{"clipsize", {"clipsize"}, DefEncoding::Plain, 1.0, ""},
	{"startrounds", {"startrounds"}, DefEncoding::Plain, 1.0, ""},
	{"targetyawrange", {"targetyawrange"}, DefEncoding::Plain, 1.0, ""},
	{"targetpitchmax", {"targetpitchmax"}, DefEncoding::Plain, 1.0, ""},
	{"targetpitchmin", {"targetpitchmin"}, DefEncoding::Plain, 1.0, ""},
	{"statid", {"statid"}, DefEncoding::Plain, 1.0, ""},
	{"maxclips", {"maxclips"}, DefEncoding::Plain, 1.0, ""},
	{"ammobucket", {"ammobucket"}, DefEncoding::Plain, 1.0, ""},
	{"loadout_selectable", {"loadout_selectable"}, DefEncoding::Plain, 1.0, ""},
	{"loadout_subclasses", {"loadout_subclasses"}, DefEncoding::Plain, 1.0, ""},
	{"round_type", {"round_type"}, DefEncoding::Plain, 1.0, ""},
	{"loadout_menu_textid", {"loadout_menu_textid"}, DefEncoding::Plain, 1.0, ""},
	{"loadout_menu_ttdesc", {"loadout_menu_ttdesc"}, DefEncoding::Plain, 1.0, ""},
	{"loadout_menu_icon", {"loadout_menu_icon"}, DefEncoding::Plain, 1.0, ""},
	{"animadm", {"animadm"}, DefEncoding::Plain, 1.0, ""},
	{"launchuserpoint", {"launch_user_point"}, DefEncoding::Plain, 1.0, ""},
	{"commandersx", {"commanders_x"}, DefEncoding::Plain, 1.0, ""},
	{"hud_loadout_select", {"hud_loadout_select"}, DefEncoding::Plain, 1.0, ""},
	{"splash", {"splash"}, DefEncoding::Plain, 1.0, ""},
	{"hudicon", {"hudicon"}, DefEncoding::Plain, 1.0, ""},
	{"gfx1a", {"gfx1a"}, DefEncoding::Plain, 1.0, ""},
	{"gfx1b", {"gfx1b"}, DefEncoding::Plain, 1.0, ""},
	{"gfx1", {"gfx1"}, DefEncoding::Plain, 1.0, ""},
	{"gfx3", {"gfx3"}, DefEncoding::Plain, 1.0, ""},
	{"error_hiptheta", {"error_hip_theta_fp16"}, DefEncoding::Fixed16, 1.0, ""},
	{"error_uptheta", {"error_up_theta_fp16"}, DefEncoding::Fixed16, 1.0, ""},
	{"renderfov", {"renderfov"}, DefEncoding::Plain, 1.0, ""},
	{"scope_min_mag", {"scope_min_mag"}, DefEncoding::Plain, 1.0, ""},
	{"soundfireloop", {"soundfireloop"}, DefEncoding::Plain, 1.0, ""},
	{"soundtrailoff", {"soundtrailoff"}, DefEncoding::Plain, 1.0, ""},
	{"vmacrotoken", {"vmacrotoken"}, DefEncoding::Plain, 1.0, ""},
	{"soundhead", {"soundhead"}, DefEncoding::Plain, 1.0, ""},
	{"soundlockedtone", {"soundlockedtone"}, DefEncoding::Plain, 1.0, ""},
	{"emplacedstance", {"emplacedstance"}, DefEncoding::Plain, 1.0, ""},
	{"special_hold", {"special_hold"}, DefEncoding::Plain, 1.0, ""},
	{"attack_anim", {"attack_anim"}, DefEncoding::Plain, 1.0, ""},
	{"run_anim", {"run_anim"}, DefEncoding::Plain, 1.0, ""},
	{"category", {"category"}, DefEncoding::Plain, 1.0, ""},
	{"ammoclass", {"ammo_class", "ammo_class_count"}, DefEncoding::Plain, 1.0, ""},
	{"crosshair", {"crosshair", "crosshair_secondary"}, DefEncoding::Plain, 1.0, ""},
	{"hudclipgfx", {"hudclipgfx_offset[0]", "hudclipgfx_offset[1]", "hudclipgfx_texture"}, DefEncoding::Plain, 1.0, ""},
	{"hudrndgfx", {"hudrndgfx_offset[0]", "hudrndgfx_offset[1]", "hudrndgfx_layout[0]", "hudrndgfx_layout[1]", "hudrndgfx_layout[2]", "hudrndgfx_texture"}, DefEncoding::Plain, 1.0, ""},
	{"scope_max_mag", {"scope_max_mag", "scope_max_mag_arg2"}, DefEncoding::Plain, 1.0, ""},
	{"scope_max_zero", {"scope_max_zero_steps", "scope_zero_step", "scope_zero_default", "scope_zero_extra"}, DefEncoding::Plain, 1.0, ""},
	{"switchcategory", {"switchcategory"}, DefEncoding::Plain, 1.0, "has_switchcategory"},
	{"weapon_class", {"weapon_class"}, DefEncoding::WeaponClass, 1.0, ""},
	{"charfilter", {"charfilter[0]", "charfilter[1]", "charfilter[2]", "charfilter[3]", "charfilter[4]", "charfilter[5]", "charfilter[6]", "charfilter[7]"}, DefEncoding::CharacterFilter, 1.0, ""},
	{"teamfilter", {"teamfilter[0]", "teamfilter[1]", "teamfilter[2]", "teamfilter[3]"}, DefEncoding::TeamFilter, 1.0, ""},
	{"classrounds", {"classrounds[0]", "classrounds[1]", "classrounds[2]", "classrounds[3]", "classrounds[4]", "classrounds[5]", "classrounds[6]"}, DefEncoding::ClassRounds, 1.0, ""},
	{"stability", {"stability_fp16[0]", "stability_fp16[1]", "stability_fp16[2]"}, DefEncoding::Fixed16, 1.0, ""},
	{"flags", {"flags", "flags2"}, DefEncoding::WeaponFlags, 1.0, ""},
	{"error", {"error[0]", "error[1]", "error[2]", "error[3]", "error[4]", "error[5]", "error_fp16[0]", "error_fp16[1]", "error_fp16[2]", "error_fp16[3]", "error_fp16[4]", "error_fp16[5]"}, DefEncoding::FloatFixed, 1.0, ""},
	{"weaponweight", {"weaponweight", "weaponweight_fp16"}, DefEncoding::FloatFixed, 1.0, ""},
	{"clipweight", {"clipweight", "clipweight_fp16"}, DefEncoding::FloatFixed, 1.0, ""},
	{"pos", {"pos[0]", "pos[1]", "pos[2]", "pos_rotation_deg_q16[0]", "pos_rotation_deg_q16[1]", "pos_rotation_deg_q16[2]"}, DefEncoding::Pose, 1.0, ""},
	{"tpos", {"tpos[0]", "tpos[1]", "tpos[2]", "tpos_rotation_deg_q16[0]", "tpos_rotation_deg_q16[1]", "tpos_rotation_deg_q16[2]"}, DefEncoding::Pose, 1.0, ""},
	{"scope_paralax_distance", {"scope_paralax_distance_fp16"}, DefEncoding::ScopeParallax, 1.0, ""},
	{"heat_values", {"heat_per_shot", "heat_decay_per_tick"}, DefEncoding::Heat, 1.0, ""},
	{"heat_effect", {"heat_effect", "heat_glow_threshold"}, DefEncoding::Fixed16, 1.0, ""},
};

const std::vector<DefProperty> kAmmoProperties = {
    {"dopplerdiv", {"doppler_divisor"}},
    {"kz_sound", {"kz_sound"}},
	{"min_damage", {"min_damage"}, DefEncoding::Plain, 1.0, ""},
	{"max_damage", {"max_damage"}, DefEncoding::Plain, 1.0, ""},
	{"penetration_impact", {"penetration_impact"}, DefEncoding::Plain, 1.0, ""},
	{"penetration_kz", {"penetration_kz"}, DefEncoding::Plain, 1.0, ""},
	{"secondary_anim", {"secondary_anim"}, DefEncoding::Plain, 1.0, ""},
	{"kz_physics", {"kz_physics"}, DefEncoding::Plain, 1.0, ""},
	{"error", {"error_fp16"}, DefEncoding::Fixed16, 1.0, ""},
	{"drag", {"drag_fp16"}, DefEncoding::Fixed16, 1.0, ""},
	{"bullet_radius", {"bullet_radius_fp16"}, DefEncoding::Fixed16, 1.0, ""},
	{"spread_count", {"spread_count"}, DefEncoding::Plain, 1.0, ""},
	{"kz_damage", {"kz_damage"}, DefEncoding::Plain, 1.0, ""},
	{"kz_minradius", {"kz_minradius_fp16"}, DefEncoding::Fixed16, 1.0, ""},
	{"kz_maxradius", {"kz_maxradius_fp16"}, DefEncoding::Fixed16, 1.0, ""},
	{"scorch_id", {"scorch_id"}, DefEncoding::Plain, 1.0, ""},
	{"scar_type", {"scar_type"}, DefEncoding::Plain, 1.0, ""},
	{"min_stable_velocity", {"min_stable_velocity"}, DefEncoding::Plain, 1.0, ""},
	{"tumble_error", {"tumble_error_fp16"}, DefEncoding::Fixed16, 1.0, ""},
	{"weight_in_grains", {"weight_in_grains"}, DefEncoding::Plain, 1.0, ""},
	{"tracerrate", {"tracer_rate"}, DefEncoding::Plain, 1.0, ""},
	{"frndlytrcrid", {"frndly_trcr_type_id"}, DefEncoding::Plain, 1.0, ""},
	{"foetrcrid", {"foe_trcr_type_id"}, DefEncoding::Plain, 1.0, ""},
	{"velocity", {"velocity"}, DefEncoding::Plain, 1.0, ""},
	{"heat_det_range", {"heat_det_range"}, DefEncoding::Plain, 1.0, ""},
	{"ai_launch", {"ai_launch"}, DefEncoding::Plain, 1.0, ""},
	{"ai_launcheffect", {"ai_launcheffect"}, DefEncoding::Plain, 1.0, ""},
	{"notarmmedammo", {"notarmmed_ammo"}, DefEncoding::Plain, 1.0, ""},
	{"max_age", {"max_age_ticks"}, DefEncoding::FixedSeconds, 1.0, ""},
	{"arm_age", {"arm_age_ticks"}, DefEncoding::FixedSeconds, 1.0, ""},
	{"boresight_maxang", {"boresight_maxang"}, DefEncoding::Degrees, 1.0, ""},
	{"kz_pieslice", {"kz_pieslice_bam"}, DefEncoding::HalfDegrees, 1.0, ""},
	{"armor_density", {"armor_density[0]", "armor_density[1]", "armor_density[2]"}, DefEncoding::Plain, 1.0, ""},
	{"recoil", {"recoil[0]", "recoil[1]", "recoil[2]"}, DefEncoding::Plain, 1.0, ""},
	{"flag", {"flags"}, DefEncoding::AmmoFlags, 1.0, ""},
	{"kztype", {"kztype"}, DefEncoding::AmmoKillZone, 1.0, ""},
	{"mf_light", {"mf_light_value"}, DefEncoding::Plain, 1.0, "mf_light"},
	{"tracer_type", {"tracer_type_friendly", "tracer_type_enemy"}, DefEncoding::Plain, 1.0, ""},
	{"light_move", {"light_move_radius_fp16", "light_move_color"}, DefEncoding::LightMove, 1.0, ""},
	{"light_impact", {"light_impact_radius_fp16", "light_impact_color", "light_impact_ticks"}, DefEncoding::LightImpact, 1.0, ""},
	{"turnrate_maxpit", {"turnrate_maxpit"}, DefEncoding::TurnRate, 1.0, ""},
	{"turnrate_maxyaw", {"turnrate_maxyaw"}, DefEncoding::TurnRate, 1.0, ""},
};

const std::vector<DefProperty> kActionProperties = {
	{"anim", {"anim"}, DefEncoding::Plain, 1.0, ""},
	{"soundset", {"soundset"}, DefEncoding::Plain, 1.0, ""},
	{"soundsetend", {"soundsetend"}, DefEncoding::Plain, 1.0, ""},
	{"particle", {"particle"}, DefEncoding::Plain, 1.0, ""},
	{"particleuserpoint", {"particleuserpoint"}, DefEncoding::Plain, 1.0, ""},
	{"action_value", {"action_value"}, DefEncoding::Plain, 1.0, ""},
	{"delaystart", {"delaystart"}, DefEncoding::Delay, 1.0, ""},
	{"delayend", {"delayend"}, DefEncoding::Delay, 1.0, ""},
	{"function", {"function", "function_args[0]", "function_args[1]", "function_args[2]", "function_args[3]"}, DefEncoding::Function, 1.0, ""},
	{"ctrlreg", {"ctrl_register"}, DefEncoding::Plain, 1.0, ""},
	{"ctrlreginc", {"ctrl_increment"}, DefEncoding::Plain, 1.0, ""},
	{"texttoken", {"text_token"}, DefEncoding::Plain, 1.0, ""},
	{"dupsound", {"duplicate_sound_count", "duplicate_sound_delay"}, DefEncoding::Plain, 1.0, ""},
};

const std::vector<DefProperty> kSightProperties = {
	{"sights", {"texture", "x1", "y1", "x2", "y2", "blend", "scale", "slide", "slide_frames"}, DefEncoding::Sight, 1.0, ""},
};

const std::vector<DefProperty> kAttachmentProperties = {
	{"addeweap", {"userpoint", "item_id", "down_angle", "up_angle", "right_angle", "left_angle", "angle_count", "kind"}, DefEncoding::Attachment, 1.0, ""},
};

const std::vector<DefProperty> kEffectProperties = {
	{"", {"surface_type", "hit_effect", "impact_sound", "value"}, DefEncoding::Plain, 1.0, ""},
};

const std::vector<DefProperty> kCarryProperties = {
	{"ammoclass_max_carry", {"name", "max_carry"}, DefEncoding::Plain, 1.0, ""},
};

} // namespace

const std::vector<DefProperty> &def_properties(DefRecordKind kind) {
	switch (kind) {
	case DefRecordKind::Item: return kItemProperties;
	case DefRecordKind::Weapon: return kWeaponProperties;
	case DefRecordKind::Ammo: return kAmmoProperties;
	case DefRecordKind::Action: return kActionProperties;
	case DefRecordKind::Sight: return kSightProperties;
	case DefRecordKind::Attachment: return kAttachmentProperties;
	case DefRecordKind::Effect: return kEffectProperties;
	case DefRecordKind::Carry: return kCarryProperties;
	}
	return kItemProperties;
}

} // namespace opennova::def
