-- GENERATED by infra/github (local_file.expansions_seed) from
-- local.expansions. DO NOT EDIT BY HAND — run `terraform apply` in infra/github
-- after editing infra/github/expansions.tf, then commit the regenerated file.
--
-- The server applies this from SEED_DIR every boot (apps/novaworld_server/main.cpp
-- apply_seed). UPSERT keeps catalogue metadata in sync with Terraform while
-- preserving `version` (owned by the release pipeline: set_expansion_version on
-- POST /api/admin/expansions/<slug>/release). Idempotent across boots.

INSERT INTO expansions
    (game_id, slug, display_name, summary, version, package_type, install_subdir, featured, github_repo)
SELECT g.id, 'ondx01', 'OpenNova Demo Mod',
       'OpenNova remaster expansion for Delta Force Xtreme 2.', '0.0.0', 'zip',
       'expansion/ondx01', 0, 'opennova-net/ondx01'
FROM games g WHERE g.slug = 'dfx2_consumer'
ON CONFLICT(slug) DO UPDATE SET
    display_name   = excluded.display_name,
    summary        = excluded.summary,
    package_type   = excluded.package_type,
    install_subdir = excluded.install_subdir,
    featured       = excluded.featured,
    github_repo    = excluded.github_repo,
    updated_at     = CURRENT_TIMESTAMP;

INSERT INTO expansions
    (game_id, slug, display_name, summary, version, package_type, install_subdir, featured, github_repo)
SELECT g.id, 'onjo01', 'OpenNova Demo Mod',
       'OpenNova remaster expansion for Joint Operations.', '0.0.0', 'zip',
       'expansion/onjo01', 0, 'opennova-net/onjo01'
FROM games g WHERE g.slug = 'jop_2_consumer'
ON CONFLICT(slug) DO UPDATE SET
    display_name   = excluded.display_name,
    summary        = excluded.summary,
    package_type   = excluded.package_type,
    install_subdir = excluded.install_subdir,
    featured       = excluded.featured,
    github_repo    = excluded.github_repo,
    updated_at     = CURRENT_TIMESTAMP;

INSERT INTO expansions
    (game_id, slug, display_name, summary, version, package_type, install_subdir, featured, github_repo)
SELECT g.id, 'revx02', 'Tactical Assault Coalition',
       'Coalition expansion package for Joint Operations', '2024.05.15', 'zip',
       'expansions/revx02', 1, 'opennova-net/revx02'
FROM games g WHERE g.slug = 'jop_2_consumer'
ON CONFLICT(slug) DO UPDATE SET
    display_name   = excluded.display_name,
    summary        = excluded.summary,
    package_type   = excluded.package_type,
    install_subdir = excluded.install_subdir,
    featured       = excluded.featured,
    github_repo    = excluded.github_repo,
    updated_at     = CURRENT_TIMESTAMP;
