// Each kind of project file in a modder's words (asset_kind_words.h).
#include "asset_kind_words.h"

#include <iterator>

namespace opennova::editor {
namespace {

constexpr AssetKindWords kWords[] = {
	{AssetKind::Unknown, "A file of no kind the game knows: no part of the game asks for a file of its name or reads one of its kind.", "Nothing in the game reads it; since the game never asks for it, the editor's build leaves it out of the archives.", "engine/editor/assets/asset_kinds.cpp, the Unknown row's comment (the game never asks for one, so the build leaves it out; S13 A8)"},
	{AssetKind::Archive, "A PFF archive: a packed container of game files, such as resource.pff, localres.pff, language.pff or an expansion's pair.", "The game mounts its archives by fixed names at boot; inside a project the editor refuses one, since its build packs the project's own files into archives.", "[orig: PFF_OpenAllArchives @ 0x4a4310]; engine/editor/assets/asset_kind.h (Archive: never a project asset, a build output); engine/editor/project_build/build_plan.cpp own_finding (BuildArchiveInProject)"},
	{AssetKind::Model, "A 3D model: its meshes at each level of detail, materials, collision and occlusion shapes, lights, named attachment points and moving parts.", "Loaded by name as an object is set up (the look and wreck models its item definition names), and for the sky, the sun and moon models a mission's .env names.", "[orig: EntityDef_LoadModelsAndCallbacks @ 0x439F50; ThreediGp_LoadFromFile @ 0x5B5780; EffectWorld_LoadCelestialModels @ 0x5ADC50]"},
	{AssetKind::Animation, "A skeletal animation clip: each bone's motion frame by frame, with its movement record, for a character's body or a first-person view.", "Loaded by name when an animation map's row names it (one that fails to load takes failsafe.bad, which JO does not ship), and by the menu's player preview.", "[orig: AnimMap_ParseConfigLine @ 0x40CB60; AnimMap_FindOrLoadBoneFile @ 0x40C030; PlayerInfo_InitPreviewModel @ 0x5600D0]"},
	{AssetKind::AnimationMap, "A text table naming, for each animation slot (reset, idle, attack, death and so on), the clips a character or a first-person weapon plays.", "Loaded by name when a character is set up (the map its item definition names) or a weapon's first-person animations load; one loaded table serves everything that names it.", "[orig: AnimMap_LoadAdmFile @ 0x40CC40; Game_ReloadEntityModelsAndCallbacks @ 0x522830]"},
	{AssetKind::FaceAnimation, "A character's facial animation: the face's texture meshes, the vertex offsets of its expressions, and its eyes' textures, size and limits.", "Loaded when a character is set up, by its model's name with .GRM; retail JO ships none, and JO's renderer never shows the face it animates.", "[orig: Entity_InitFromModel @ 0x40E211; FaceAnimConfig_LoadFile @ 0x588BE0]; docs/world/world-wac-ai-re.md (the GRM section)"},
	{AssetKind::AiProfile, "The AI profile of a vehicle or helicopter driver: its type, view and radar ranges and angles, target priorities, speeds and weapon ranges.", "Loaded when a placed vehicle's AI is set up, by the AI file its mission record names, else a default (helo1.aip last); without one the AI targets nothing.", "[orig: AIProfile_LoadOrFind @ 0x45FD80; Entity_InitHelicopterAIFromDef @ 0x4683C0; Entity_InitVehicleAIFromDef @ 0x4686C0]"},
	{AssetKind::Texture, "An image the game draws on models, menus, the HUD, the terrain or the loading screen: a TGA, PCX, DDS, PNG, or an MDT (a ready-made normal map).", "Loaded by name wherever one is named: a model's materials as the model loads, a menu's windows, the HUD's set at a mission's start, the loading screen.", "[orig: Material_LoadStageTexture @ 0x5B16F0; CTextureManager_LoadOrFindTexture @ 0x654980; HUD_LoadAllTextures @ 0x59DDA0; Render_LoadingScreen @ 0x521D10]"},
	{AssetKind::MaterialChunk, "Texture data a model's material reads as a chunk container whatever the file's name: a normal map (NQ8B), an alpha volume (HRZ8) or alpha data (AOC8).", "Loaded with a model whose material names it under one of the three special texture types; a scan of 2,717 models found no stock material using one.", "[orig: Material_LoadStageTexture @ 0x5B16F0; chunk loaders @ 0x58F350, @ 0x58F470, @ 0x58F590]; docs/render/render-material-re.md D-RMAT-12"},
	{AssetKind::Font, "A bitmap font: pictures of its 224 characters on 256-pixel pages, with each character's place and the spacing between them.", "Loaded by name: the HUD and menu set as the main menu opens, each font a menu window names when its menu loads, and the loading screen's two.", "[orig: HUD_InitAllFonts @ 0x51EE20 -> HUD_LoadFontIntoSlot @ 0x580400; CFontCache_LoadOrGetFont @ 0x652F70; Render_LoadingScreen @ 0x521D10]"},
	{AssetKind::Strings, "A localized string table: the game's texts under named sections and keys, such as item names, menu texts or a mission's messages.", "Read at boot (gameerr, gametext, vmacros and keyhelp.bin; the game exits without the last three), at the main menu (game.bin, menutxt.bin) and at a mission's start (its own).", "[orig: Game_InitSubsystems @ 0x4A6CD0 (@ 0x4A6FED, @ 0x4A702F, @ 0x4A7072); Menu_InitShellResources @ 0x552510; TextResource_LoadMissionTextBin @ 0x51ED90]"},
	{AssetKind::MusicScript, "A compiled music script: a small program that picks which tracks of its music bank play, and when, from the game's music state.", "Loaded by name with its bank: MENUMUS.BIN as the main menu opens, GAMEMUS.BIN at a multiplayer mission's start (an expansion's M<name>.bin and G<name>.bin instead).", "[orig: AudioVM_InitMenuMusicStreaming @ 0x56AA60; Game_StartMission @ 0x525581 -> AudioVM_OpenMusicContext @ 0x6722A0; AudioVM_LoadScriptFile @ 0x672D20]"},
	{AssetKind::RawBin, "A .bin that is neither a string table nor a music script: a raw table or marker, such as fgn2.bin or the stored credentials epass.bin and passgen.bin.", "Unknown: no reader of raw .bin files as such is witnessed; fgn2.bin is only checked for at boot (its presence picks the German effects), and epass.bin and passgen.bin load as stored credentials.", "[orig: Game_LoadConfig @ 0x551480 (fgn2.bin @ 0x5514E8); CEffectSystem_Init @ 0x5F6070; EPass_LoadStoredCredentials @ 0x450B20; EPass_LoadCredentials @ 0x450EB0]"},
	{AssetKind::CountryCode, "The install's country code (us, for one), lightly encoded, which the game reports in its settings when it joins a multiplayer game.", "Read at boot with the C library from the game's own folder, never from an archive or an expansion's folder; missing, the game runs with no country code.", "[orig: Game_ReadCCBinFile @ 0x4A5860]; docs/net/novaworld-net-re.md (COUNTRYCODE, D-NET-296)"},
	{AssetKind::Credits, "The scrolling credits: lines of text with their fonts, colours, alignment and images, in NovaLogic's encoded binary configuration form.", "A menu's credits window loads it when its menu loads, by the name its data source gives (the shipped nlist.kda, on the options menu's credits).", "[orig: CMarqueeWnd_LoadCreditsFromIni @ 0x65C5A0 -> ConfigFile_LoadGlobal @ 0x760AD0]; docs/mnu/menu-re.md (Marquee / credits)"},
	{AssetKind::Mission, "A mission: its settings, the player's starting weapons, every placed item, building, marker and character, its waypoints, zones, groups and scripted events.", "The mission list scans for .bms files at boot (loose, or in localres.pff or language.pff, never resource.pff); the host loads the chosen one at the mission's start, a joiner never.", "[orig: MissionList_ScanAndBuildFromFiles @ 0x563170; Mission_BuildMapListFromPFF @ 0x562910; Game_StartMission @ 0x524360 -> Mission_LoadBMSFile @ 0x40F4E0]"},
	{AssetKind::MissionText, "The interchange text of NovaLogic's original mission editor (dfx2med.exe) for a mission, which the Nile editor can also import.", "The game never reads it: its program holds no .mis name and no reader of one. The build leaves it out and the editor opens it in no document.", "docs/mission/mis-format-re.md, Current verdict (What the game reads: the .bms alone, Mission_LoadBMSFile @ 0x40F4E0); engine/editor/assets/asset_kinds.cpp, the MissionText row's comment"},
	{AssetKind::MapProject, "A map project of NovaLogic's Nile mission editor: a compressed XML scene of a mission, which retail lists among its missions.", "Retail's mission list, built at boot, takes one (loose or archived) as it takes a .bms and loads it through an XML loader not yet read; OpenNova lists none yet.", "[orig: Mission_BuildMapListFromPFF @ 0x562910; MissionList_ScanAndBuildFromFiles @ 0x563170; Mission_ParseMapFileHeader @ 0x4CCAB0]; docs/mission/mis-format-re.md D-MIS-7"},
	{AssetKind::Terrain, "A terrain's settings text: its colour and detail maps, the height data file it uses, its tile set, its sector layout and its edge locks.", "Read as a mission loads its terrain (a mission whose terrain does not load does not start), and parsed again for any time-of-day colours before the .env.", "[orig: Game_StartMission @ 0x524B26 -> Game_LoadTerrainDuringConnect @ 0x520710 -> Terrain_LoadEnvironmentConfig @ 0x610940; Environment_LoadTimeOfDayConfig @ 0x57DB30]"},
	{AssetKind::TerrainPolyData, "A terrain's height data: the compressed height map and ground mesh that its terrain settings (.trn) name.", "Opened as a mission's terrain starts up, by the name its .trn gives; the load never checks whether it opened.", "[orig: Terrain_Init @ 0x60FBE0 -> PolyTrn_LoadTerrainConfig @ 0x60E3D0]"},
	{AssetKind::TileInfo, "A mission's tile placements: which tile of the terrain's tile set is painted where (water, decals), each with its flips and rotation.", "Read as a mission's terrain loads, found by the mission's name and read loose first; without one the terrain's own tiles stand.", "[orig: Terrain_LoadTileInfoFile @ 0x60A740]"},
	{AssetKind::Environment, "A mission's environment: time-of-day colour keyframes, fog, sky and cloud maps, water, weather and the sun, moon, glare and star models.", "Read as a mission loads, after its terrain's .trn and overcast.def; one that is missing or does not parse is skipped and the mission starts on defaults.", "[orig: Terrain_LoadEnvironmentConfig @ 0x610940 -> Environment_LoadTimeOfDayConfig @ 0x57DB30]"},
	{AssetKind::Menu, "A menu: one or more screens of windows (buttons, lists, tables, text, images) with the actions and sounds they run.", "main.mnu loads as the main menu opens (its Startup screen); others load when a menu action or the game names them, such as cmap.mnu at a mission's start.", "[orig: Menu_InitShellResources @ 0x552651 -> UIScene_LoadAndParseContent @ 0x63C830]"},
	{AssetKind::MenuStyle, "A stylesheet: named values (fonts, colours, images) that the menus use as %NAME% variables.", "Only menu_style.mns, then brand.mns, are read, as the main menu opens, a later definition winning; a .mns of any other name is never read.", "[orig: Menu_InitShellResources @ 0x552604, @ 0x552616 -> NapiConfigMap_LoadIncludeFile @ 0x63B970]"},
	{AssetKind::MusicBank, "Music audio: a bank of tracks that a music script plays by number, streamed from disk as they play.", "Streamed by path, never from an archive: MENUMUS.SBF as the main menu opens, GAMEMUS.SBF at a multiplayer mission's start (an expansion's M<name>.sbf, G<name>.sbf from its folder).", "[orig: AudioVM_InitMenuMusicStreaming @ 0x56AA60; AudioVM_OpenMusicContext @ 0x6722A0; Expansion_LoadAssets @ 0x4A4906, @ 0x4A4936]"},
	{AssetKind::SoundBank, "A sound bank: named sound sets, each with layers of members that name the waves to play, with their volume, pitch and distance falloff.", "Opened by name: the mission banks (game.lwf and its kin) at a mission's start, menu.lwf for the player screen, a mission's dialog sounds, a menu window's sound.", "[orig: SoundBank_OpenFile @ 0x75CAA0; Game_StartMission @ 0x525443; PlayerInfo_InitProfileSelector @ 0x5613BA; SoundBank_CollectionAddOrRef @ 0x652B40]"},
	{AssetKind::Wave, "One recorded sound (a .wav), which a sound bank's sets or a mission script's voice lines play.", "Loaded from the archives by its name, as a sound bank's sounds name it or a mission script's wave command plays it.", "[orig: Audio_LoadWavFileFromArchive @ 0x766480]; docs/audio/lwf-dbf-sound-re.md (WAC scripted voice)"},
	{AssetKind::DialogBank, "A mission's radio dialog: numbered dialogs, each a run of lines naming the sounds to play in turn.", "Read at a mission's start, found by the mission's name, its sounds from the mission's own .lwf (else .pwf); without one the mission plays no dialog.", "[orig: DialogSystem_Init @ 0x5275E0 -> DialogManager_LoadFromFile @ 0x44E650]"},
	{AssetKind::Particles, "Effect definitions in text: each effect's particles, their textures and motion, and the tables that shape their colour and size over time.", "Read at boot: every .ptl, loose and archived, with the .ptu set, or the German .ptg set when fgn2.bin is present.", "[orig: CEffectSystem_Init @ 0x5F6070 -> CEffectWorld_ParseSectionCallback @ 0x5ECB40]"},
	{AssetKind::Script, "A mission script in text: commands the game compiles and runs during a mission, such as triggers, orders, weather, sounds and texts.", "At a mission's start game.wac, server.wac and the mission's own (by its name) compile, in that order, into one program; a script's RUN command loads another.", "[orig: WacScript_InitAndLoad @ 0x4F91F0; Script_LoadAndCompileFile @ 0x4EE660]"},
	{AssetKind::ItemDefs, "Every kind of object the game can place: its id, name, type (person, vehicle, building and so on), models, animations, sounds, health and physics.", "Read at boot; a missing file boots with no item definitions (its fatal error is never reached), and repeated ids or names are only logged.", "[orig: Game_InitSubsystems @ 0x4A71A3 -> ItemDefs_LoadAndValidate @ 0x4A1DA0]"},
	{AssetKind::WeaponDefs, "Every weapon: its name, ammunition, firing and animations, first-person and HUD look, weight, and which classes and teams may carry it.", "Read at boot for the loadout lists, and again at a mission's start for its weapons; missing, the weapon list holds only None.", "[orig: WeaponDef_LoadAll @ 0x54DD10; Game_StartMission @ 0x5254B8]"},
	{AssetKind::AmmoDefs, "Every ammunition type: its flags, speed, lifetime, spread, drag, damage, penetration, tracers, guidance and kill zones.", "Read at a mission's start; missing, the mission has no ammunition types.", "[orig: Game_StartMission @ 0x52548A -> AmmoDef_LoadAll @ 0x40B0B0]"},
	{AssetKind::HudPosDefs, "The HUD's layout: where each gauge, readout and frame sits (in a 1024 by 768 design space), its fonts, and each vehicle's HUD.", "Read at a mission's start as the HUD sets up; missing, the HUD uses its default positions.", "[orig: HUD_InitOverlaySystem @ 0x5A4620 (hudpos @ 0x5A4931) -> HUD_ParseHudposToken @ 0x59F370]"},
	{AssetKind::HudFxDefs, "HUD definitions the game reads by this name at a mission's start; what the file holds is not yet documented.", "Read at a mission's start as the HUD sets up, before hudpos.def; skipped silently when missing.", "[orig: HUD_InitOverlaySystem @ 0x5A4620 (hudfx @ 0x5A462E)]"},
	{AssetKind::AvatarDefs, "The player characters to choose from: head, body and arms parts combined into characters, grouped by nationality and division.", "Read at boot, before items.def; the player screen lists its characters, and each player's look is built from the one chosen.", "[orig: Game_InitSubsystems @ 0x4A70B5 -> CAvatarDefs_Init @ 0x57B180]"},
	{AssetKind::SoundProfileDefs, "Named sound profiles: for each of 51 slots (footsteps, deaths, doors, engines, impacts and more), the sound set an item plays.", "Read at boot, and again when an expansion reloads. Missing, the table the game allocated for it is never cleared, and every item binds its first slot: a mission's items take their sounds from that memory, and the game can hang or crash.", "[orig: Game_InitSubsystems @ 0x4A7141 -> SoundProfile_LoadAll @ 0x527490; ItemDef_AllocateWithDefaults @ 0x49E3EA -> SoundProfile_FindSlotByName @ 0x526E30]"},
	{AssetKind::CharAttrDefs, "Up to 16 character classes' attributes: stealth, health bonus, recoil, reload, crosshair and scope modifiers, camouflage, run speed and abilities such as medic.", "Read at boot, after the subsystems start; missing, the game logs that it could not load the character attributes and goes on.", "[orig: Game_Run @ 0x4A7FE3 -> CharAttr_LoadFromDef @ 0x412140]"},
	{AssetKind::PowerupDefs, "The pickups: what each gives (health, all ammunition, a weapon), how often and how many times it respawns, and its pickup sound.", "Read at a mission's start and bound to the items that name a row; missing, the game logs that it is unable to load powerup.def and goes on.", "[orig: Game_StartMission @ 0x5256CD -> PowerUpDef_LoadFromFile @ 0x443350]"},
	{AssetKind::OtherDefs, "A definitions text under a name no other kind claims, such as overcast.def (the overcast weather's colours) or reverb.def (the audio's reverb presets).", "Unknown: no reader of .def files as such is witnessed; the game reads one only by a name it knows, as overcast.def at a mission's load and reverb.def for the audio.", "[orig: Environment_LoadTimeOfDayConfig @ 0x57DB30 (overcast.def); Audio_LoadReverbDefs @ 0x766D80 (reverb.def)]"},
	{AssetKind::StringTableCoo, "The menu's saved NovaWorld data, its browser cookies among it, every string encrypted with a key from this computer, so it reads back only here.", "Read as the main menu opens, from the game's own folder with the C library (never an archive or an expansion's folder), and rewritten in place when the game quits.", "[orig: CUIStringTable_OpenAndLoad @ 0x63A500 (from @ 0x55262B); CUIStringTable_LoadFromFile @ 0x64F290; sub_63BA60 @ 0x63BA9A]; docs/net/novaworld-net-re.md D-NET-267"},
	{AssetKind::NovaWorldScreen, "A NovaWorld screen as a brace-delimited UI script: the error page (nw_error.mnx) or the login's start page (nw_startup.mnx).", "Loaded by name when the NovaWorld error or login screen opens, or a menu row names it; from the archives only, unless the game runs with /d.", "[orig: UI_ShowNovaWorldErrorMessage @ 0x558449; UI_EnterNovaWorldMenu @ 0x558937; @ 0x63E1B0 -> process_ui_script_buffer @ 0x63CBE0; FileSystem_OpenFile @ 0x75B1C0]"},
	{AssetKind::Video, "A Bink video: the prologue and intro films, or the menus' main, header and footer videos.", "Played as the main menu first opens (prolog.bik, intro.bik) or shown in the menus, each from the expansion's folder first, then the install's; a missing one is skipped.", "[orig: Game_PlayIntroVideos @ 0x5637A0; UI_CreateMenuBinkVideos @ 0x54B590]"},
	{AssetKind::PlayerSave, "The player's saved profiles in five slots: key bindings and options in player.sav; character, class and kits in weapon.sav.", "Read as the main menu opens (weapon.sav from the expansion's folder first) and written when the profile is saved; missing or unreadable, the game starts a fresh profile.", "[orig: PlayerProfile_LoadAllFromDisk @ 0x54F4D0; PlayerProfile_SaveToFiles @ 0x54BE00; PlayerProfile_InitDefaults @ 0x54BB40]"},
	{AssetKind::Shader, "An HLSL effect, stored encrypted: the shader techniques and passes that models' materials draw with.", "Read at boot as the renderer starts: every .fx in every mounted archive (or in a loose override folder), decrypted as it loads.", "[orig: HLSLEffect_InitAndLoadAll @ 0x5B0080 -> HLSLEffect_LoadAllFromPFFArchive @ 0x5AFED0 -> HLSLEffect_LoadFromFile @ 0x5AE690; ScriptFile_LoadAndDecrypt @ 0x5AE060]"},
	{AssetKind::Config, "A settings file the game reads by name, such as game.cfg (the game's settings), admin.cfg (server administration) or gt.ssc (an encrypted override).", "Read by name at boot (game.cfg, again at the main menu; assets.cd; gt.ssc; admin.cfg), each skipped silently when missing, game.cfg then taking defaults.", "[orig: Game_LoadConfig @ 0x551480; Game_ReadAssetsCDFile @ 0x4A5800; Mission_LoadEncryptedConfig @ 0x4CDCD0; CAdminServer_LoadConfig @ 0x406D80]"},
	{AssetKind::Score, "The scoring table: the points each event scores and the end-of-round scoreboard's columns, for each game type.", "Read loose by its bare name from the install's folder when the game types' default settings are made, and written there with the defaults when missing.", "[orig: GameType_CreateDefaultSettings @ 0x52DD00 -> ScoreConfig_LoadFile @ 0x52D8A0; ScoreConfig_SaveFile @ 0x52CDD0]"},
	{AssetKind::Text, "Plain text the game reads by name from its folder, such as earlyerr.txt (errors shown before the archives open) or filter.txt (the chat filter).", "Read loose by its bare name: earlyerr.txt when an early error shows, filter.txt at boot, and an expansion's version.txt for the checksum a joiner must match.", "[orig: Game_ShowEarlyError @ 0x4A68A0 -> Game_ReadLineFromFile @ 0x4A59A0; ChatFilter_LoadFromFile @ 0x4FD640; Expansion_LoadAssets @ 0x4A4858]"},
	{AssetKind::ImportSource, "A source file the project imports, such as a PNG the image importer turns into the game's PCX, marked by its import record beside it.", "The game never reads it: the editor's import converts it into game files named after it, and the build packs those outputs, never the source.", "engine/editor/assets/asset_kinds.cpp, the ImportSource row's comment (scan_project_assets); CONTEXT.md, Import / sidecar"},
};

constexpr bool in_order() {
	for (size_t i = 0; i < std::size(kWords); ++i)
		if (size_t(kWords[i].kind) != i) return false;
	return std::size(kWords) == kAssetKindCount;
}
static_assert(in_order(), "one row per AssetKind, in the enum's order");

} // namespace

const AssetKindWords &asset_kind_words(AssetKind kind) {
	const size_t index = size_t(kind);
	return kWords[index < std::size(kWords) ? index : 0];
}

} // namespace opennova::editor
