/* The witnessed boot-required resource manifest (ENG-6). Every row is
   transcribed from the R8 record (docs/required-resources.md) — that file is
   the witness source; edits land there first and here in the same change. */
#include "gameprofile/required_resources.h"

#include <ctype.h>
#include <stddef.h>

static const NovaRequiredResource k_required_resources[] = {
    /* --- Boot (Game_Run -> Game_InitSubsystems), witnessed order --- */
    { "game.cfg", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, 0,
      "missing -> silent Config_SetDefaults; version key != 0x1D re-defaults",
      "[orig: Game_LoadConfig @ 0x551480 via File_ParseASCIIFileWithCallback @ 0x53d980]" },
    { "fgn2.bin", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, 0,
      "existence flag only, never parsed",
      "[orig: @ 0x5514e8]" },
    { "assets.cd", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, 0,
      "missing -> empty string, silent",
      "[orig: Game_ReadAssetsCDFile @ 0x4a5800]" },
    { "CC.BIN", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, 0,
      "missing -> empty country code, silent",
      "[orig: Game_ReadCCBinFile @ 0x4a5860; value @ 0x4a5950]" },
    { "filter.txt", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, 0,
      "silent skip",
      "[orig: ChatFilter_LoadFromFile @ 0x4fd640]" },
    { "expansion\\<n>\\<n>.pff", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, NOVA_RES_F_PATTERN,
      "absent -> expansion unregistered, base game proceeds (<n>L.pff sibling; <n>.bin names it)",
      "[orig: Expansion_ScanAndRegister @ 0x4a43d0; Expansion_LoadAssets @ 0x4a4730]" },
    { "resource.pff", NOVA_BOOT_PHASE_BOOT, NOVA_RES_FATAL, NOVA_RES_F_PFF_TABLE_ANY,
      "zero boot-table archives opened -> earlyerr.txt line-3 dialog + exit; any single archive may be absent",
      "[orig: PFF_OpenAllArchives @ 0x4a4310 over the name table @ 0x829f90; fatal check @ 0x4a6f44]" },
    { "localres.pff", NOVA_BOOT_PHASE_BOOT, NOVA_RES_FATAL, NOVA_RES_F_PFF_TABLE_ANY,
      "zero boot-table archives opened -> earlyerr.txt line-3 dialog + exit; any single archive may be absent",
      "[orig: PFF_OpenAllArchives @ 0x4a4310 over the name table @ 0x829f90; fatal check @ 0x4a6f44]" },
    { "language.pff", NOVA_BOOT_PHASE_BOOT, NOVA_RES_FATAL, NOVA_RES_F_PFF_TABLE_ANY,
      "zero boot-table archives opened -> earlyerr.txt line-3 dialog + exit; any single archive may be absent",
      "[orig: PFF_OpenAllArchives @ 0x4a4310 over the name table @ 0x829f90; fatal check @ 0x4a6f44]" },
    { "gameerr.bin", NOVA_BOOT_PHASE_BOOT, NOVA_RES_DIALOG, 0,
      "missing -> earlyerr.txt line-4 dialog, then boot continues",
      "[orig: @ 0x4a6fc8]" },
    { "gametext.bin", NOVA_BOOT_PHASE_BOOT, NOVA_RES_FATAL, 0,
      "\"Unable to load game strings\" MessageBox + exit",
      "[orig: Game_InitSubsystems @ 0x4a6fed]" },
    { "vmacros.bin", NOVA_BOOT_PHASE_BOOT, NOVA_RES_FATAL, 0,
      "\"Unable to load voice macro strings\" MessageBox + exit",
      "[orig: @ 0x4a702f]" },
    { "keyhelp.bin", NOVA_BOOT_PHASE_BOOT, NOVA_RES_FATAL, 0,
      "\"Unable to load keyboard map strings\" MessageBox + exit",
      "[orig: @ 0x4a7072]" },
    { "weapon.def", NOVA_BOOT_PHASE_BOOT, NOVA_RES_REQUIRED, 0,
      "missing -> silent; weapon table left with a single \"None\" entry (SCR-encrypted supported, key 0x2A5A8EAD)",
      "[orig: WeaponDef_LoadAll @ 0x54dd10; mission slots @ 0x5254b8]" },
    { "Avatars.def", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, 0,
      "silent skip",
      "[orig: CAvatarDefs_Init @ 0x57b180]" },
    { "SndProf.def", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, 0,
      "silent skip (empty 128-slot sound-profile table)",
      "[orig: @ 0x4a7141 -> SoundProfile_LoadAll @ 0x527490]" },
    { "gt.ssc", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, 0,
      "silent skip (gate-tag override, key \"jop:2:oyez\")",
      "[orig: Mission_LoadEncryptedConfig @ 0x4cdcd0]" },
    { "items.def", NOVA_BOOT_PHASE_BOOT, NOVA_RES_FATAL, 0,
      "fatal \"Unable to load items.def\" wired at the callsite (the loader as decompiled always returns success; see the record's Not-witnessed)",
      "[orig: @ 0x4a71a3 -> ItemDefs_LoadAndValidate @ 0x4a1da0 -> Game_FatalErrorWithMessageBox @ 0x4a5160]" },
    { "charattr.def", NOVA_BOOT_PHASE_BOOT, NOVA_RES_SOFT, 0,
      "missing -> _errlog.txt \"Server ERROR! Could not load charattr definitions.\", continues",
      "[orig: Game_Run @ 0x4a7fe3 -> CharAttr_LoadFromDef @ 0x412140]" },
    { "loading.pcx", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, 0,
      "graceful texture miss",
      "[orig: Game_ShowLoadingScreen @ 0x4a544f]" },
    { "*.npj/*.npz", NOVA_BOOT_PHASE_BOOT, NOVA_RES_REQUIRED, NOVA_RES_F_PATTERN,
      "none found -> empty mission list (the only wildcard scan at boot)",
      "[orig: MissionList_ScanAndBuildFromFiles @ 0x563170]" },
    { "hiscore.txt", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, 0,
      "silent skip",
      "[orig: HUD_LoadHighScoreText @ 0x5630e5]" },
    { "admin.cfg", NOVA_BOOT_PHASE_BOOT, NOVA_RES_OPTIONAL, 0,
      "silent skip",
      "[orig: CAdminServer_LoadConfig @ 0x406d80; callsite @ 0x4a72c2]" },

    /* --- Main menu (sub_552500 enter), witnessed order --- */
    { "game.bin", NOVA_BOOT_PHASE_MENU, NOVA_RES_REQUIRED, 0,
      "load unchecked; menu strings absent if missing",
      "[orig: @ 0x552510, lazy resource @ 0x25510f8]" },
    { "player.sav", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "missing/bad magic -> profile defaults + first-run flag",
      "[orig: PlayerProfile_LoadAllFromDisk @ 0x54f4d0 (@ 0x54f586)]" },
    { "weapon.sav", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "missing/bad magic -> profile defaults; resolved expansion\\<n>\\ first",
      "[orig: PlayerProfile_LoadAllFromDisk @ 0x54f4d0 (@ 0x54f6c7)]" },
    { "prolog.BIK", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "exists-checked, skipped (loose-only via Win32 OpenFile, never in PFFs)",
      "[orig: Game_PlayIntroVideos @ 0x5637a0]" },
    { "intro.BIK", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "exists-checked, skipped (loose-only via Win32 OpenFile, never in PFFs)",
      "[orig: Game_PlayIntroVideos @ 0x5637a0]" },
    { "MENUMUS.SBF", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "graceful (silent menu music); expansion form M<n>.sbf; bank streams loose by path",
      "[orig: AudioVM_InitMenuMusicStreaming @ 0x56aa60; names set Expansion_LoadAssets @ 0x4a4798]" },
    { "MENUMUS.BIN", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "graceful (silent menu music); expansion form M<n>.bin",
      "[orig: AudioVM_InitMenuMusicStreaming @ 0x56aa60; names set Expansion_LoadAssets @ 0x4a4798]" },
    { "menu_style.mns", NOVA_BOOT_PHASE_MENU, NOVA_RES_REQUIRED, 0,
      "silent skip -> unstyled UI (menu fonts/colors come from its KEY set)",
      "[orig: @ 0x552604 via NapiConfigMap_LoadIncludeFile @ 0x63b970]" },
    { "brand.mns", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "silent skip (retail ships none; appended after menu_style.mns)",
      "[orig: @ 0x552616 via NapiConfigMap_LoadIncludeFile @ 0x63b970]" },
    { "main.bik", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "expansion -> default path fallback; missing -> no menu video",
      "[orig: UI_CreateMenuBinkVideos @ 0x54b590; strings @ 0x7d2a00-0x7d2a54]" },
    { "header.bik", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "expansion -> default path fallback; missing -> no menu video",
      "[orig: UI_CreateMenuBinkVideos @ 0x54b590; strings @ 0x7d2a00-0x7d2a54]" },
    { "footer.bik", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "expansion -> default path fallback; missing -> no menu video",
      "[orig: UI_CreateMenuBinkVideos @ 0x54b590; strings @ 0x7d2a00-0x7d2a54]" },
    { "nw_cdata.coo", NOVA_BOOT_PHASE_MENU, NOVA_RES_REQUIRED, 0,
      "HRESULT ignored",
      "[orig: @ 0x55262b -> sub_63A500]" },
    { "main.mnu", NOVA_BOOT_PHASE_MENU, NOVA_RES_FATAL, 0,
      "menu never appears — boot dead-ends silently (no dialog); the entry node is \"Startup\"",
      "[orig: sub_552500 @ 0x552651 -> UIScene_LoadAndParseContent @ 0x63c830 -> CUIScene_SelectNodeByName @ 0x63b6b0]" },
    { "menutxt.bin", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "fallback literals used (nw_error.mnx hardcoded @ 0x558449)",
      "[orig: UIStringTable_LookupAndDup @ 0x63b290; e.g. @ 0x55840e, @ 0x5561b7]" },
    { "Arial12b.fnt", NOVA_BOOT_PHASE_MENU, NOVA_RES_REQUIRED, 0,
      "missing -> null font slot, scale 1.0, no crash (text renders nothing; width breakpoints 640/800/1024)",
      "[orig: HUD_InitAllFonts @ 0x51ee20 -> sub_580400]" },
    { "Arial14n.fnt", NOVA_BOOT_PHASE_MENU, NOVA_RES_REQUIRED, 0,
      "missing -> null font slot, scale 1.0, no crash",
      "[orig: HUD_InitAllFonts @ 0x51ee20 -> sub_580400]" },
    { "Arial14b.fnt", NOVA_BOOT_PHASE_MENU, NOVA_RES_REQUIRED, 0,
      "missing -> null font slot, scale 1.0, no crash",
      "[orig: HUD_InitAllFonts @ 0x51ee20 -> sub_580400]" },
    { "Arial16n.fnt", NOVA_BOOT_PHASE_MENU, NOVA_RES_REQUIRED, 0,
      "missing -> null font slot, scale 1.0, no crash",
      "[orig: HUD_InitAllFonts @ 0x51ee20 -> sub_580400]" },
    { "Arial16b.fnt", NOVA_BOOT_PHASE_MENU, NOVA_RES_REQUIRED, 0,
      "missing -> null font slot, scale 1.0, no crash",
      "[orig: HUD_InitAllFonts @ 0x51ee20 -> sub_580400]" },
    { "Impac22b.fnt", NOVA_BOOT_PHASE_MENU, NOVA_RES_REQUIRED, 0,
      "missing -> null font slot, scale 1.0, no crash (Impact pair loads at every width)",
      "[orig: HUD_InitAllFonts @ 0x51ee20 -> sub_580400]" },
    { "Impac38b.fnt", NOVA_BOOT_PHASE_MENU, NOVA_RES_REQUIRED, 0,
      "missing -> null font slot, scale 1.0, no crash (Impact pair loads at every width)",
      "[orig: HUD_InitAllFonts @ 0x51ee20 -> sub_580400]" },
    { "menu.lwf", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "graceful",
      "[orig: PlayerInfo_InitProfileSelector @ 0x5613ba]" },
    { "PI_Idle.BAD", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "graceful (player-preview idle; PI_actv/PI_LookR/PI_lookL table @ 0x83c830)",
      "[orig: PlayerInfo_InitPreviewModel @ 0x5600d0 (@ 0x560107)]" },
    { "Dt1rst.bad", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "graceful (player-preview rest pose)",
      "[orig: PlayerInfo_InitPreviewModel @ 0x5600d0 (@ 0x560138)]" },
    { "HwmCube.dds", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "graceful (player-preview environment cube)",
      "[orig: PlayerInfo_InitPreviewModel @ 0x5600d0]" },
    { "epass.bin", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "silent skip (stored credentials)",
      "[orig: load_stored_credentials @ 0x450b20]" },
    { "passgen.bin", NOVA_BOOT_PHASE_MENU, NOVA_RES_OPTIONAL, 0,
      "silent skip (stored credentials)",
      "[orig: EPass_LoadCredentials @ 0x450eb0]" },

    /* --- Mission start (Game_StartMission @ 0x524360), witnessed order --- */
    { "failsafe.bad", NOVA_BOOT_PHASE_MISSION, NOVA_RES_REQUIRED, 0,
      "it IS the fallback when a mission .bad is missing; loaded every mission start",
      "[orig: AnimMap_Init @ 0x40be96; AnimMap_FindOrLoadBoneFile @ 0x40c285]" },
    { "gamelocl.lwf", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "exists-checked per slot, silent skip (expansion slots <exp>L.lwf/<exp>.lwf load first)",
      "[orig: @ 0x525443 loop over the 260-byte-stride table @ 0x82a5b0 via SoundBank_LoadIfExists]" },
    { "game.lwf", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "exists-checked per slot, silent skip",
      "[orig: @ 0x525443 loop over the 260-byte-stride table @ 0x82a5b0 via SoundBank_LoadIfExists]" },
    { "game3.lwf", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "exists-checked per slot, silent skip",
      "[orig: @ 0x525443 loop over the 260-byte-stride table @ 0x82a5b0 via SoundBank_LoadIfExists]" },
    { "game2.lwf", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "exists-checked per slot, silent skip",
      "[orig: @ 0x525443 loop over the 260-byte-stride table @ 0x82a5b0 via SoundBank_LoadIfExists]" },
    { "ammo.def", NOVA_BOOT_PHASE_MISSION, NOVA_RES_REQUIRED, 0,
      "silent (empty ammo table); SCR key 0x2A5A8EAD",
      "[orig: @ 0x52548a -> AmmoDef_LoadAll @ 0x40b0b0]" },
    { "powerup.def", NOVA_BOOT_PHASE_MISSION, NOVA_RES_SOFT, 0,
      "_errlog.txt \"Unable to load powerup.def\", continues",
      "[orig: @ 0x5256cd -> sub_443350]" },
    { "medmssn.bin", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "the literal fallback for mission text (<missionbase>.bin exists-checked first)",
      "[orig: TextResource_LoadMissionTextBin @ 0x51ed90]" },
    { "game.wac", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "exists-checked, silent skip (compiled game -> server -> mission into one buffer)",
      "[orig: WacScript_InitAndLoad @ 0x4f91f0 (game @ 0x4f9454)]" },
    { "server.wac", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "exists-checked, silent skip",
      "[orig: WacScript_InitAndLoad @ 0x4f91f0 (server @ 0x4f94bc)]" },
    { "GAMEMUS.SBF", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "graceful (MP mission music; SP stops the music context); expansion form G<n>.sbf",
      "[orig: @ 0x525581-0x525598 -> AudioVM_OpenMusicContext @ 0x6722a0; names @ 0x4a47da]" },
    { "GAMEMUS.BIN", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "graceful (MP mission music); expansion form G<n>.bin",
      "[orig: @ 0x525581-0x525598 -> AudioVM_OpenMusicContext @ 0x6722a0; names @ 0x4a47da]" },
    { "loadscrn.pcx", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "graceful (mission-load screen art)",
      "[orig: render_loading_screen @ 0x521d10 (@ 0x521dd9)]" },
    { "Arials18.fnt", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "graceful (mission-load screen font)",
      "[orig: render_loading_screen @ 0x521d10]" },
    { "Arial22.fnt", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "graceful (mission-load screen font)",
      "[orig: render_loading_screen @ 0x521d10]" },
    { "cmap.mnu", NOVA_BOOT_PHASE_MISSION, NOVA_RES_REQUIRED, 0,
      "load unchecked (in-mission command map UI)",
      "[orig: @ 0x526316/@ 0x526332; Input_HandleActionBinding @ 0x49b91b]" },
    { "game.mnu", NOVA_BOOT_PHASE_MISSION, NOVA_RES_REQUIRED, 0,
      "load unchecked (in-mission menu screen)",
      "[orig: @ 0x49b3b1]" },
    { "weapon.mnu", NOVA_BOOT_PHASE_MISSION, NOVA_RES_REQUIRED, 0,
      "load unchecked (the in-game armory WEAPON screen)",
      "[orig: @ 0x49b8de/@ 0x4e0b44]" },
    { "vehicle.mnu", NOVA_BOOT_PHASE_MISSION, NOVA_RES_REQUIRED, 0,
      "load unchecked (vehicle screen)",
      "[orig: @ 0x49b892/@ 0x4e0af8]" },
    { "stat.mnu", NOVA_BOOT_PHASE_MISSION, NOVA_RES_REQUIRED, 0,
      "load unchecked (end-round stats screen)",
      "[orig: UI_ProcessEndRoundScreenTransition @ 0x5b8636]" },
    { "death.mnu", NOVA_BOOT_PHASE_MISSION, NOVA_RES_REQUIRED, 0,
      "load unchecked (death screen)",
      "[orig: Render_ProcessMainSceneFrame @ 0x5cab7e]" },
    { "mp.mnu", NOVA_BOOT_PHASE_MISSION, NOVA_RES_REQUIRED, 0,
      "load unchecked (multiplayer screen)",
      "[orig: @ 0x5588fa]" },
    { "hudfx.def", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "silent skip",
      "[orig: HUD_InitOverlaySystem @ 0x5a4620 (hudfx @ 0x5a462e)]" },
    { "hudpos.def", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "silent skip (default HUD positions)",
      "[orig: HUD_InitOverlaySystem @ 0x5a4620 (hudpos @ 0x5a4931)]" },
    { "monogram.tga", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "graceful (mission UI texture)",
      "[orig: @ 0x525aa3-0x525aad]" },
    { "boxtile.tga", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "graceful (mission UI texture)",
      "[orig: @ 0x525aa3-0x525aad]" },
    { "border.tga", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "graceful (mission UI texture)",
      "[orig: @ 0x525aa3-0x525aad]" },
    { "upl.3di", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "lazy, null on miss (celestial models are data-driven from the mission .env)",
      "[orig: EffectWorld_LoadCelestialModels @ 0x5add25]" },
    { "couri20b.fnt", NOVA_BOOT_PHASE_MISSION, NOVA_RES_OPTIONAL, 0,
      "graceful",
      "[orig: @ 0x572a67 / @ 0x572f24]" },
};

enum { k_required_resource_count =
           (int)(sizeof(k_required_resources) / sizeof(k_required_resources[0])) };

int gameprofile_required_resource_count(void) {
    return k_required_resource_count;
}

const NovaRequiredResource *gameprofile_required_resource_at(int index) {
    if (index < 0 || index >= k_required_resource_count) {
        return NULL;
    }
    return &k_required_resources[index];
}

static int name_equals_ci(const char *a, const char *b) {
    while (*a && *b) {
        if (tolower((unsigned char)*a) != tolower((unsigned char)*b)) {
            return 0;
        }
        ++a;
        ++b;
    }
    return *a == '\0' && *b == '\0';
}

const NovaRequiredResource *gameprofile_required_resource_find(const char *name) {
    if (!name) {
        return NULL;
    }
    for (int i = 0; i < k_required_resource_count; ++i) {
        if (name_equals_ci(k_required_resources[i].name, name)) {
            return &k_required_resources[i];
        }
    }
    return NULL;
}
