#!/usr/bin/env python3
"""Generate libs/wac/src/command_table.gen.cpp from the extracted WAC ISA schema.

Source of truth: notes/wac/wac_commands.schema.json (dumped from Jointops.exe's
command table @0x82D290). Re-run after re-extracting the schema.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# Schema is vendored next to this generator (extracted from Jointops.exe's command
# table @0x82D290; see notes/wac/wac.md). Keeps the registry regenerable + auditable.
SCHEMA = os.path.join(HERE, "wac_commands.schema.json")
OUT = os.path.join(HERE, "..", "src", "command_table.gen.cpp")

PT_ENUM = [
    "Null", "Value", "Number", "Red", "Green", "Blue", "Distance", "Heading",
    "Seconds", "Hour", "Meters", "Ssn", "Group", "Team", "Area", "Target",
    "WpList", "Text", "Filename", "SoundSet", "TextToken", "Face", "Fx", "Ammo",
    "Anim", "Cheat", "IfName", "Variable",
]


def main():
    with open(SCHEMA) as f:
        doc = json.load(f)
    cmds = doc["commands"]
    lines = []
    lines.append("// AUTO-GENERATED by libs/wac/tools/gen_command_table.py -- do not edit by hand.")
    lines.append("// Source: notes/wac/wac_commands.schema.json (Jointops.exe command table @0x82D290).")
    lines.append("#include \"wac/command.h\"")
    lines.append("")
    lines.append("namespace opennova::wac {")
    lines.append("")
    lines.append("namespace {")
    lines.append("const CommandDef kCommands[] = {")
    for c in cmds:
        pts = c["param_types"]
        while len(pts) < 4:
            pts.append(0)
        pt = ", ".join("ParamType::" + PT_ENUM[p] for p in pts[:4])
        name = c["name"].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            "    {\"%s\", 0x%02x, %d, %d, {%s}, 0x%XU}," % (
                name, c["flags"], c["argc"], c["call_conv"], pt,
                int(c["handler_ea"], 16)))
    lines.append("};")
    lines.append("constexpr int kCount = static_cast<int>(sizeof(kCommands) / sizeof(kCommands[0]));")
    lines.append("} // namespace")
    lines.append("")
    lines.append("const CommandDef *wac_commands() { return kCommands; }")
    lines.append("int wac_command_count() { return kCount; }")
    lines.append("")
    lines.append("} // namespace opennova::wac")
    lines.append("")
    text = "\n".join(lines)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d commands)" % (OUT, len(cmds)))


if __name__ == "__main__":
    sys.exit(main())
