#!/usr/bin/env python3
"""Walk JO_ASSETS_t/*.ptl, emit notes/ptl_corpus_catalog.md.

Usage (from the worktree root):

    python notes/scripts/catalog_corpus.py > notes/ptl_corpus_catalog.md
"""
from __future__ import annotations

import pathlib
import re
import sys

CORPUS = pathlib.Path.home() / "Desktop" / "JO_ASSETS_t"

SECT = re.compile(rb"^\[(effectdef|particledef|tabledef|tabledef_edithandles)\]", re.M)
ID = re.compile(rb"\bid\s*=\s*([^;\r\n]+);")


def main() -> int:
    if not CORPUS.is_dir():
        print(f"# .ptl corpus catalog (corpus directory missing: {CORPUS})")
        return 1

    files = sorted(CORPUS.glob("*.ptl"))

    print("# .ptl corpus catalog")
    print()
    print(f"Generated by `notes/scripts/catalog_corpus.py` against `{CORPUS}` ({len(files)} files).")
    print()
    print("| File | KB | [effectdef] | [particledef] | [tabledef] | [edithandles] | First ids |")
    print("|---|---|---|---|---|---|---|")

    for path in files:
        raw = path.read_bytes()
        sections = [m.group(1).decode("ascii") for m in SECT.finditer(raw)]
        ids = [m.group(1).decode("ascii", errors="replace").strip() for m in ID.finditer(raw)]
        first_ids = ", ".join(ids[:5]) + ("…" if len(ids) > 5 else "")
        # Escape pipe chars so we don't break the markdown table.
        first_ids = first_ids.replace("|", "\\|")
        print(
            f"| {path.name} | {len(raw) // 1024} | "
            f"{sections.count('effectdef')} | "
            f"{sections.count('particledef')} | "
            f"{sections.count('tabledef')} | "
            f"{sections.count('tabledef_edithandles')} | "
            f"{first_ids} |"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
