#include <editor/graph/code_text_keys.h>

#include <base/io/strutil.h>
#include <editor/graph/asset_graph.h>

namespace opennova::editor {

namespace {

// Generated from the binary's calls (each row a function's first call of the pair, its address).
const CodeTextKey kRows[] = {
	{"GAME.BIN", "Menu", "ALWAYS", "HostDialog_PopulateWeaponRestrictionList", 0x556699},
	{"GAME.BIN", "Menu", "ALWAYS", "HostDialog_WeaponRestrictionCycleHandler", 0x55778F},
	{"GAME.BIN", "Menu", "ALWAYS", "sub_557910", 0x55799A},
	{"GAME.BIN", "Menu", "CHARCLASS_ENGINEER", "HostDialog_PopulateClassListCombo", 0x556798},
	{"GAME.BIN", "Menu", "CHARCLASS_ENGINEER", "TextResource_GetCharacterClassName", 0x562FEE},
	{"GAME.BIN", "Menu", "CHARCLASS_ENGINEER", "UI_InitWeaponClassSelection", 0x56733E},
	{"GAME.BIN", "Menu", "CHARCLASS_GUNNER", "TextResource_GetCharacterClassName", 0x562FCB},
	{"GAME.BIN", "Menu", "CHARCLASS_GUNNER", "UI_InitWeaponClassSelection", 0x5672ED},
	{"GAME.BIN", "Menu", "CHARCLASS_MEDIC", "TextResource_GetCharacterClassName", 0x562F93},
	{"GAME.BIN", "Menu", "CHARCLASS_MEDIC", "UI_InitWeaponClassSelection", 0x56729B},
	{"GAME.BIN", "Menu", "CHARCLASS_RIFLEMAN", "UI_InitWeaponClassSelection", 0x567315},
	{"GAME.BIN", "Menu", "CHARCLASS_SNIPER", "TextResource_GetCharacterClassName", 0x562FAF},
	{"GAME.BIN", "Menu", "CHARCLASS_SNIPER", "UI_InitWeaponClassSelection", 0x5672C4},
	{"GAME.BIN", "Menu", "CS_NONAME", "PlayerInfo_SaveFromDialog", 0x55F11C},
	{"GAME.BIN", "Menu", "CS_NONAME", "PlayerInfo_InitProfileSelector", 0x5612C5},
	{"GAME.BIN", "Menu", "DEFAULT_SPAWN_KEY", "UI_UpdateDeathScreenContent", 0x553B1F},
	{"GAME.BIN", "Menu", "HOME", "UI_UpdateDeathScreenContent", 0x553B07},
	{"GAME.BIN", "Menu", "NEVER", "HostDialog_PopulateClassListCombo", 0x5567FE},
	{"GAME.BIN", "Menu", "NEVER", "HostDialog_OnWeaponRestrictionListClick", 0x557880},
	{"GAME.BIN", "Menu", "NEVER", "HostDialog_SetAllWeaponRestrictions", 0x557A96},
	{"GAME.BIN", "Menu", "NONE", "PlayerInfo_PopulateWeaponSlotLists", 0x56057C},
	{"GAME.BIN", "Menu", "NONE", "UI_PopulateThreeCategoryLists", 0x566F05},
	{"GAMEERR.BIN", "Generic Error Strings", "STRE_CANTHOST", "UI_ShowSessionErrorMessage", 0x56931F},
	{"GAMEERR.BIN", "Generic Error Strings", "STRE_NOCREATEHOST", "UI_ShowSessionErrorMessage", 0x569342},
	{"GAMEERR.BIN", "Generic Error Strings", "STRE_NOINITPRO", "UI_ShowSessionErrorMessage", 0x5692FB},
	{"GAMEERR.BIN", "Generic Error Strings", "STRE_NOINITPRO", "UI_EnumerateAndJoinSession", 0x56A02B},
	{"GAMEERR.BIN", "Generic Strings", "PRE_CONNECTED", "MultiPlayer_JoinSessionStateMachine", 0x56A90B},
	{"GAMEERR.BIN", "Generic Strings", "PRE_CONNECTING", "MultiPlayer_JoinSessionStateMachine", 0x56A554},
	{"GAMEERR.BIN", "Generic Strings", "PRE_ENUMSESSION", "UI_EnumerateAndJoinSession", 0x56A0AC},
	{"GAMEERR.BIN", "Generic Strings", "PRE_JOININGSESSION", "MultiPlayer_JoinSessionStateMachine", 0x56A4B9},
	{"GAMEERR.BIN", "Generic Strings", "PRE_JOINSESSIONCHOICE", "sub_5691F0", 0x569253},
	{"GAMEERR.BIN", "Generic Strings", "PRE_JOINSESSIONCHOICE", "UI_EnumerateAndJoinSession", 0x56A2BD},
	{"GAMEERR.BIN", "Generic Strings", "PRE_STARTINGSESSION", "MultiPlayer_JoinSessionStateMachine", 0x56A45A},
	{"GAMEERR.BIN", "Generic Strings", "PRE_VERIFYING", "MultiPlayer_JoinSessionStateMachine", 0x56A649},
	{"GAMEERR.BIN", "Generic Strings", "WAITTIMEDISPLAY", "MultiPlayer_JoinSessionStateMachine", 0x56A830},
	{"GAMEERR.BIN", "Generic Strings", "WAITTOJOIN", "MultiPlayer_JoinSessionStateMachine", 0x56A8CB},
	{"GAMEERR.BIN", "Generic Strings", "WAITXXXPEOPLEINFRONT2", "MultiPlayer_JoinSessionStateMachine", 0x56A7DD},
	{"GAMEERR.BIN", "MP Errors", "CVNEEDPW", "UI_EnumerateAndJoinSession", 0x56A258},
	{"GAMEERR.BIN", "MP Errors", "CVSTATCLIENTERR", "UI_EnumerateAndJoinSession", 0x56A145},
	{"GAMEERR.BIN", "MP Errors", "CVUNABLETOCREATE", "UI_JoinSelectedSession", 0x569A89},
	{"GAMEERR.BIN", "MP Errors", "CVUNABLETOCREATE", "UI_EnumerateAndJoinSession", 0x56A1E8},
	{"GAMEERR.BIN", "MP Errors", "CVUNKNOWN3", "UI_ShowSessionErrorMessage", 0x5692D7},
	{"GAMEERR.BIN", "MP Errors", "CVUNKNOWN4", "UI_ShowSessionErrorMessage", 0x569366},
	{"GAMEERR.BIN", "MP Errors", "CVUNKNOWN5", "UI_ShowSessionErrorMessage", 0x56938B},
	{"GAMEERR.BIN", "MP Errors", "CVUNKNOWNJOIN1", "UI_JoinSelectedSession", 0x569DFF},
	{"GAMEERR.BIN", "MP Errors", "ERR5", "CNapiNetwork_GetDisconnectReasonString", 0x4C70F5},
	{"GAMEERR.BIN", "MP Errors", "UNSPECIFIED", "CNapiNetwork_GetDisconnectReasonString", 0x4C7148},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND01", "NetPacket_HandleGameEvent", 0x426493},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND07", "NetPacket_HandleGameEvent", 0x426622},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND12", "NetPacket_HandleGameEvent", 0x42681E},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND14", "NetPacket_HandleGameEvent", 0x42689F},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND15", "NetPacket_HandleGameEvent", 0x426A8B},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND16", "NetPacket_HandleGameEvent", 0x426AC9},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND17", "NetPacket_HandleGameEvent", 0x426C8D},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND18", "NetPacket_HandleGameEvent", 0x426CB6},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND19", "NetPacket_HandleGameEvent", 0x426E2E},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND25", "NetPacket_HandleGameEvent", 0x4268C9},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND26", "NetPacket_HandleGameEvent", 0x4268F3},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND27", "NetPacket_HandleGameEvent", 0x426AFB},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND31", "NetPacket_HandleGameEvent", 0x426F77},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND32", "NetPacket_HandleGameEvent", 0x426FB8},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND33", "NetPacket_HandleGameEvent", 0x426EF5},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND34", "NetPacket_HandleGameEvent", 0x426F36},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND36", "NetPacket_HandleGameEvent", 0x4266B2},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND42", "NetPacket_HandleGameEvent", 0x426426},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND44", "NetPacket_HandleGameEvent", 0x4263FC},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND46", "NetPacket_HandleGameEvent", 0x4263A6},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND47", "NetPacket_HandleGameEvent", 0x427B5A},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND48", "Chat_FormatMessage", 0x422C94},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND49", "NetPacket_HandleGameEvent", 0x42685B},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND50", "NetPacket_HandleGameEvent", 0x426C5E},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_FULLYCAMPED_BLUE", "NetPacket_HandleGameEvent", 0x427319},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_FULLYCAMPED_RED", "NetPacket_HandleGameEvent", 0x42735D},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_BLUETAKEN", "NetPacket_HandleGameEvent", 0x427740},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_BLUEWARNING", "NetPacket_HandleGameEvent", 0x4274F1},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_CAPTUREDEFEND", "NetPacket_HandleGameEvent", 0x427269},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_CAPTURELEVEL", "NetPacket_HandleGameEvent", 0x4271EA},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_LOST", "NetPacket_HandleGameEvent", 0x427069},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_LOSTLEVEL", "NetPacket_HandleGameEvent", 0x427124},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_REDTAKEN", "NetPacket_HandleGameEvent", 0x427894},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_REDWARNING", "NetPacket_HandleGameEvent", 0x427645},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_WON", "NetPacket_HandleGameEvent", 0x4270BF},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_WONLEVEL", "NetPacket_HandleGameEvent", 0x4271B7},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LOSTCAMP_BLUE", "NetPacket_HandleGameEvent", 0x42741E},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LOSTCAMP_RED", "NetPacket_HandleGameEvent", 0x427462},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_PSP_BLUETAKEN", "NetPacket_HandleGameEvent", 0x4277EA},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_PSP_BLUEWARNING", "NetPacket_HandleGameEvent", 0x42759B},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_PSP_REDTAKEN", "NetPacket_HandleGameEvent", 0x42793E},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_PSP_REDWARNING", "NetPacket_HandleGameEvent", 0x4276EF},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_SSKBX", "NetPacket_HandleGameEvent", 0x4279BC},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_YRSSKB1", "NetPacket_HandleGameEvent", 0x427A7F},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_YRSSKBX", "NetPacket_HandleGameEvent", 0x427A12},
	{"GAMETEXT.BIN", "Client", "STRCLI01", "Chat_FormatPlayerMessage", 0x422B67},
	{"GAMETEXT.BIN", "Client", "STRCLI01", "sub_422D00", 0x422D39},
	{"GAMETEXT.BIN", "Client", "STRCLI01", "HUD_FormatKillEventMessage", 0x422DDA},
	{"GAMETEXT.BIN", "client", "strcli01", "HUD_DrawTeamIdLine", 0x59ABDF},
	{"GAMETEXT.BIN", "client", "strcli01", "sub_5B78D0", 0x5B7949},
	{"GAMETEXT.BIN", "Client", "STRCLI02", "Server_OnPlayerJoin", 0x51AA90},
	{"GAMETEXT.BIN", "Client", "STRCLI04", "HUD_DrawGameScoreOverlay", 0x4231E8},
	{"GAMETEXT.BIN", "Client", "STRCLI04", "HUD_DrawScoreOverlay", 0x593EFC},
	{"GAMETEXT.BIN", "Client", "STRCLI05", "HUD_DrawGameScoreOverlay", 0x4232D5},
	{"GAMETEXT.BIN", "client", "strcli05", "HUD_DrawTeamIdLine", 0x59AB23},
	{"GAMETEXT.BIN", "Client", "STRCLI05", "HUD_DrawGameTimerOverlay", 0x59CED0},
	{"GAMETEXT.BIN", "client", "strcli05", "sub_5B78D0", 0x5B78FD},
	{"GAMETEXT.BIN", "Client", "STRCLI06", "HUD_DrawGameScoreOverlay", 0x42331B},
	{"GAMETEXT.BIN", "client", "strcli06", "HUD_DrawTeamIdLine", 0x59AB53},
	{"GAMETEXT.BIN", "Client", "STRCLI06", "HUD_DrawGameTimerOverlay", 0x59CF8B},
	{"GAMETEXT.BIN", "client", "strcli06", "sub_5B78D0", 0x5B7910},
	{"GAMETEXT.BIN", "Client", "STRCLI07", "HUD_DrawGameScoreOverlay", 0x42389C},
	{"GAMETEXT.BIN", "Client", "STRCLI08", "HUD_DrawGameScoreOverlay", 0x4238ED},
	{"GAMETEXT.BIN", "Client", "STRCLI17", "HUD_DrawGameScoreOverlay", 0x423374},
	{"GAMETEXT.BIN", "client", "strcli17", "HUD_DrawTeamIdLine", 0x59AB83},
	{"GAMETEXT.BIN", "client", "strcli17", "sub_5B78D0", 0x5B7923},
	{"GAMETEXT.BIN", "Client", "STRCLI18", "HUD_DrawGameScoreOverlay", 0x4233BA},
	{"GAMETEXT.BIN", "client", "strcli18", "HUD_DrawTeamIdLine", 0x59ABAF},
	{"GAMETEXT.BIN", "client", "strcli18", "sub_5B78D0", 0x5B7936},
	{"GAMETEXT.BIN", "client", "strcli18", "HUD_DrawTeamScoreboard", 0x5BC744},
	{"GAMETEXT.BIN", "client", "strcli19", "HUD_DrawTeamIdLine", 0x59AAED},
	{"GAMETEXT.BIN", "client", "strcli19", "sub_5B78D0", 0x5B78EA},
	{"GAMETEXT.BIN", "client", "strcli21", "HUD_DrawTeamIdLine", 0x59AC96},
	{"GAMETEXT.BIN", "Client", "STRCLI23", "HUD_DrawGameScoreOverlay", 0x423237},
	{"GAMETEXT.BIN", "Client", "STRCLI23", "HUD_DrawScoreOverlay", 0x593F28},
	{"GAMETEXT.BIN", "Client", "STRCLI24", "NapiNPClientMsg_0x032", 0x42815F},
	{"GAMETEXT.BIN", "Client", "STRCLI25", "UI_UpdateDeathScreenContent", 0x553899},
	{"GAMETEXT.BIN", "Client", "STRCLI25", "HUD_DrawScoreOverlay", 0x593ED1},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_ENEMYUNITS", "Cine_ProcessEpilogSequence_Retail", 0x575EEF},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_ENEMYUNITS", "Cine_EpilogStateMachineUpdate", 0x57668F},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_ENEMYUNITS", "HUD_DrawEndRoundStatistics", 0x5B774F},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_FAST_PLAY_BONUS", "Cine_ProcessEpilogSequence_Retail", 0x576091},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_FRIENDLYUNITS", "Cine_ProcessEpilogSequence_Retail", 0x576019},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_FRIENDLYUNITS", "Cine_EpilogStateMachineUpdate", 0x576751},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_FRIENDLYUNITS", "HUD_DrawEndRoundStatistics", 0x5B7859},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_KEYINFO", "Cinematic_EpilogUpdate", 0x574757},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_KEYINFO", "Cine_ProcessEpilogSequence_Retail", 0x5761B3},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_KEYINFO", "Cine_EpilogStateMachineUpdate", 0x5767B9},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_KEYINFO2", "Cinematic_EpilogUpdate", 0x5747B6},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_OBJECTIVEBONUS", "Cine_ProcessEpilogSequence_Retail", 0x575E26},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_OBJECTIVEBONUS", "Cine_EpilogStateMachineUpdate", 0x576604},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_OBJECTIVEBONUS", "HUD_DrawEndRoundStatistics", 0x5B7699},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_TEAMUNITS", "Cine_ProcessEpilogSequence_Retail", 0x575F85},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_TEAMUNITS", "Cine_EpilogStateMachineUpdate", 0x5766F0},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_TEAMUNITS", "HUD_DrawEndRoundStatistics", 0x5B77D6},
	{"GAMETEXT.BIN", "Epilog", "STREPILOG_TOTALPOINTS", "Cine_ProcessEpilogSequence_Retail", 0x57612F},
	{"GAMETEXT.BIN", "GateTypeAbbrev", "AAS", "GameType_GetAbbreviation", 0x52113D},
	{"GAMETEXT.BIN", "GateTypeAbbrev", "AD", "GameType_GetAbbreviation", 0x5210EB},
	{"GAMETEXT.BIN", "GateTypeAbbrev", "CAC", "GameType_GetAbbreviation", 0x52115D},
	{"GAMETEXT.BIN", "GateTypeAbbrev", "CTF", "GameType_GetAbbreviation", 0x5210B3},
	{"GAMETEXT.BIN", "GateTypeAbbrev", "DM", "GameType_GetAbbreviation", 0x521045},
	{"GAMETEXT.BIN", "GateTypeAbbrev", "FB", "GameType_GetAbbreviation", 0x521107},
	{"GAMETEXT.BIN", "GateTypeAbbrev", "FM", "GameType_GetAbbreviation", 0x521121},
	{"GAMETEXT.BIN", "GateTypeAbbrev", "KOTH", "GameType_GetAbbreviation", 0x52107B},
	{"GAMETEXT.BIN", "GateTypeAbbrev", "SD", "GameType_GetAbbreviation", 0x5210CF},
	{"GAMETEXT.BIN", "GateTypeAbbrev", "TDM", "GameType_GetAbbreviation", 0x521061},
	{"GAMETEXT.BIN", "GateTypeAbbrev", "TKOTH", "GameType_GetAbbreviation", 0x521097},
	{"GAMETEXT.BIN", "hud", "altitude", "HUD_DrawAltitudeBar", 0x59F2D4},
	{"GAMETEXT.BIN", "HUD", "HUD_CMAP_GOCODEZULU", "Server_PlayGoCodeSoundAndChat", 0x55248E},
	{"GAMETEXT.BIN", "HUD", "HUD_CMAP_JOIN", "NapiNPClientMsg_HandleSquadJoin", 0x425688},
	{"GAMETEXT.BIN", "HUD", "HUD_CMAP_RECRUIT", "NapiNPClientMsg_PlayerRecruited", 0x425929},
	{"GAMETEXT.BIN", "HUD", "HUD_CMAP_SETFIRETEAM", "NapiNPClientMsg_0x073", 0x425866},
	{"GAMETEXT.BIN", "HUD", "HUD_COM2GUN", "Entity_UpdateTransformAndTurret", 0x441336},
	{"GAMETEXT.BIN", "hud", "hud_farp", "HUD_DrawTrackedTargetDistance", 0x594BFA},
	{"GAMETEXT.BIN", "hud", "Hud_LMLocked", "HUD_DrawLookModeLabel", 0x5941A9},
	{"GAMETEXT.BIN", "hud", "Hud_LookMode", "HUD_DrawLookModeLabel", 0x59411B},
	{"GAMETEXT.BIN", "Hud", "hud_map_legend", "HUD_DrawHelpScreenIcons", 0x49749E},
	{"GAMETEXT.BIN", "hud", "hud_mission", "HUD_DrawGameScoreOverlay", 0x4230DE},
	{"GAMETEXT.BIN", "hud", "hud_scope_mag", "HUD_DrawScopeOverlayDetails", 0x59E9AC},
	{"GAMETEXT.BIN", "hud", "hud_scope_zero", "HUD_DrawScopeOverlayDetails", 0x59E8E5},
	{"GAMETEXT.BIN", "hud", "hud_scope_zero_auto", "HUD_DrawScopeOverlayDetails", 0x59E910},
	{"GAMETEXT.BIN", "hud", "hud_scope_zero_none", "HUD_DrawScopeOverlayDetails", 0x59E92A},
	{"GAMETEXT.BIN", "HUD", "HUD_SPECMODE_1STP", "sub_59AFB0", 0x59B080},
	{"GAMETEXT.BIN", "HUD", "HUD_SPECMODE_CHASE", "sub_59AFB0", 0x59B094},
	{"GAMETEXT.BIN", "HUD", "HUD_SPECMODE_FREE", "sub_59AFB0", 0x59B0A8},
	{"GAMETEXT.BIN", "Hud", "hud_targeting", "sub_593C10", 0x593C53},
	{"GAMETEXT.BIN", "hud", "mto", "HUD_DrawWaypointNameAndDistance", 0x594903},
	{"GAMETEXT.BIN", "hud", "speed", "sub_596650", 0x596740},
	{"GAMETEXT.BIN", "Hud", "TGT_cycle", "sub_593C10", 0x593C3F},
	{"GAMETEXT.BIN", "hud", "tourque", "HUD_DrawTorqueGauge", 0x596318},
	{"GAMETEXT.BIN", "item", "text_default", "HUD_BuildEntityInfo", 0x4B8A54},
	{"GAMETEXT.BIN", "KeyPress", "STRKEYPRESS_ADVANCED", "Input_InitBindingSystem", 0x49A625},
	{"GAMETEXT.BIN", "KeyPress", "STRKEYPRESS_NO", "Input_InitBindingSystem", 0x49A5E4},
	{"GAMETEXT.BIN", "KeyPress", "STRKEYPRESS_RESTART", "Input_InitBindingSystem", 0x49A604},
	{"GAMETEXT.BIN", "KeyPress", "STRKEYPRESS_SAVE", "Input_InitBindingSystem", 0x49A646},
	{"GAMETEXT.BIN", "KeyPress", "STRKEYPRESS_YES", "Input_InitBindingSystem", 0x49A5C0},
	{"GAMETEXT.BIN", "Keys", "Alt-", "KeyBinding_FormatDisplayString", 0x496E51},
	{"GAMETEXT.BIN", "Keys", "Ctrl-", "KeyBinding_FormatDisplayString", 0x496CC5},
	{"GAMETEXT.BIN", "Keys", "Ctrl-", "KeyBinding_FormatBindingString", 0x559AC5},
	{"GAMETEXT.BIN", "Keys", "KEY", "KeyBinding_GetKeyNameAndDisplayName", 0x496261},
	{"GAMETEXT.BIN", "Keys", "LBUTTON", "KeyBinding_FormatDisplayString", 0x497050},
	{"GAMETEXT.BIN", "Keys", "LEFT", "UI_RefreshControlMappingList", 0x55B524},
	{"GAMETEXT.BIN", "Keys", "LEFT", "UI_UpdateControlMappingDisplay", 0x55B874},
	{"GAMETEXT.BIN", "Keys", "LEFT", "UI_PopulateControlMappingList", 0x55C274},
	{"GAMETEXT.BIN", "Keys", "MBUTTON", "KeyBinding_FormatDisplayString", 0x497090},
	{"GAMETEXT.BIN", "Keys", "MIDDLE", "UI_RefreshControlMappingList", 0x55B562},
	{"GAMETEXT.BIN", "Keys", "MIDDLE", "UI_UpdateControlMappingDisplay", 0x55B8AF},
	{"GAMETEXT.BIN", "Keys", "MIDDLE", "UI_PopulateControlMappingList", 0x55C2B2},
	{"GAMETEXT.BIN", "Keys", "MWHLDN", "KeyBinding_FormatDisplayString", 0x4970E2},
	{"GAMETEXT.BIN", "Keys", "MWHLDN", "UI_RefreshControlMappingList", 0x55B5B4},
	{"GAMETEXT.BIN", "Keys", "MWHLDN", "UI_UpdateControlMappingDisplay", 0x55B901},
	{"GAMETEXT.BIN", "Keys", "MWHLDN", "UI_PopulateControlMappingList", 0x55C304},
	{"GAMETEXT.BIN", "Keys", "MWHLUP", "KeyBinding_FormatDisplayString", 0x49711D},
	{"GAMETEXT.BIN", "Keys", "MWHLUP", "UI_RefreshControlMappingList", 0x55B5EF},
	{"GAMETEXT.BIN", "Keys", "MWHLUP", "UI_UpdateControlMappingDisplay", 0x55B93C},
	{"GAMETEXT.BIN", "Keys", "MWHLUP", "UI_PopulateControlMappingList", 0x55C33F},
	{"GAMETEXT.BIN", "Keys", "OR", "KeyBinding_FormatDisplayString", 0x496C5E},
	{"GAMETEXT.BIN", "Keys", "OR", "KeyBinding_FormatBindingString", 0x559A5E},
	{"GAMETEXT.BIN", "Keys", "RBUTTON", "KeyBinding_FormatDisplayString", 0x497014},
	{"GAMETEXT.BIN", "Keys", "RIGHT", "UI_RefreshControlMappingList", 0x55B4E8},
	{"GAMETEXT.BIN", "Keys", "RIGHT", "UI_UpdateControlMappingDisplay", 0x55B83B},
	{"GAMETEXT.BIN", "Keys", "RIGHT", "UI_PopulateControlMappingList", 0x55C238},
	{"GAMETEXT.BIN", "Keys", "Shift-", "KeyBinding_FormatDisplayString", 0x496D10},
	{"GAMETEXT.BIN", "Keys", "Shift-", "KeyBinding_FormatBindingString", 0x559B10},
	{"GAMETEXT.BIN", "LoadingText", "LT_SERVERMSG", "Render_LoadingScreen", 0x522074},
	{"GAMETEXT.BIN", "MENU", "STR_CMAP_FIRETEAMA", "NapiNPClientMsg_0x073", 0x425853},
	{"GAMETEXT.BIN", "Menu", "UNTITLED", "Config_SetDefaults", 0x54D1A1},
	{"GAMETEXT.BIN", "Menu", "USERMESSAGE", "Config_SetDefaults", 0x54D240},
	{"GAMETEXT.BIN", "Misc", "STRMISC_INFAMMO", "Input_HandleActionBinding_0", 0x4E076C},
	{"GAMETEXT.BIN", "Misc", "STRMISC_KILLEDBLUE", "WacAction_Lose", 0x4ED46E},
	{"GAMETEXT.BIN", "Misc", "STRMISC_KILLEDGREEN", "WacAction_Lose", 0x4ED408},
	{"GAMETEXT.BIN", "Misc", "STRMISC_LOCKGAME_OFF", "Input_HandleActionBinding", 0x49BC57},
	{"GAMETEXT.BIN", "Misc", "STRMISC_MOUSESCALE", "Input_HandleActionBinding", 0x49B1EC},
	{"GAMETEXT.BIN", "Misc", "STRMISC_NEWOBJECTIVE", "HUD_ShowObjectiveNotification", 0x5BA3A5},
	{"GAMETEXT.BIN", "Misc", "STRMISC_SCOPESCALE", "Input_HandleActionBinding_0", 0x4E05E0},
	{"GAMETEXT.BIN", "Misc", "STRMISC_TALKBLUE", "Input_HandleActionBinding", 0x49BB0D},
	{"GAMETEXT.BIN", "NovaWorld", "STRNOVA07", "Lobby_UpdateServerInfo", 0x4FEA5A},
	{"GAMETEXT.BIN", "NovaWorld", "STRNOVA08", "Lobby_UpdateServerInfo", 0x4FEA2B},
	{"GAMETEXT.BIN", "NovaWorld", "STRNOVA09", "Lobby_UpdateServerInfo", 0x4FEA02},
	{"GAMETEXT.BIN", "NovaWorld", "STRNOVA10", "Lobby_UpdateServerInfo", 0x4FED94},
	{"GAMETEXT.BIN", "NovaWorld", "STRNOVA11", "Lobby_UpdateServerInfo", 0x4FEBEE},
	{"GAMETEXT.BIN", "NovaWorld", "STRNOVA12", "Lobby_UpdateServerInfo", 0x4FEC1A},
	{"GAMETEXT.BIN", "Overlays", "LFP", "HUD_DrawWaypointNameAndDistance", 0x59499A},
	{"GAMETEXT.BIN", "Overlays", "LFP", "HUD_GetTargetInfoString", 0x5BB4F1},
	{"GAMETEXT.BIN", "Overlays", "METERS", "Overlay_BuildEndGameStatsText", 0x54A840},
	{"GAMETEXT.BIN", "Overlays", "METERS", "HUD_DrawEndGameScreen", 0x5BD763},
	{"GAMETEXT.BIN", "Overlays", "SECONDS", "HUD_DrawEndGameScreen", 0x5BD73D},
	{"GAMETEXT.BIN", "Overlays", "STROVER1", "HUD_DrawEndRoundStatsOverlay", 0x5B7E6A},
	{"GAMETEXT.BIN", "Overlays", "STROVER100", "HUD_DrawEndRoundStatsOverlay", 0x5B83A4},
	{"GAMETEXT.BIN", "Overlays", "STROVER102", "HUD_DrawEndRoundStatsOverlay", 0x5B83C6},
	{"GAMETEXT.BIN", "Overlays", "STROVER105", "HUD_DrawEndRoundStatsOverlay", 0x5B82EC},
	{"GAMETEXT.BIN", "Overlays", "STROVER108", "HUD_DrawEndRoundStatsOverlay", 0x5B8207},
	{"GAMETEXT.BIN", "Overlays", "STROVER110", "HUD_DrawEndRoundStatsOverlay", 0x5B80B1},
	{"GAMETEXT.BIN", "Overlays", "STROVER111", "HUD_DrawEndRoundStatsOverlay", 0x5B80FF},
	{"GAMETEXT.BIN", "Overlays", "STROVER112", "HUD_DrawEndRoundStatsOverlay", 0x5B8017},
	{"GAMETEXT.BIN", "Overlays", "STROVER114", "HUD_DrawEndRoundStatsOverlay", 0x5B803C},
	{"GAMETEXT.BIN", "Overlays", "STROVER115", "HUD_DrawEndRoundStatsOverlay", 0x5B8230},
	{"GAMETEXT.BIN", "Overlays", "STROVER117", "HUD_DrawEndRoundStatsOverlay", 0x5B8315},
	{"GAMETEXT.BIN", "Overlays", "STROVER119", "HUD_DrawEndRoundStatsOverlay", 0x5B812D},
	{"GAMETEXT.BIN", "Overlays", "STROVER120", "HUD_DrawEndRoundStatsOverlay", 0x5B8167},
	{"GAMETEXT.BIN", "Overlays", "STROVER18", "HUD_GetTargetInfoString", 0x5BB441},
	{"GAMETEXT.BIN", "Overlays", "STROVER19", "Game_AssignEntityOverlayNames", 0x523CB7},
	{"GAMETEXT.BIN", "Overlays", "STROVER19", "HUD_GetTargetInfoString", 0x5BB544},
	{"GAMETEXT.BIN", "Overlays", "STROVER2", "HUD_DrawEndRoundStatsOverlay", 0x5B7F8D},
	{"GAMETEXT.BIN", "Overlays", "STROVER20", "Game_AssignEntityOverlayNames", 0x523CE2},
	{"GAMETEXT.BIN", "Overlays", "STROVER20", "HUD_GetTargetInfoString", 0x5BB58E},
	{"GAMETEXT.BIN", "Overlays", "STROVER21", "Game_AssignEntityOverlayNames", 0x523D3D},
	{"GAMETEXT.BIN", "Overlays", "STROVER21", "HUD_GetTargetInfoString", 0x5BB5BC},
	{"GAMETEXT.BIN", "Overlays", "STROVER22", "Game_AssignEntityOverlayNames", 0x523D6D},
	{"GAMETEXT.BIN", "Overlays", "STROVER22", "HUD_GetTargetInfoString", 0x5BB5D6},
	{"GAMETEXT.BIN", "Overlays", "STROVER23", "HUD_GetTargetInfoString", 0x5BB6A4},
	{"GAMETEXT.BIN", "Overlays", "STROVER24", "HUD_GetTargetInfoString", 0x5BB68D},
	{"GAMETEXT.BIN", "Overlays", "STROVER25", "HUD_GetTargetInfoString", 0x5BB676},
	{"GAMETEXT.BIN", "Overlays", "STROVER28", "HUD_GetGameTypeOverlayLabel", 0x5B869E},
	{"GAMETEXT.BIN", "Overlays", "STROVER28", "HUD_DrawGameModeHeader", 0x5B8887},
	{"GAMETEXT.BIN", "Overlays", "STROVER29", "GameType_GetAbbreviation", 0x5211B2},
	{"GAMETEXT.BIN", "Overlays", "STROVER29", "HUD_GetGameTypeOverlayLabel", 0x5B86B5},
	{"GAMETEXT.BIN", "Overlays", "STROVER29", "HUD_DrawGameModeHeader", 0x5B8CF2},
	{"GAMETEXT.BIN", "Overlays", "STROVER30", "GameType_GetAbbreviation", 0x5211E8},
	{"GAMETEXT.BIN", "Overlays", "STROVER30", "HUD_GetGameTypeOverlayLabel", 0x5B86EC},
	{"GAMETEXT.BIN", "Overlays", "STROVER30", "HUD_DrawGameModeHeader", 0x5B896F},
	{"GAMETEXT.BIN", "Overlays", "STROVER31", "GameType_GetAbbreviation", 0x521220},
	{"GAMETEXT.BIN", "Overlays", "STROVER31", "HUD_GetGameTypeOverlayLabel", 0x5B8720},
	{"GAMETEXT.BIN", "Overlays", "STROVER31", "HUD_DrawGameModeHeader", 0x5B8AB4},
	{"GAMETEXT.BIN", "Overlays", "STROVER34", "HUD_DrawEndRoundStatsOverlay", 0x5B7E0F},
	{"GAMETEXT.BIN", "Overlays", "STROVER35", "HUD_DrawEndRoundStatsOverlay", 0x5B7E3A},
	{"GAMETEXT.BIN", "Overlays", "STROVER36", "HUD_DrawObjectiveTextWithScrollList", 0x5BC8D1},
	{"GAMETEXT.BIN", "Overlays", "STROVER43", "HUD_DrawMessageLog", 0x5B9E54},
	{"GAMETEXT.BIN", "Overlays", "STROVER48", "GameType_GetAbbreviation", 0x521204},
	{"GAMETEXT.BIN", "Overlays", "STROVER48", "HUD_GetGameTypeOverlayLabel", 0x5B8706},
	{"GAMETEXT.BIN", "Overlays", "STROVER48", "HUD_DrawGameModeHeader", 0x5B8A1F},
	{"GAMETEXT.BIN", "Overlays", "STROVER5", "UI_DrawDisconnectReasonDialog", 0x5B8F09},
	{"GAMETEXT.BIN", "Overlays", "STROVER50", "UI_UpdateDeathScreenContent", 0x55385D},
	{"GAMETEXT.BIN", "Overlays", "STROVER50", "HUD_DrawGameTimer", 0x593E00},
	{"GAMETEXT.BIN", "Overlays", "STROVER50", "HUD_DrawGameModeHeader", 0x5B8940},
	{"GAMETEXT.BIN", "Overlays", "STROVER53", "HUD_DrawGameTimerOverlay", 0x59CE2D},
	{"GAMETEXT.BIN", "Overlays", "STROVER54", "HUD_DrawPingDisplay", 0x59DA39},
	{"GAMETEXT.BIN", "Overlays", "STROVER55", "HUD_GetTargetInfoString", 0x5BB737},
	{"GAMETEXT.BIN", "Overlays", "STROVER56", "GameType_GetAbbreviation", 0x52123C},
	{"GAMETEXT.BIN", "Overlays", "STROVER56", "HUD_GetGameTypeOverlayLabel", 0x5B873A},
	{"GAMETEXT.BIN", "Overlays", "STROVER56", "HUD_DrawGameModeHeader", 0x5B8B49},
	{"GAMETEXT.BIN", "Overlays", "STROVER57", "GameType_GetAbbreviation", 0x521258},
	{"GAMETEXT.BIN", "Overlays", "STROVER57", "HUD_GetGameTypeOverlayLabel", 0x5B8754},
	{"GAMETEXT.BIN", "Overlays", "STROVER57", "HUD_DrawGameModeHeader", 0x5B8BDD},
	{"GAMETEXT.BIN", "Overlays", "STROVER58", "GameType_GetAbbreviation", 0x521274},
	{"GAMETEXT.BIN", "Overlays", "STROVER58", "HUD_GetGameTypeOverlayLabel", 0x5B876E},
	{"GAMETEXT.BIN", "Overlays", "STROVER58", "HUD_DrawGameModeHeader", 0x5B8C8E},
	{"GAMETEXT.BIN", "Overlays", "STROVER59", "HUD_DrawTimerOverlay", 0x59DBDB},
	{"GAMETEXT.BIN", "Overlays", "STROVER6", "sub_5B9090", 0x5B90CF},
	{"GAMETEXT.BIN", "Overlays", "STROVER60", "Game_AssignEntityOverlayNames", 0x523D0D},
	{"GAMETEXT.BIN", "Overlays", "STROVER60", "HUD_GetTargetInfoString", 0x5BB5A5},
	{"GAMETEXT.BIN", "Overlays", "STROVER62", "HUD_DrawEndRoundStatsOverlay", 0x5B7DA8},
	{"GAMETEXT.BIN", "Overlays", "STROVER63", "HUD_DrawTimerOverlay", 0x59DC45},
	{"GAMETEXT.BIN", "Overlays", "STROVER64", "GameType_GetAbbreviation", 0x5211CE},
	{"GAMETEXT.BIN", "Overlays", "STROVER64", "HUD_GetGameTypeOverlayLabel", 0x5B86D4},
	{"GAMETEXT.BIN", "Overlays", "STROVER64", "HUD_DrawGameModeHeader", 0x5B8906},
	{"GAMETEXT.BIN", "Overlays", "STROVER67", "Game_AssignEntityOverlayNames", 0x523D9D},
	{"GAMETEXT.BIN", "Overlays", "STROVER67", "HUD_GetTargetInfoString", 0x5BB5F0},
	{"GAMETEXT.BIN", "Overlays", "STROVER68", "Game_AssignEntityOverlayNames", 0x523DCD},
	{"GAMETEXT.BIN", "Overlays", "STROVER68", "HUD_GetTargetInfoString", 0x5BB61D},
	{"GAMETEXT.BIN", "Overlays", "STROVER7", "HUD_DrawPausedText", 0x59D687},
	{"GAMETEXT.BIN", "Overlays", "STROVER76", "code at 0x5bb037", 0x5BB037},
	{"GAMETEXT.BIN", "Overlays", "STROVER77", "code at 0x5bb051", 0x5BB051},
	{"GAMETEXT.BIN", "Overlays", "STROVER78", "code at 0x5bb06b", 0x5BB06B},
	{"GAMETEXT.BIN", "Overlays", "STROVER79", "code at 0x5bb085", 0x5BB085},
	{"GAMETEXT.BIN", "Overlays", "STROVER80", "code at 0x5bb0a2", 0x5BB0A2},
	{"GAMETEXT.BIN", "Overlays", "STROVER81", "code at 0x5bb0bc", 0x5BB0BC},
	{"GAMETEXT.BIN", "Overlays", "STROVER82", "code at 0x5bb0d6", 0x5BB0D6},
	{"GAMETEXT.BIN", "Overlays", "STROVER83", "code at 0x5bb0f0", 0x5BB0F0},
	{"GAMETEXT.BIN", "Overlays", "STROVER91", "HUD_DrawBreathBar", 0x59D82C},
	{"GAMETEXT.BIN", "Overlays", "STROVER92", "GameType_GetAbbreviation", 0x521290},
	{"GAMETEXT.BIN", "Overlays", "STROVER92", "HUD_GetGameTypeOverlayLabel", 0x5B8788},
	{"GAMETEXT.BIN", "Overlays", "STROVER93", "GameType_GetAbbreviation", 0x5212AC},
	{"GAMETEXT.BIN", "Overlays", "STROVER93", "HUD_GetGameTypeOverlayLabel", 0x5B87A2},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ARMORY_INFO", "HUD_DrawGameplayOverlays", 0x5BDF37},
	{"GAMETEXT.BIN", "Overlays", "STROVER_BLUETEAM", "HUD_DrawEndRoundStatsOverlay", 0x5B8084},
	{"GAMETEXT.BIN", "Overlays", "STROVER_CALLMEDIC", "UI_UpdateDeathScreenContent", 0x553F41},
	{"GAMETEXT.BIN", "Overlays", "STROVER_CALLMEDIC", "DeathScreen_DrawOverlay", 0x5BEF92},
	{"GAMETEXT.BIN", "Overlays", "STROVER_CONTROL", "HUD_InitOverlaySystem", 0x5A47D3},
	{"GAMETEXT.BIN", "Overlays", "STROVER_DEFENSIVEPOSITION", "HUD_DrawMapOverlay", 0x5A71A0},
	{"GAMETEXT.BIN", "Overlays", "STROVER_DESTROYINGCAMP", "HUD_DrawTakeoverStatus", 0x59BC0C},
	{"GAMETEXT.BIN", "Overlays", "STROVER_DESTROYINGCAMPENEMY", "HUD_DrawTakeoverStatus", 0x59BBE3},
	{"GAMETEXT.BIN", "Overlays", "STROVER_DIST", "HUD_DrawScopeOverlayDetails", 0x59E4F3},
	{"GAMETEXT.BIN", "Overlays", "STROVER_DIST", "HUD_RenderAllOverlays", 0x5A8961},
	{"GAMETEXT.BIN", "Overlays", "STROVER_DIST1KM", "HUD_DrawScopeOverlayDetails", 0x59E4C7},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_BLUEFLAGS", "HUD_FormatEndGameConditionText", 0x5BCF99},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_BLUETGTS", "HUD_FormatEndGameConditionText", 0x5BCF21},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_ENEMYKILLS", "HUD_FormatEndGameConditionText", 0x5BCED1},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_FLAGS", "HUD_FormatEndGameConditionText", 0x5BCF71},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_OBJECTIVES", "HUD_FormatEndGameConditionText", 0x5BD011},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_REDFLAGS", "HUD_FormatEndGameConditionText", 0x5BCFC1},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_REDTGTS", "HUD_FormatEndGameConditionText", 0x5BCF49},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_TIMELIMIT", "HUD_FormatEndGameConditionText", 0x5BCFE9},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_TITLEWIN", "Overlay_BuildEndGameStatsText", 0x54A5F7},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_TITLEWIN", "HUD_DrawEndGameScreen", 0x5BD4F7},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_XP", "HUD_FormatEndGameConditionText", 0x5BCEA9},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_ZONETIME", "HUD_FormatEndGameConditionText", 0x5BCEF9},
	{"GAMETEXT.BIN", "Overlays", "STROVER_FARP_RELOADING", "HUD_DrawGameplayOverlays", 0x5BE0DE},
	{"GAMETEXT.BIN", "Overlays", "STROVER_FARP_WAIT", "HUD_DrawGameplayOverlays", 0x5BE08E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_FLAGCARRIER", "HUD_DrawGameScoreOverlay", 0x423959},
	{"GAMETEXT.BIN", "Overlays", "STROVER_FLAGCARRIER", "HUD_DrawFlagCarrierLabel", 0x594DBB},
	{"GAMETEXT.BIN", "Overlays", "STROVER_GAMETIME", "HUD_DrawEndRoundStatsOverlay", 0x5B8564},
	{"GAMETEXT.BIN", "Overlays", "STROVER_GAMETYPE", "Overlay_BuildEndGameStatsText", 0x54A44D},
	{"GAMETEXT.BIN", "Overlays", "STROVER_GAMETYPE", "HUD_DrawEndGameScreen", 0x5BD33D},
	{"GAMETEXT.BIN", "Overlays", "STROVER_HIGEAR", "HUD_InitOverlaySystem", 0x5A48B7},
	{"GAMETEXT.BIN", "Overlays", "STROVER_HUDEXPPOINTS", "HUD_InitOverlaySystem", 0x5A4837},
	{"GAMETEXT.BIN", "Overlays", "STROVER_HUDSESSIONPTS", "HUD_InitOverlaySystem", 0x5A4853},
	{"GAMETEXT.BIN", "Overlays", "STROVER_HUDTOTALPTS", "HUD_InitOverlaySystem", 0x5A486C},
	{"GAMETEXT.BIN", "Overlays", "STROVER_INITIALSPAWN", "UI_UpdateDeathScreenContent", 0x554192},
	{"GAMETEXT.BIN", "Overlays", "STROVER_KILLLIST", "HUD_DrawKillList", 0x423A75},
	{"GAMETEXT.BIN", "Overlays", "STROVER_LOADGAME", "Game_TryLoadSavedGame", 0x4395EA},
	{"GAMETEXT.BIN", "Overlays", "STROVER_LOADGAMEFAIL", "Game_ShowSaveLoadStatusMessage", 0x43953E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_LOADGAMEFAIL", "Game_TryLoadSavedGame", 0x439632},
	{"GAMETEXT.BIN", "Overlays", "STROVER_LOWGEAR", "HUD_InitOverlaySystem", 0x5A4885},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MAXPLAYERSALLOWED", "Overlay_BuildEndGameStatsText", 0x54A4BE},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MAXPLAYERSALLOWED", "HUD_DrawEndGameScreen", 0x5BD3AE},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MEDGEAR", "HUD_InitOverlaySystem", 0x5A489E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MEDICTIMER", "UI_UpdateDeathScreenContent", 0x553EEF},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MEDICTIMER", "DeathScreen_DrawOverlay", 0x5BEF22},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MISSION_FAILED", "Cinematic_EpilogUpdate", 0x574623},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MISSIONNAME", "Overlay_BuildEndGameStatsText", 0x54A351},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MISSIONNAME", "HUD_DrawEndGameScreen", 0x5BD241},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MISSIONOBJECTIVES", "HUD_DrawWinConditions", 0x5BA986},
	{"GAMETEXT.BIN", "Overlays", "STROVER_NOCAMP", "HUD_DrawTakeoverStatus", 0x59BC63},
	{"GAMETEXT.BIN", "Overlays", "STROVER_NORESPAWN", "UI_UpdateDeathScreenContent", 0x55377E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_NUMPLAYERS", "Overlay_BuildEndGameStatsText", 0x54A52E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_NUMPLAYERS", "HUD_DrawEndGameScreen", 0x5BD41E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_OBJECTIVEPOINT_SHORT", "CMap_OnOpenPopulate", 0x549639},
	{"GAMETEXT.BIN", "Overlays", "STROVER_OBJECTIVEPOINT_SHORT", "HUD_DrawTakeoverStatus", 0x59B6FC},
	{"GAMETEXT.BIN", "Overlays", "STROVER_OBJECTIVEPOINT_SHORT", "Render_CapturePointLabels", 0x5A2984},
	{"GAMETEXT.BIN", "Overlays", "STROVER_OBJECTIVEPOINT_SHORT", "HUD_DrawMapOverlay", 0x5A7102},
	{"GAMETEXT.BIN", "Overlays", "STROVER_OBJECTIVEPOINT_SHORT", "DeathScreen_DrawOverlay", 0x5BF0A7},
	{"GAMETEXT.BIN", "Overlays", "STROVER_PENALTYTIMER", "UI_UpdateDeathScreenContent", 0x553927},
	{"GAMETEXT.BIN", "Overlays", "STROVER_PENALTYTIMER", "DeathScreen_DrawOverlay", 0x5BEE15},
	{"GAMETEXT.BIN", "Overlays", "STROVER_PERMANENTDEATH", "UI_UpdateDeathScreenContent", 0x55373A},
	{"GAMETEXT.BIN", "Overlays", "STROVER_PLAYERWIN", "HUD_DrawEndRoundStatsOverlay", 0x5B7DED},
	{"GAMETEXT.BIN", "Overlays", "STROVER_PSP", "HUD_DrawTakeoverStatus", 0x59B71D},
	{"GAMETEXT.BIN", "Overlays", "STROVER_PSPRESPAWN", "UI_UpdateDeathScreenContent", 0x553E37},
	{"GAMETEXT.BIN", "Overlays", "STROVER_PSPRESPAWN", "DeathScreen_DrawOverlay", 0x5BEE90},
	{"GAMETEXT.BIN", "Overlays", "STROVER_READYFORTAKEOVER", "HUD_DrawZoneStatusPanel", 0x5A261D},
	{"GAMETEXT.BIN", "Overlays", "STROVER_REDTEAM", "UI_UpdateDeathScreenContent", 0x5541DB},
	{"GAMETEXT.BIN", "Overlays", "STROVER_REDTEAM", "HUD_DrawEndRoundStatsOverlay", 0x5B7FE0},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RESPAWN", "DeathScreen_DrawOverlay", 0x5BF171},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RESPAWN1", "UI_UpdateDeathScreenContent", 0x554257},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RESPAWN2", "UI_UpdateDeathScreenContent", 0x55405E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RESPAWN3", "UI_UpdateDeathScreenContent", 0x5542E2},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RESPAWN4", "UI_UpdateDeathScreenContent", 0x5542C0},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RESPAWNBLUEONLY", "DeathScreen_DrawOverlay", 0x5BF3DC},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RESPAWNRED", "DeathScreen_DrawOverlay", 0x5BF48F},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULEPENALTIES", "Overlay_BuildEndGameStatsText", 0x54A8F1},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULEPENALTIES", "HUD_DrawEndGameScreen", 0x5BD8DC},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULEPOINTS", "Overlay_BuildEndGameStatsText", 0x54A6F9},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULEPOINTS", "HUD_DrawEndGameScreen", 0x5BD5E3},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULES_DM", "HUD_BuildRulesAndBriefingText", 0x5B9310},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULES_KOTH", "HUD_BuildRulesAndBriefingText", 0x5B94AB},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULES_PSPGAMES", "HUD_BuildRulesAndBriefingText", 0x5B946C},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SAVEGAME", "Game_SaveAndShowNotification", 0x439412},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SAVEGAME_FNF", "Game_ShowSaveLoadStatusMessage", 0x43956E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SAVEGAMEFAIL", "Game_SaveAndShowNotification", 0x4394D6},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SERVERNAME", "Overlay_BuildEndGameStatsText", 0x54A2E8},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SERVERNAME", "HUD_DrawEndGameScreen", 0x5BD1CC},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SETTINGUPCAMP", "HUD_DrawTakeoverStatus", 0x59BB6D},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SETTINGUPCAMPENEMY", "HUD_DrawTakeoverStatus", 0x59BB41},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SETUPCAMP", "HUD_DrawTakeoverStatus", 0x59BAF4},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SIT", "HUD_InitOverlaySystem", 0x5A47BA},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SLOT", "SaveFile_WriteFullState", 0x4AD168},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SLOTINFO", "sub_5B7370", 0x5B73A2},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SLOTINFO", "sub_5B74B0", 0x5B7543},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SLOTTITLE_LOAD", "sub_5B74B0", 0x5B74E3},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SLOTTITLE_SAVE", "sub_5B74B0", 0x5B74F9},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SPECTATOR_SUFFIX", "CMap_UpdatePlayerListUI", 0x547E95},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SPECTATORSPAWN", "UI_UpdateDeathScreenContent", 0x553763},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SPMISSIONHOWTO", "sub_5B9210", 0x5B9299},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGNEUTRALCAMP", "HUD_DrawTakeoverStatus", 0x59BBA5},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGOVERBLD", "HUD_DrawTakeoverStatus", 0x59B999},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGOVERBLDPSP", "HUD_DrawTakeoverStatus", 0x59B948},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGOVEROBJ", "HUD_DrawTakeoverStatus", 0x59B9D6},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGOVERVEH", "HUD_DrawTakeoverStatus", 0x59B9BA},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGOVERVEHPSP", "HUD_DrawTakeoverStatus", 0x59B96C},
	{"GAMETEXT.BIN", "Overlays", "STROVER_UNDERATTACK", "code at 0x5991ea", 0x5991EA},
	{"GAMETEXT.BIN", "Overlays", "STROVER_UNDERATTACK", "HUD_DrawZoneStatusPanel", 0x5A263C},
	{"GAMETEXT.BIN", "Overlays", "STROVER_UPTIME", "Overlay_BuildEndGameStatsText", 0x54A3D4},
	{"GAMETEXT.BIN", "Overlays", "STROVER_UPTIME", "HUD_DrawEndGameScreen", 0x5BD2C4},
	{"GAMETEXT.BIN", "Overlays", "STROVER_USEARMORY", "HUD_InitOverlaySystem", 0x5A4805},
	{"GAMETEXT.BIN", "Overlays", "STROVER_USEARMORYD", "HUD_InitOverlaySystem", 0x5A481E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_USEGUN", "HUD_InitOverlaySystem", 0x5A47EC},
	{"GAMETEXT.BIN", "Overlays", "STROVER_VEHICLEBAY_INFO", "HUD_DrawGameplayOverlays", 0x5BDFBB},
	{"GAMETEXT.BIN", "Overlays", "STROVER_WAITTOSPAWN", "DeathScreen_DrawOverlay", 0x5BF026},
	{"GAMETEXT.BIN", "Overlays", "STROVER_WELCOMESPAWN", "UI_UpdateDeathScreenContent", 0x554206},
	{"GAMETEXT.BIN", "Overlays", "STROVER_WNDTITLE_DIRECTIVES", "sub_5BA400", 0x5BA489},
	{"GAMETEXT.BIN", "Overlays", "STROVER_WNDTITLE_DIRECTIVES", "HUD_DrawKOTHWinLoseDirectives", 0x5BA6B9},
	{"GAMETEXT.BIN", "Overlays", "STROVR_CONSOLEMESSAGES", "HUD_DrawClassRosterOverlay", 0x5BA015},
	{"GAMETEXT.BIN", "Overlays", "STROVR_ENGINEER", "HUD_DrawTeamScoreboard", 0x5BC7C9},
	{"GAMETEXT.BIN", "Overlays", "STROVR_NO_WRITE", "Game_SaveAndShowNotification", 0x4394B0},
	{"GAMETEXT.BIN", "Overlays", "STROVR_UNKNOWN", "HUD_DrawKillList", 0x423DBE},
	{"GAMETEXT.BIN", "Overlays", "STROVR_UNKNOWN", "CMap_UpdatePlayerListUI", 0x547F18},
	{"GAMETEXT.BIN", "Overlays", "TOPBLUE", "code at 0x5b799d", 0x5B799D},
	{"GAMETEXT.BIN", "Overlays", "TOPNEUTRAL", "code at 0x5b798a", 0x5B798A},
	{"GAMETEXT.BIN", "Overlays", "TOPPLAYERS", "code at 0x5b79e9", 0x5B79E9},
	{"GAMETEXT.BIN", "Overlays", "TOPRED", "code at 0x5b79b0", 0x5B79B0},
	{"GAMETEXT.BIN", "Overlays", "TOPVIOLET", "code at 0x5b79d6", 0x5B79D6},
	{"GAMETEXT.BIN", "Overlays", "TOPYELLOW", "code at 0x5b79c3", 0x5B79C3},
	{"GAMETEXT.BIN", "Score", "SCORE_SAVES_LEFT", "sub_5B74B0", 0x5B750A},
	{"GAMETEXT.BIN", "Score", "SCORE_TITLE", "HUD_DrawEndRoundStatistics", 0x5B7656},
	{"GAMETEXT.BIN", "server", "C2Blue", "NapiNPServerMsg_0x04D_ChangeTeam", 0x51902E},
	{"GAMETEXT.BIN", "server", "C2Red", "NapiNPServerMsg_0x04D_ChangeTeam", 0x51909C},
	{"GAMETEXT.BIN", "Server", "STRSRV01", "Server_DrawStatusScreen", 0x50A3A2},
	{"GAMETEXT.BIN", "Server", "STRSRV02", "Server_DrawStatusScreen", 0x50A817},
	{"GAMETEXT.BIN", "Server", "STRSRV03", "Server_DrawStatusScreen", 0x50A84B},
	{"GAMETEXT.BIN", "Server", "STRSRV04", "Server_DrawStatusScreen", 0x50A8A4},
	{"GAMETEXT.BIN", "Server", "STRSRV05", "Server_DrawStatusScreen", 0x50A8DF},
	{"GAMETEXT.BIN", "Server", "STRSRV06", "Server_DrawStatusScreen", 0x50A92B},
	{"GAMETEXT.BIN", "Server", "STRSRV07", "Server_DrawStatusScreen", 0x50A977},
	{"GAMETEXT.BIN", "Server", "STRSRV08", "Server_DrawStatusScreen", 0x50A9CC},
	{"GAMETEXT.BIN", "Server", "STRSRV10", "Server_DrawStatusScreen", 0x50AFC3},
	{"GAMETEXT.BIN", "Server", "STRSRV11", "Server_DrawStatusScreen", 0x50B0EF},
	{"GAMETEXT.BIN", "Server", "STRSRV16", "code at 0x4fde85", 0x4FDE85},
	{"GAMETEXT.BIN", "Server", "STRSRV17", "Server_DrawStatusScreen", 0x50B038},
	{"GAMETEXT.BIN", "Server", "STRSRV18", "Server_NotifyPlayerKicked", 0x5083C6},
	{"GAMETEXT.BIN", "Server", "STRSRV19", "Server_InitNewRoundState", 0x51C9CD},
	{"GAMETEXT.BIN", "Server", "STRSRV19", "CNapiGameSession_BuildAndCreateSession", 0x5696EE},
	{"GAMETEXT.BIN", "Server", "STRSRV23", "HUD_DrawPlayerScoreList", 0x50032B},
	{"GAMETEXT.BIN", "Server", "STRSRV24", "Server_DrawStatusScreen", 0x50B0A0},
	{"GAMETEXT.BIN", "Server", "STRSRV25", "Server_DrawStatusScreen", 0x50B165},
	{"GAMETEXT.BIN", "Server", "STRSRV_MEDREQ", "Server_BroadcastMedicRequest", 0x5153C4},
	{"GAMETEXT.BIN", "Text", "CAMERA", "KeyBinding_BuildCategoryPages", 0x496812},
	{"GAMETEXT.BIN", "Text", "CHANGE_SCREEN", "HUD_DrawKillList", 0x424281},
	{"GAMETEXT.BIN", "Text", "CHANGE_SCREEN", "HelpScreen_Draw", 0x4978E2},
	{"GAMETEXT.BIN", "Text", "CHANGE_SCREEN", "HUD_DrawEndGameScreen", 0x5BDDD8},
	{"GAMETEXT.BIN", "Text", "CHEAT", "KeyBinding_BuildCategoryPages", 0x496952},
	{"GAMETEXT.BIN", "Text", "COMMUNICATIONS", "KeyBinding_BuildCategoryPages", 0x496892},
	{"GAMETEXT.BIN", "Text", "DEBUG", "KeyBinding_BuildCategoryPages", 0x4969D2},
	{"GAMETEXT.BIN", "Text", "HELPTITLE", "HelpScreen_BuildPage", 0x4971E6},
	{"GAMETEXT.BIN", "Text", "MAP", "KeyBinding_BuildCategoryPages", 0x496852},
	{"GAMETEXT.BIN", "Text", "MOVEMENT", "KeyBinding_BuildCategoryPages", 0x496992},
	{"GAMETEXT.BIN", "Text", "NOVALOGIC", "KeyBinding_BuildCategoryPages", 0x496912},
	{"GAMETEXT.BIN", "Text", "NULL", "KeyBinding_BuildCategoryPages", 0x496757},
	{"GAMETEXT.BIN", "Text", "PAGE", "HelpScreen_BuildPage", 0x49721C},
	{"GAMETEXT.BIN", "Text", "PAGE", "HUD_DrawEndGameScreen", 0x5BDD67},
	{"GAMETEXT.BIN", "Text", "SERVER", "KeyBinding_BuildCategoryPages", 0x4968D2},
	{"GAMETEXT.BIN", "Text", "SPECTATOR", "KeyBinding_BuildCategoryPages", 0x496A4F},
	{"GAMETEXT.BIN", "Text", "SYSTEM", "KeyBinding_BuildCategoryPages", 0x496792},
	{"GAMETEXT.BIN", "Text", "teammatemenu", "KeyBinding_BuildCategoryPages", 0x496A12},
	{"GAMETEXT.BIN", "Text", "UNKNOWN", "KeyBinding_BuildCategoryPages", 0x496A85},
	{"GAMETEXT.BIN", "Text", "WEAPONS", "KeyBinding_BuildCategoryPages", 0x4967D2},
	{"GAMETEXT.BIN", "TimeOfDay", "DAWN", "Lobby_UpdateServerInfo", 0x4FF051},
	{"GAMETEXT.BIN", "TimeOfDay", "DAY", "Lobby_UpdateServerInfo", 0x4FF087},
	{"GAMETEXT.BIN", "TimeOfDay", "DUSK", "Lobby_UpdateServerInfo", 0x4FF0BD},
	{"GAMETEXT.BIN", "TimeOfDay", "NIGHT", "Lobby_UpdateServerInfo", 0x4FF0F4},
	{"GAMETEXT.BIN", "TimeOfDay", "UNKNOWN", "Lobby_UpdateServerInfo", 0x4FF122},
	{"GAMETEXT.BIN", "Tips", "GP_DESIGNATOR_HELPMORTAR", "CTipSystem_Draw", 0x5B6E7C},
	{"GAMETEXT.BIN", "Tips", "StrGPTip", "CTipSystem_Draw", 0x5B6DEF},
	{"GAMETEXT.BIN", "Vidtest", "CARD_NOT_QUALIFIED", "VideoTest_TriggerSelectionDialogProc", 0x53E226},
	{"GAMETEXT.BIN", "Vidtest", "CHOOSE_CARD", "VideoTest_TriggerSelectionDialogProc", 0x53E2CB},
	{"GAMETEXT.BIN", "Vidtest", "Detected", "code at 0x53ea01", 0x53EA01},
	{"GAMETEXT.BIN", "Vidtest", "ERROR", "VideoTest_TriggerSelectionDialogProc", 0x53E213},
	{"GAMETEXT.BIN", "Vidtest", "FAIL", "Game_RunVideoTestDialog", 0x53EC41},
	{"GAMETEXT.BIN", "Vidtest", "GHWINIT_ERR_D3DVERSION", "sub_586350", 0x5863A9},
	{"GAMETEXT.BIN", "Vidtest", "HAS_SHADERS", "VideoTest_BuildTriggerPropertyDescription", 0x53E0A8},
	{"GAMETEXT.BIN", "Vidtest", "High", "code at 0x53e6f0", 0x53E6F0},
	{"GAMETEXT.BIN", "Vidtest", "High", "code at 0x53e770", 0x53E770},
	{"GAMETEXT.BIN", "Vidtest", "High", "code at 0x53e7f0", 0x53E7F0},
	{"GAMETEXT.BIN", "Vidtest", "High", "code at 0x53e870", 0x53E870},
	{"GAMETEXT.BIN", "Vidtest", "High", "code at 0x53e8e0", 0x53E8E0},
	{"GAMETEXT.BIN", "Vidtest", "High", "code at 0x53e963", 0x53E963},
	{"GAMETEXT.BIN", "Vidtest", "High", "code at 0x53e9c0", 0x53E9C0},
	{"GAMETEXT.BIN", "Vidtest", "Highest", "code at 0x53e703", 0x53E703},
	{"GAMETEXT.BIN", "Vidtest", "Highest", "code at 0x53e783", 0x53E783},
	{"GAMETEXT.BIN", "Vidtest", "Highest", "code at 0x53e803", 0x53E803},
	{"GAMETEXT.BIN", "Vidtest", "Highest", "code at 0x53e883", 0x53E883},
	{"GAMETEXT.BIN", "Vidtest", "INFORMATION", "VideoTest_TriggerSelectionDialogProc", 0x53E307},
	{"GAMETEXT.BIN", "Vidtest", "INIT3DHWDEVICELIST", "VideoAdapter_EnumerateAll", 0x53EBCC},
	{"GAMETEXT.BIN", "Vidtest", "INIT3DHWDEVICELIST", "sub_586350", 0x586386},
	{"GAMETEXT.BIN", "Vidtest", "Low", "code at 0x53e6ca", 0x53E6CA},
	{"GAMETEXT.BIN", "Vidtest", "Low", "code at 0x53e74a", 0x53E74A},
	{"GAMETEXT.BIN", "Vidtest", "Low", "code at 0x53e7ca", 0x53E7CA},
	{"GAMETEXT.BIN", "Vidtest", "Low", "code at 0x53e84a", 0x53E84A},
	{"GAMETEXT.BIN", "Vidtest", "Low", "code at 0x53e906", 0x53E906},
	{"GAMETEXT.BIN", "Vidtest", "Low", "code at 0x53e93d", 0x53E93D},
	{"GAMETEXT.BIN", "Vidtest", "Low", "code at 0x53e9e6", 0x53E9E6},
	{"GAMETEXT.BIN", "Vidtest", "MEETS_REQUIREMENTS", "VideoTest_BuildTriggerPropertyDescription", 0x53E0EA},
	{"GAMETEXT.BIN", "Vidtest", "NO_3DCARDS", "VideoAdapter_EnumerateAll", 0x53EBDF},
	{"GAMETEXT.BIN", "Vidtest", "NO_DIRECTX9", "VideoTest_BuildTriggerPropertyDescription", 0x53DFB7},
	{"GAMETEXT.BIN", "Vidtest", "NO_MULTITEXTURES", "VideoTest_BuildTriggerPropertyDescription", 0x53DF6E},
	{"GAMETEXT.BIN", "Vidtest", "NO_TNL", "VideoTest_BuildTriggerPropertyDescription", 0x53DF1E},
	{"GAMETEXT.BIN", "Vidtest", "NO_WHQL", "VideoTest_BuildTriggerPropertyDescription", 0x53E050},
	{"GAMETEXT.BIN", "Vidtest", "Normal", "code at 0x53e6dd", 0x53E6DD},
	{"GAMETEXT.BIN", "Vidtest", "Normal", "code at 0x53e75d", 0x53E75D},
	{"GAMETEXT.BIN", "Vidtest", "Normal", "code at 0x53e7dd", 0x53E7DD},
	{"GAMETEXT.BIN", "Vidtest", "Normal", "code at 0x53e85d", 0x53E85D},
	{"GAMETEXT.BIN", "Vidtest", "Normal", "code at 0x53e8f3", 0x53E8F3},
	{"GAMETEXT.BIN", "Vidtest", "Normal", "code at 0x53e950", 0x53E950},
	{"GAMETEXT.BIN", "Vidtest", "Normal", "code at 0x53e9d3", 0x53E9D3},
	{"GAMETEXT.BIN", "Vidtest", "Not_Detected", "code at 0x53ea14", 0x53EA14},
	{"GAMETEXT.BIN", "Vidtest", "NOTHING_SUITABLE", "VideoTest_TriggerSelectionDialogProc", 0x53E3D2},
	{"GAMETEXT.BIN", "Vidtest", "Off", "code at 0x53e92a", 0x53E92A},
	{"GAMETEXT.BIN", "Vidtest", "PASS", "Game_RunVideoTestDialog", 0x53EC32},
	{"GAMETEXT.BIN", "Vidtest", "RECOMMENDATION", "VideoTest_TriggerSelectionDialogProc", 0x53E46D},
	{"GAMETEXT.BIN", "Vidtest", "RUNNING_WIN2K", "VideoTest_BuildTriggerPropertyDescription", 0x53E001},
	{"GAMETEXT.BIN", "Vidtest", "SELECT_DEVICE", "VideoTest_TriggerSelectionDialogProc", 0x53E2AD},
	{"GAMETEXT.BIN", "Vidtest", "Unknown", "code at 0x53e661", 0x53E661},
	{"GAMETEXT.BIN", "Vidtest", "Unknown", "code at 0x53e716", 0x53E716},
	{"GAMETEXT.BIN", "Vidtest", "Unknown", "code at 0x53e796", 0x53E796},
	{"GAMETEXT.BIN", "Vidtest", "Unknown", "code at 0x53e816", 0x53E816},
	{"GAMETEXT.BIN", "Vidtest", "Unknown", "code at 0x53e896", 0x53E896},
	{"GAMETEXT.BIN", "Vidtest", "Unknown", "code at 0x53e8cd", 0x53E8CD},
	{"GAMETEXT.BIN", "Vidtest", "Unknown", "code at 0x53e976", 0x53E976},
	{"GAMETEXT.BIN", "Vidtest", "Unknown", "code at 0x53e9ad", 0x53E9AD},
	{"GAMETEXT.BIN", "Vidtest", "VIDEO_CARD_LIST", "VideoTest_TriggerSelectionDialogProc", 0x53E2EC},
	{"GAMETEXT.BIN", "WPNames", "STRWPNAMEDEFAULT", "HUD_GetWaypointName", 0x59477B},
};

} // namespace

const std::vector<CodeTextKey> &code_text_keys() {
	static const std::vector<CodeTextKey> rows(std::begin(kRows), std::end(kRows));
	return rows;
}

std::vector<const CodeTextKey *> code_reads_of(const AssetGraph &graph, const GraphSymbol &symbol) {
	std::vector<const CodeTextKey *> out;
	if (symbol.kind != ReferenceKind::TextId) return out;
	const std::string name = strutil::to_upper(symbol.name);
	for (const CodeTextKey &row : code_text_keys()) {
		if (strutil::to_upper(row.key) != name) continue;
		const std::string scope = std::string(row.table) + "/" + row.section;
		if (graph.resolve_symbol(ReferenceKind::TextId, row.key, scope) == &symbol) out.push_back(&row);
	}
	return out;
}

} // namespace opennova::editor
