#include <editor/graph/code_text_keys.h>

#include <base/io/strutil.h>
#include <editor/graph/asset_graph.h>

namespace opennova::editor {

namespace {

// Generated from the binary's calls (each row a function's first call of the pair, its address).
const CodeTextKey kRows[] = {
	{"GAMEERR.BIN", "MP Errors", "ERR5", "CNapiNetwork_GetDisconnectReasonString", 0x4C70F5},
	{"GAMEERR.BIN", "MP Errors", "UNSPECIFIED", "CNapiNetwork_GetDisconnectReasonString", 0x4C7148},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND01", "NetPacket_HandleGameEvent", 0x426493},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND07", "NetPacket_HandleGameEvent", 0x426622},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND12", "NetPacket_HandleGameEvent", 0x42681E},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND14", "NetPacket_HandleGameEvent", 0x42689F},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND15", "NetPacket_HandleGameEvent", 0x426A8B},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND16", "NetPacket_HandleGameEvent", 0x426AC9},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND17", "NetPacket_HandleGameEvent", 0x426C8D},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND18", "NetPacket_HandleGameEvent", 0x426CB6},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND19", "NetPacket_HandleGameEvent", 0x426E2E},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND25", "NetPacket_HandleGameEvent", 0x4268C9},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND26", "NetPacket_HandleGameEvent", 0x4268F3},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND27", "NetPacket_HandleGameEvent", 0x426AFB},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND31", "NetPacket_HandleGameEvent", 0x426F77},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND32", "NetPacket_HandleGameEvent", 0x426FB8},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND33", "NetPacket_HandleGameEvent", 0x426EF5},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND34", "NetPacket_HandleGameEvent", 0x426F36},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND36", "NetPacket_HandleGameEvent", 0x4266B2},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND42", "NetPacket_HandleGameEvent", 0x426426},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND44", "NetPacket_HandleGameEvent", 0x4263FC},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND46", "NetPacket_HandleGameEvent", 0x4263A6},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND47", "NetPacket_HandleGameEvent", 0x427B5A},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND48", "Chat_FormatMessage", 0x422C94},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND49", "NetPacket_HandleGameEvent", 0x42685B},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND50", "NetPacket_HandleGameEvent", 0x426C5E},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_FULLYCAMPED_BLUE", "NetPacket_HandleGameEvent", 0x427319},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_FULLYCAMPED_RED", "NetPacket_HandleGameEvent", 0x42735D},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_BLUETAKEN", "NetPacket_HandleGameEvent", 0x427740},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_BLUEWARNING", "NetPacket_HandleGameEvent", 0x4274F1},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_CAPTUREDEFEND", "NetPacket_HandleGameEvent", 0x427269},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_CAPTURELEVEL", "NetPacket_HandleGameEvent", 0x4271EA},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_LOST", "NetPacket_HandleGameEvent", 0x427069},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_LOSTLEVEL", "NetPacket_HandleGameEvent", 0x427124},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_REDTAKEN", "NetPacket_HandleGameEvent", 0x427894},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_REDWARNING", "NetPacket_HandleGameEvent", 0x427645},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_WON", "NetPacket_HandleGameEvent", 0x4270BF},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LFP_WONLEVEL", "NetPacket_HandleGameEvent", 0x4271B7},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LOSTCAMP_BLUE", "NetPacket_HandleGameEvent", 0x42741E},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_LOSTCAMP_RED", "NetPacket_HandleGameEvent", 0x427462},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_PSP_BLUETAKEN", "NetPacket_HandleGameEvent", 0x4277EA},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_PSP_BLUEWARNING", "NetPacket_HandleGameEvent", 0x42759B},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_PSP_REDTAKEN", "NetPacket_HandleGameEvent", 0x42793E},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_PSP_REDWARNING", "NetPacket_HandleGameEvent", 0x4276EF},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_SSKBX", "NetPacket_HandleGameEvent", 0x4279BC},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_YRSSKB1", "NetPacket_HandleGameEvent", 0x427A7F},
	{"GAMETEXT.BIN", "Canned Msg", "STRCND_YRSSKBX", "NetPacket_HandleGameEvent", 0x427A12},
	{"GAMETEXT.BIN", "Client", "STRCLI01", "Chat_FormatPlayerMessage", 0x422B67},
	{"GAMETEXT.BIN", "Client", "STRCLI01", "sub_422D00", 0x422D39},
	{"GAMETEXT.BIN", "Client", "STRCLI01", "HUD_FormatKillEventMessage", 0x422DDA},
	{"GAMETEXT.BIN", "Client", "STRCLI04", "HUD_DrawGameScoreOverlay", 0x4231E8},
	{"GAMETEXT.BIN", "Client", "STRCLI05", "HUD_DrawGameScoreOverlay", 0x4232D5},
	{"GAMETEXT.BIN", "Client", "STRCLI06", "HUD_DrawGameScoreOverlay", 0x42331B},
	{"GAMETEXT.BIN", "Client", "STRCLI07", "HUD_DrawGameScoreOverlay", 0x42389C},
	{"GAMETEXT.BIN", "Client", "STRCLI08", "HUD_DrawGameScoreOverlay", 0x4238ED},
	{"GAMETEXT.BIN", "Client", "STRCLI17", "HUD_DrawGameScoreOverlay", 0x423374},
	{"GAMETEXT.BIN", "Client", "STRCLI18", "HUD_DrawGameScoreOverlay", 0x4233BA},
	{"GAMETEXT.BIN", "Client", "STRCLI23", "HUD_DrawGameScoreOverlay", 0x423237},
	{"GAMETEXT.BIN", "Client", "STRCLI24", "NapiNPClientMsg_0x032", 0x42815F},
	{"GAMETEXT.BIN", "HUD", "HUD_CMAP_JOIN", "NapiNPClientMsg_HandleSquadJoin", 0x425688},
	{"GAMETEXT.BIN", "HUD", "HUD_CMAP_RECRUIT", "NapiNPClientMsg_PlayerRecruited", 0x425929},
	{"GAMETEXT.BIN", "HUD", "HUD_CMAP_SETFIRETEAM", "NapiNPClientMsg_0x073", 0x425866},
	{"GAMETEXT.BIN", "hud", "hud_mission", "HUD_DrawGameScoreOverlay", 0x4230DE},
	{"GAMETEXT.BIN", "Keys", "Alt-", "KeyBinding_FormatDisplayString", 0x496E51},
	{"GAMETEXT.BIN", "Keys", "Ctrl-", "KeyBinding_FormatDisplayString", 0x496CC5},
	{"GAMETEXT.BIN", "Keys", "Ctrl-", "KeyBinding_FormatBindingString", 0x559AC5},
	{"GAMETEXT.BIN", "Keys", "KEY", "KeyBinding_GetKeyNameAndDisplayName", 0x496261},
	{"GAMETEXT.BIN", "Keys", "LBUTTON", "KeyBinding_FormatDisplayString", 0x497050},
	{"GAMETEXT.BIN", "Keys", "LEFT", "UI_RefreshControlMappingList", 0x55B524},
	{"GAMETEXT.BIN", "Keys", "LEFT", "UI_UpdateControlMappingDisplay", 0x55B874},
	{"GAMETEXT.BIN", "Keys", "LEFT", "UI_PopulateControlMappingList", 0x55C274},
	{"GAMETEXT.BIN", "Keys", "MBUTTON", "KeyBinding_FormatDisplayString", 0x497090},
	{"GAMETEXT.BIN", "Keys", "MIDDLE", "UI_RefreshControlMappingList", 0x55B562},
	{"GAMETEXT.BIN", "Keys", "MIDDLE", "UI_UpdateControlMappingDisplay", 0x55B8AF},
	{"GAMETEXT.BIN", "Keys", "MIDDLE", "UI_PopulateControlMappingList", 0x55C2B2},
	{"GAMETEXT.BIN", "Keys", "MWHLDN", "KeyBinding_FormatDisplayString", 0x4970E2},
	{"GAMETEXT.BIN", "Keys", "MWHLDN", "UI_RefreshControlMappingList", 0x55B5B4},
	{"GAMETEXT.BIN", "Keys", "MWHLDN", "UI_UpdateControlMappingDisplay", 0x55B901},
	{"GAMETEXT.BIN", "Keys", "MWHLDN", "UI_PopulateControlMappingList", 0x55C304},
	{"GAMETEXT.BIN", "Keys", "MWHLUP", "KeyBinding_FormatDisplayString", 0x49711D},
	{"GAMETEXT.BIN", "Keys", "MWHLUP", "UI_RefreshControlMappingList", 0x55B5EF},
	{"GAMETEXT.BIN", "Keys", "MWHLUP", "UI_UpdateControlMappingDisplay", 0x55B93C},
	{"GAMETEXT.BIN", "Keys", "MWHLUP", "UI_PopulateControlMappingList", 0x55C33F},
	{"GAMETEXT.BIN", "Keys", "OR", "KeyBinding_FormatDisplayString", 0x496C5E},
	{"GAMETEXT.BIN", "Keys", "OR", "KeyBinding_FormatBindingString", 0x559A5E},
	{"GAMETEXT.BIN", "Keys", "RBUTTON", "KeyBinding_FormatDisplayString", 0x497014},
	{"GAMETEXT.BIN", "Keys", "RIGHT", "UI_RefreshControlMappingList", 0x55B4E8},
	{"GAMETEXT.BIN", "Keys", "RIGHT", "UI_UpdateControlMappingDisplay", 0x55B83B},
	{"GAMETEXT.BIN", "Keys", "RIGHT", "UI_PopulateControlMappingList", 0x55C238},
	{"GAMETEXT.BIN", "Keys", "Shift-", "KeyBinding_FormatDisplayString", 0x496D10},
	{"GAMETEXT.BIN", "Keys", "Shift-", "KeyBinding_FormatBindingString", 0x559B10},
	{"GAMETEXT.BIN", "LoadingText", "LT_SERVERMSG", "Render_LoadingScreen", 0x522074},
	{"GAMETEXT.BIN", "MENU", "STR_CMAP_FIRETEAMA", "NapiNPClientMsg_0x073", 0x425853},
	{"GAMETEXT.BIN", "Overlays", "METERS", "Overlay_BuildEndGameStatsText", 0x54A840},
	{"GAMETEXT.BIN", "Overlays", "STROVER1", "HUD_DrawEndRoundStatsOverlay", 0x5B7E6A},
	{"GAMETEXT.BIN", "Overlays", "STROVER_BLUETEAM", "HUD_DrawEndRoundStatsOverlay", 0x5B8431},
	{"GAMETEXT.BIN", "Overlays", "STROVER_CONTROL", "HUD_InitOverlaySystem", 0x5A47D3},
	{"GAMETEXT.BIN", "Overlays", "STROVER_DESTROYINGCAMP", "HUD_DrawTakeoverStatus", 0x59BC0C},
	{"GAMETEXT.BIN", "Overlays", "STROVER_DESTROYINGCAMPENEMY", "HUD_DrawTakeoverStatus", 0x59BBE3},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_BLUEFLAGS", "HUD_FormatEndGameConditionText", 0x5BCF99},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_BLUETGTS", "HUD_FormatEndGameConditionText", 0x5BCF21},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_ENEMYKILLS", "HUD_FormatEndGameConditionText", 0x5BCED1},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_FLAGS", "HUD_FormatEndGameConditionText", 0x5BCF71},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_OBJECTIVES", "HUD_FormatEndGameConditionText", 0x5BD011},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_REDFLAGS", "HUD_FormatEndGameConditionText", 0x5BCFC1},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_REDTGTS", "HUD_FormatEndGameConditionText", 0x5BCF49},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_TIMELIMIT", "HUD_FormatEndGameConditionText", 0x5BCFE9},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_TITLEWIN", "Overlay_BuildEndGameStatsText", 0x54A5F7},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_XP", "HUD_FormatEndGameConditionText", 0x5BCEA9},
	{"GAMETEXT.BIN", "Overlays", "STROVER_ENDGAMECOND_ZONETIME", "HUD_FormatEndGameConditionText", 0x5BCEF9},
	{"GAMETEXT.BIN", "Overlays", "STROVER_FLAGCARRIER", "HUD_DrawGameScoreOverlay", 0x423959},
	{"GAMETEXT.BIN", "Overlays", "STROVER_FLAGCARRIER", "HUD_DrawFlagCarrierLabel", 0x594DBB},
	{"GAMETEXT.BIN", "Overlays", "STROVER_GAMETIME", "HUD_DrawEndRoundStatsOverlay", 0x5B8564},
	{"GAMETEXT.BIN", "Overlays", "STROVER_GAMETYPE", "Overlay_BuildEndGameStatsText", 0x54A44D},
	{"GAMETEXT.BIN", "Overlays", "STROVER_GAMETYPE", "HUD_DrawEndGameScreen", 0x5BD33D},
	{"GAMETEXT.BIN", "Overlays", "STROVER_HIGEAR", "HUD_InitOverlaySystem", 0x5A48B7},
	{"GAMETEXT.BIN", "Overlays", "STROVER_HUDEXPPOINTS", "HUD_InitOverlaySystem", 0x5A4837},
	{"GAMETEXT.BIN", "Overlays", "STROVER_HUDSESSIONPTS", "HUD_InitOverlaySystem", 0x5A4853},
	{"GAMETEXT.BIN", "Overlays", "STROVER_HUDTOTALPTS", "HUD_InitOverlaySystem", 0x5A486C},
	{"GAMETEXT.BIN", "Overlays", "STROVER_KILLLIST", "HUD_DrawKillList", 0x423A75},
	{"GAMETEXT.BIN", "Overlays", "STROVER_LOADGAME", "Game_TryLoadSavedGame", 0x4395EA},
	{"GAMETEXT.BIN", "Overlays", "STROVER_LOADGAMEFAIL", "Game_ShowSaveLoadStatusMessage", 0x43953E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_LOADGAMEFAIL", "Game_TryLoadSavedGame", 0x439632},
	{"GAMETEXT.BIN", "Overlays", "STROVER_LOWGEAR", "HUD_InitOverlaySystem", 0x5A4885},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MAXPLAYERSALLOWED", "Overlay_BuildEndGameStatsText", 0x54A4BE},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MAXPLAYERSALLOWED", "HUD_DrawEndGameScreen", 0x5BD3AE},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MEDGEAR", "HUD_InitOverlaySystem", 0x5A489E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MISSIONNAME", "Overlay_BuildEndGameStatsText", 0x54A351},
	{"GAMETEXT.BIN", "Overlays", "STROVER_MISSIONNAME", "HUD_DrawEndGameScreen", 0x5BD241},
	{"GAMETEXT.BIN", "Overlays", "STROVER_NOCAMP", "HUD_DrawTakeoverStatus", 0x59BC63},
	{"GAMETEXT.BIN", "Overlays", "STROVER_NUMPLAYERS", "Overlay_BuildEndGameStatsText", 0x54A52E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_READYFORTAKEOVER", "HUD_DrawZoneStatusPanel", 0x5A261D},
	{"GAMETEXT.BIN", "Overlays", "STROVER_REDTEAM", "UI_UpdateDeathScreenContent", 0x5541DB},
	{"GAMETEXT.BIN", "Overlays", "STROVER_REDTEAM", "HUD_DrawEndRoundStatsOverlay", 0x5B8477},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULEPENALTIES", "Overlay_BuildEndGameStatsText", 0x54A8F1},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULEPOINTS", "Overlay_BuildEndGameStatsText", 0x54A6F9},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULES_DM", "HUD_BuildRulesAndBriefingText", 0x5B9310},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULES_KOTH", "HUD_BuildRulesAndBriefingText", 0x5B94AB},
	{"GAMETEXT.BIN", "Overlays", "STROVER_RULES_PSPGAMES", "HUD_BuildRulesAndBriefingText", 0x5B946C},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SAVEGAME", "Game_SaveAndShowNotification", 0x439412},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SAVEGAME_FNF", "Game_ShowSaveLoadStatusMessage", 0x43956E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SAVEGAMEFAIL", "Game_SaveAndShowNotification", 0x4394D6},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SERVERNAME", "Overlay_BuildEndGameStatsText", 0x54A2E8},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SERVERNAME", "HUD_DrawEndGameScreen", 0x5BD1CC},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SETTINGUPCAMP", "HUD_DrawTakeoverStatus", 0x59BB6D},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SETTINGUPCAMPENEMY", "HUD_DrawTakeoverStatus", 0x59BB41},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SETUPCAMP", "HUD_DrawTakeoverStatus", 0x59BAF4},
	{"GAMETEXT.BIN", "Overlays", "STROVER_SIT", "HUD_InitOverlaySystem", 0x5A47BA},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGNEUTRALCAMP", "HUD_DrawTakeoverStatus", 0x59BBA5},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGOVERBLD", "HUD_DrawTakeoverStatus", 0x59B999},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGOVERBLDPSP", "HUD_DrawTakeoverStatus", 0x59B948},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGOVEROBJ", "HUD_DrawTakeoverStatus", 0x59B9D6},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGOVERVEH", "HUD_DrawTakeoverStatus", 0x59B9BA},
	{"GAMETEXT.BIN", "Overlays", "STROVER_TAKINGOVERVEHPSP", "HUD_DrawTakeoverStatus", 0x59B96C},
	{"GAMETEXT.BIN", "Overlays", "STROVER_UNDERATTACK", "HUD_DrawZoneStatusPanel", 0x5A263C},
	{"GAMETEXT.BIN", "Overlays", "STROVER_UPTIME", "Overlay_BuildEndGameStatsText", 0x54A3D4},
	{"GAMETEXT.BIN", "Overlays", "STROVER_UPTIME", "HUD_DrawEndGameScreen", 0x5BD2C4},
	{"GAMETEXT.BIN", "Overlays", "STROVER_USEARMORY", "HUD_InitOverlaySystem", 0x5A4805},
	{"GAMETEXT.BIN", "Overlays", "STROVER_USEARMORYD", "HUD_InitOverlaySystem", 0x5A481E},
	{"GAMETEXT.BIN", "Overlays", "STROVER_USEGUN", "HUD_InitOverlaySystem", 0x5A47EC},
	{"GAMETEXT.BIN", "Overlays", "STROVR_NO_WRITE", "Game_SaveAndShowNotification", 0x4394B0},
	{"GAMETEXT.BIN", "Overlays", "STROVR_UNKNOWN", "HUD_DrawKillList", 0x423DBE},
	{"GAMETEXT.BIN", "Text", "CAMERA", "KeyBinding_BuildCategoryPages", 0x496812},
	{"GAMETEXT.BIN", "Text", "CHANGE_SCREEN", "HUD_DrawKillList", 0x424281},
	{"GAMETEXT.BIN", "Text", "CHANGE_SCREEN", "HelpScreen_Draw", 0x4978E2},
	{"GAMETEXT.BIN", "Text", "CHANGE_SCREEN", "HUD_DrawEndGameScreen", 0x5BDDD8},
	{"GAMETEXT.BIN", "Text", "CHEAT", "KeyBinding_BuildCategoryPages", 0x496952},
	{"GAMETEXT.BIN", "Text", "COMMUNICATIONS", "KeyBinding_BuildCategoryPages", 0x496892},
	{"GAMETEXT.BIN", "Text", "DEBUG", "KeyBinding_BuildCategoryPages", 0x4969D2},
	{"GAMETEXT.BIN", "Text", "HELPTITLE", "HelpScreen_BuildPage", 0x4971E6},
	{"GAMETEXT.BIN", "Text", "MAP", "KeyBinding_BuildCategoryPages", 0x496852},
	{"GAMETEXT.BIN", "Text", "MOVEMENT", "KeyBinding_BuildCategoryPages", 0x496992},
	{"GAMETEXT.BIN", "Text", "NOVALOGIC", "KeyBinding_BuildCategoryPages", 0x496912},
	{"GAMETEXT.BIN", "Text", "NULL", "KeyBinding_BuildCategoryPages", 0x496757},
	{"GAMETEXT.BIN", "Text", "PAGE", "HelpScreen_BuildPage", 0x49721C},
	{"GAMETEXT.BIN", "Text", "PAGE", "HUD_DrawEndGameScreen", 0x5BDD67},
	{"GAMETEXT.BIN", "Text", "SERVER", "KeyBinding_BuildCategoryPages", 0x4968D2},
	{"GAMETEXT.BIN", "Text", "SPECTATOR", "KeyBinding_BuildCategoryPages", 0x496A4F},
	{"GAMETEXT.BIN", "Text", "SYSTEM", "KeyBinding_BuildCategoryPages", 0x496792},
	{"GAMETEXT.BIN", "Text", "teammatemenu", "KeyBinding_BuildCategoryPages", 0x496A12},
	{"GAMETEXT.BIN", "Text", "UNKNOWN", "KeyBinding_BuildCategoryPages", 0x496A85},
	{"GAMETEXT.BIN", "Text", "WEAPONS", "KeyBinding_BuildCategoryPages", 0x4967D2},
	{"GAMETEXT.BIN", "TimeOfDay", "DAWN", "Lobby_UpdateServerInfo", 0x4FF051},
	{"GAMETEXT.BIN", "TimeOfDay", "DAY", "Lobby_UpdateServerInfo", 0x4FF087},
	{"GAMETEXT.BIN", "TimeOfDay", "DUSK", "Lobby_UpdateServerInfo", 0x4FF0BD},
	{"GAMETEXT.BIN", "TimeOfDay", "NIGHT", "Lobby_UpdateServerInfo", 0x4FF0F4},
	{"GAMETEXT.BIN", "TimeOfDay", "UNKNOWN", "Lobby_UpdateServerInfo", 0x4FF122},
};

} // namespace

const std::vector<CodeTextKey> &code_text_keys() {
	static const std::vector<CodeTextKey> rows(std::begin(kRows), std::end(kRows));
	return rows;
}

std::vector<const CodeTextKey *> code_reads_of(const AssetGraph &graph, const GraphSymbol &symbol) {
	std::vector<const CodeTextKey *> out;
	if (symbol.kind != ReferenceKind::TextId) return out;
	const std::string name = strutil::to_upper(symbol.name);
	for (const CodeTextKey &row : code_text_keys()) {
		if (strutil::to_upper(row.key) != name) continue;
		const std::string scope = std::string(row.table) + "/" + row.section;
		if (graph.resolve_symbol(ReferenceKind::TextId, row.key, scope) == &symbol) out.push_back(&row);
	}
	return out;
}

} // namespace opennova::editor
