#!/usr/bin/env python3
"""The godot-cpp build profile (godot/src/godot_cpp_profile.json): the engine
classes the GDExtension can reach, so godot-cpp generates and compiles those
~190 classes instead of all ~1020 in extension_api.json.

The set is derived, never hand-edited:
  1. every extension_api.json class or native structure whose name appears as
     a token anywhere under godot/src (GDCLASS parents, casts, signatures,
     comments: a superset is harmless), and every class whose generated
     header godot/src includes (a header can be included without the class
     ever being named);
  2. closed over parents and over every type a method of an included class
     names in its signature (return value, arguments, the class of an enum
     or bitfield), so a chained call such as get_viewport()->get_camera_3d()
     keeps compiling: godot-cpp drops any method whose signature names a
     class outside the profile;
  3. plus the classes godot-cpp's own core sources include (PINNED).

A godot/src change that starts using a new engine class fails to compile
until the profile is regenerated with --write (CI's lint step runs
--enforce, so a stale profile fails there first).

Modes:
  (default)   report whether the profile is current; exit 0 (soft)
  --enforce   exit 1 when the tracked profile differs from the derived set
  --write     regenerate godot/src/godot_cpp_profile.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
API_PATH = REPO / "third_party/godot-cpp/gdextension/extension_api.json"
PROFILE_PATH = REPO / "godot/src/godot_cpp_profile.json"
SOURCE_ROOT = REPO / "godot/src"
SOURCE_SUFFIXES = (".h", ".hpp", ".cpp", ".inc")
SKIP_PARTS = {"build"}

# godot-cpp core sources outside the generated classes that include class
# headers build_profile.py does not add itself: src/core/print_string.cpp
# (os.hpp) and include/godot_cpp/core/mutex_lock.hpp (mutex.hpp).
PINNED = ("Mutex", "OS")

TOKEN = re.compile(r"\b[A-Z][A-Za-z0-9_]*\b")
TYPE_PART = re.compile(r"[A-Za-z0-9_]+")
CLASS_INCLUDE = re.compile(r"godot_cpp/classes/([a-z0-9_]+)\.hpp")


def header_stem(name: str) -> str:
    """A class's generated header name (binding_generator.py camel_to_snake)."""
    name = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    name = re.sub("([a-z0-9])([A-Z])", r"\1_\2", name)
    return name.replace("2_D", "2D").replace("3_D", "3D").lower()


def derive(api: dict, source: str) -> list[str]:
    classes = {c["name"]: c for c in api["classes"]}
    structs = {s["name"] for s in api.get("native_structures", [])}
    known = set(classes) | structs

    def signature_types(name: str) -> set[str]:
        found = set()
        for method in classes[name].get("methods", []):
            types = [method.get("return_value", {}).get("type", "")]
            types += [arg["type"] for arg in method.get("arguments", [])]
            for t in types:
                found.update(part for part in TYPE_PART.findall(t) if part in known)
        return found

    by_header = {header_stem(name): name for name in classes}
    pending = {token for token in TOKEN.findall(source) if token in known} | set(PINNED)
    pending |= {by_header[stem] for stem in CLASS_INCLUDE.findall(source) if stem in by_header}
    included: set[str] = set()
    while pending:
        name = pending.pop()
        if name in included:
            continue
        included.add(name)
        if name in classes:
            parent = classes[name].get("inherits", "")
            if parent:
                pending.add(parent)
            pending |= signature_types(name)
    return sorted(included)


def read_sources() -> str:
    chunks = []
    for path in sorted(SOURCE_ROOT.rglob("*")):
        if path.suffix in SOURCE_SUFFIXES and not SKIP_PARTS.intersection(path.relative_to(SOURCE_ROOT).parts):
            chunks.append(path.read_text(encoding="utf-8", errors="ignore"))
    return "\n".join(chunks)


def render(enabled: list[str]) -> str:
    profile = {
        "_comment": "Generated by scripts/lint/godot_cpp_profile.py; regenerate with --write "
                    "when godot/src starts using an engine class this list lacks.",
        "enabled_classes": enabled,
    }
    return json.dumps(profile, indent="\t") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--enforce", action="store_true", help="exit 1 when the profile is stale")
    mode.add_argument("--write", action="store_true", help="regenerate the profile")
    args = parser.parse_args()

    if not API_PATH.is_file():
        print(f"[godot-cpp-profile] {API_PATH.relative_to(REPO)} missing: init the godot-cpp submodule",
              file=sys.stderr)
        return 1 if args.enforce else 0
    api = json.loads(API_PATH.read_text(encoding="utf-8"))
    enabled = derive(api, read_sources())
    wanted = render(enabled)
    current = PROFILE_PATH.read_text(encoding="utf-8") if PROFILE_PATH.is_file() else ""

    if args.write:
        PROFILE_PATH.write_text(wanted, encoding="utf-8", newline="\n")
        print(f"[godot-cpp-profile] wrote {len(enabled)} of {len(api['classes'])} classes "
              f"to {PROFILE_PATH.relative_to(REPO)}")
        return 0
    if current == wanted:
        print(f"[godot-cpp-profile] current: {len(enabled)} of {len(api['classes'])} classes")
        return 0
    have = set(json.loads(current).get("enabled_classes", [])) if current else set()
    missing = sorted(set(enabled) - have)
    extra = sorted(have - set(enabled))
    print("[godot-cpp-profile] godot/src/godot_cpp_profile.json is stale; "
          "run python scripts/lint/godot_cpp_profile.py --write")
    if missing:
        print(f"[godot-cpp-profile]   missing: {', '.join(missing)}")
    if extra:
        print(f"[godot-cpp-profile]   no longer used: {', '.join(extra)}")
    return 1 if args.enforce else 0


if __name__ == "__main__":
    sys.exit(main())
