"""
Blender ASE Exporter - ASCII Scene Export
Based on 3ds Max ASCII Scene Export format

This module provides functionality to export Blender scenes to ASE format,
maintaining compatibility with the 3ds Max ASE specification.

The ASE text is generated by the native C library (libopennova) via FFI.
Python collects all Blender data and populates C structs; the C writer
produces the final .ase file.
"""

from __future__ import annotations

import ctypes
import bpy
import bmesh
import math
import os
import re
import traceback
from mathutils import Vector
from pyopennova import ase_ffi


class MaterialKeeper:
    """Material manager similar to 3ds Max MtlKeeper (flat list of materials).

    Materials are sorted by their IR index (extracted from Blender material
    name ``Material_{N}_...``) so that the exported order matches the .3dp
    order, ensuring OED name-based matching works correctly.
    """

    def __init__(self):
        self.materials = []
        self.material_map = {}
        self.object_material_map = {}

    @staticmethod
    def _is_source_material(material):
        return MaterialKeeper._ir_index(material) != 999999

    @staticmethod
    def _ir_index(material):
        """Extract the IR index from a Blender material name like 'Material_3_FF_ST_OP'.

        Returns the integer N, or a large fallback so unknown materials sort last.
        """
        if material is None:
            return 999999
        name = material.name
        if not name.startswith("Material_"):
            return 999999
        rest = name[len("Material_"):]
        parts = rest.split("_", 1)
        try:
            return int(parts[0])
        except (ValueError, IndexError):
            return 999999

    def add_material(self, material):
        """Register a material if it's not already present. Returns material index."""
        if material is None:
            return -1
        if not self._is_source_material(material):
            return -1
        if material in self.material_map:
            return self.material_map[material]
        idx = len(self.materials)
        self.materials.append(material)
        self.material_map[material] = idx
        return idx

    def add_object_materials(self, obj):
        """Register materials for a mesh object.

        Stores the global material index for the object's first material,
        used as the MATERIAL_REF in the exported ASE.
        """
        if not obj.data.materials:
            self.object_material_map[obj.name] = -1
            return -1

        first_idx = -1
        for mat in obj.data.materials:
            if mat is not None and self._is_source_material(mat):
                idx = self.add_material(mat)
                if first_idx == -1:
                    first_idx = idx

        self.object_material_map[obj.name] = first_idx if first_idx >= 0 else -1
        return first_idx if first_idx >= 0 else -1

    def sort_by_ir_index(self):
        """Re-sort materials by their IR index and rebuild the index map."""
        self.materials.sort(key=self._ir_index)
        self.material_map = {mat: i for i, mat in enumerate(self.materials)}

    def get_global_index(self, material):
        """Look up a Blender material's global sub-material index."""
        return self.material_map.get(material, 0)

    def get_object_material_id(self, obj):
        return self.object_material_map.get(obj.name, -1)

    def count(self):
        return len(self.materials)

    def get_material(self, idx):
        if 0 <= idx < len(self.materials):
            return self.materials[idx]
        return None


class AseExporter:
    """Main ASE exporter class"""

    # OED hard limit: each Multi/Sub-Object parent supports at most 64
    # submaterials before g_CurrentSubMaterial >= 64 triggers "Too many
    # submaterials!".  We split across multiple top-level material slots.
    SUBS_PER_SLOT = 64

    # OED MaterialTexSlot.path is char[16] (15 usable chars + null).
    # copy_str(dst, 16, src) uses strncpy(dst, src, 15) so texture filenames
    # (including extension) must be at most 15 characters to survive the
    # OED's ensure_bucket -> 3DI export pipeline without truncation.
    MAX_TEX_FILENAME = 15

    def __init__(self):
        # Export options
        self.include_mesh = True
        self.include_materials = True
        self.include_animations = False
        self.include_normals = True  # Unused by C writer (normals not in ASE struct)
        self.include_uvs = True
        self.include_vertex_colors = False
        self.include_bone_weights = True
        self.export_textures = True
        self.precision = 4
        self.scale = 1.0

        # Internal state
        self.material_keeper = MaterialKeeper()
        self.scene = None
        self._texture_queue = {}  # bitmap_filename -> bpy.types.Image
        self._used_tex_names = {}  # lowercase short name -> original short name (dedup)

        # Node processing
        self.total_node_count = 0

    def set_options(self, **options):
        """Set export options"""
        for key, value in options.items():
            if hasattr(self, key):
                setattr(self, key, value)

    @staticmethod
    def _is_visible(obj):
        visible_get = getattr(obj, "visible_get", None)
        if callable(visible_get):
            try:
                if not visible_get():
                    return False
            except TypeError:
                pass
        current = obj
        while current is not None:
            if getattr(current, "hide_viewport", False):
                return False
            hidden_get = getattr(current, "hide_get", None)
            if callable(hidden_get):
                try:
                    if hidden_get():
                        return False
                except TypeError:
                    pass
            current = getattr(current, "parent", None)
        return True

    @classmethod
    def _is_part_dummy(cls, obj):
        name = cls._clean_blender_duplicate_suffix(obj.name)
        return obj.type == 'EMPTY' and re.match(r"^PN\d{2}$", name) is not None

    @classmethod
    def _is_render_mesh(cls, obj):
        name = cls._clean_blender_duplicate_suffix(obj.name)
        return obj.type == 'MESH' and re.match(r"^\d{2} Mesh\d+$", name) is not None

    @classmethod
    def _is_helper_mesh(cls, obj):
        return obj.type == 'MESH' and not cls._is_render_mesh(obj)

    @classmethod
    def _visible_meshes(cls, scene):
        return [o for o in scene.objects if o.type == 'MESH' and cls._is_visible(o)]

    @classmethod
    def _part_dummy_objects(cls, scene):
        return sorted(
            [o for o in scene.objects if cls._is_part_dummy(o) and cls._is_visible(o)],
            key=cls._part_dummy_sort_key,
        )

    @classmethod
    def _ordered_mesh_objects(cls, scene):
        meshes = [
            (idx, obj)
            for idx, obj in enumerate(scene.objects)
            if obj.type == 'MESH' and cls._is_visible(obj)
        ]
        return [
            obj for _, obj in sorted(
                meshes,
                key=lambda item: cls._mesh_sort_key(item[1], item[0]),
            )
        ]

    @classmethod
    def _ordered_render_meshes(cls, scene):
        return [o for o in cls._ordered_mesh_objects(scene) if cls._is_render_mesh(o)]

    @classmethod
    def _ordered_helper_meshes(cls, scene):
        return [o for o in cls._ordered_mesh_objects(scene) if cls._is_helper_mesh(o)]

    @classmethod
    def _part_dummy_sort_key(cls, obj):
        name = cls._clean_blender_duplicate_suffix(obj.name)
        return cls._leading_number_key(name), name

    @classmethod
    def _mesh_sort_key(cls, obj, scene_index=0):
        name = cls._clean_blender_duplicate_suffix(obj.name)
        group = cls._mesh_group(name)
        if group == 4:
            return (group, cls._userpoint_sort_key(name), scene_index)
        if group in (3, 5, 6):
            return (group, scene_index, name)
        return (group, cls._leading_number_key(name), name)

    @staticmethod
    def _leading_number_key(name):
        match = re.search(r"\d+", name)
        return int(match.group(0)) if match else 999999

    @staticmethod
    def _userpoint_sort_key(name):
        match = re.match(r"^(UP(.|$)|USR)(\d{2})(?:\s+(.*))?$", name)
        if not match:
            return (0, 0, name.casefold())
        prefix = match.group(1)
        type_code = 0
        if prefix.startswith("UP") and len(prefix) >= 3:
            type_code = ord(prefix[2])
        part_index = int(match.group(3)) - 1
        label = (match.group(4) or "").casefold()
        return (-part_index, type_code, label)

    @staticmethod
    def _mesh_group(name):
        if re.match(r"^\d{2} Mesh\d+$", name):
            return 0
        if re.match(r"^_\d{2} center$", name):
            return 2
        if name.startswith("~") and " attach" in name:
            return 3
        if name.startswith("UP") or name.startswith("USR"):
            return 4
        if "-colonly" in name:
            return 5
        if "-occonly" in name:
            return 6
        return 9

    @classmethod
    def _is_unrotated_marker_mesh(cls, obj):
        name = cls._clean_blender_duplicate_suffix(obj.name)
        return (
            re.match(r"^_\d{2} center$", name) is not None
            or (name.startswith("~") and " attach" in name)
            or name.startswith("UP")
            or name.startswith("USR")
        )

    @classmethod
    def _uses_absolute_render_mesh_vertices(cls, obj):
        return (
            cls._is_render_mesh(obj)
            and obj.parent is not None
            and cls._is_part_dummy(obj.parent)
            and cls._matrix_is_identity(obj.matrix_world)
        )

    @staticmethod
    def _matrix_is_identity(matrix, tolerance=1e-8):
        for r in range(4):
            for c in range(4):
                expected = 1.0 if r == c else 0.0
                if abs(matrix[r][c] - expected) > tolerance:
                    return False
        return True

    def export_scene(self, scene, filepath):
        """Export scene to ASE file via native C writer.

        Exports the currently visible/exportable scene to the primary filepath.
        Export one LOD at a time by hiding or excluding other LOD scene roots.
        """
        self.scene = scene

        print(f"ASE Export: Starting export to {filepath}")

        try:
            if not filepath:
                raise ValueError("No output filepath specified")

            output_dir = os.path.dirname(filepath)
            if output_dir and not os.path.exists(output_dir):
                print(f"ASE Export: Creating directory {output_dir}")
                os.makedirs(output_dir, exist_ok=True)

            # Phase 1: Preprocess visible exportable objects and materials.
            print(f"ASE Export: Preprocessing scene")
            self.preprocess_scene()
            print(f"ASE Export: Found {self.total_node_count} exportable objects")

            # Phase 2: Count entities for C document allocation.
            render_mesh_objects = self._ordered_render_meshes(scene)
            part_dummy_objects = self._part_dummy_objects(scene)
            helper_mesh_objects = self._ordered_helper_meshes(scene)
            mesh_objects = render_mesh_objects + helper_mesh_objects

            light_objects = [o for o in scene.objects if o.type == 'LIGHT' and self._is_visible(o)]
            bone_list = []
            for o in scene.objects:
                if o.type == 'ARMATURE' and o.pose and self._is_visible(o):
                    for bone in sorted(o.pose.bones, key=lambda b: b.name):
                        bone_list.append((o, bone))

            total_objects = len(render_mesh_objects) + len(part_dummy_objects) + len(helper_mesh_objects) + len(bone_list)
            total_materials = self.material_keeper.count() if self.include_materials else 0
            total_lights = len(light_objects)

            print(f"ASE Export: {total_objects} objects ({len(render_mesh_objects)} render meshes, "
                  f"{len(part_dummy_objects)} PN dummies, {len(helper_mesh_objects)} helpers, "
                  f"{len(bone_list)} bones), {total_materials} materials, {total_lights} lights")

            # Phase 3: Create and populate C document
            # Allocate ceil(N/64) top-level Multi/Sub-Object material slots,
            # each holding up to 64 submaterials (OED hard limit per parent).
            doc_materials = math.ceil(total_materials / self.SUBS_PER_SLOT) if total_materials > 0 else 0
            doc = ase_ffi.create_document(total_objects, doc_materials, total_lights)

            has_skinned = any(
                o.vertex_groups and any(m.type == 'ARMATURE' and m.object for m in o.modifiers)
                for o in mesh_objects
            )
            doc.flags = 1 if has_skinned else 0
            doc.skinned_flags = 1 if has_skinned else 0

            # Populate materials
            if self.include_materials:
                print(f"ASE Export: Populating {total_materials} materials")
                self._populate_materials(doc)

            # Populate objects: bones first, then meshes (matches 3ds Max export order)
            obj_idx = 0
            for arm_obj, bone in bone_list:
                self._populate_bone_object(doc.objects[obj_idx], arm_obj, bone)
                obj_idx += 1

            for mesh_obj in render_mesh_objects:
                print(f"ASE Export: Populating geometry '{mesh_obj.name}'")
                self._populate_geometry(doc.objects[obj_idx], mesh_obj)
                obj_idx += 1

            for part_obj in part_dummy_objects:
                print(f"ASE Export: Populating PN dummy '{part_obj.name}'")
                self._populate_part_dummy_object(doc.objects[obj_idx], part_obj)
                obj_idx += 1

            for mesh_obj in helper_mesh_objects:
                print(f"ASE Export: Populating helper geometry '{mesh_obj.name}'")
                self._populate_geometry(doc.objects[obj_idx], mesh_obj)
                obj_idx += 1

            # Populate lights
            for i, light_obj in enumerate(light_objects):
                self._populate_light(doc.lights[i], light_obj)

            # Phase 4: Write via C library
            ase_ffi.write_file(filepath, doc)
            # Clear Python-allocated face_normals before C-side free
            for i in range(doc.object_count):
                doc.objects[i].face_normals = None
                doc.objects[i].face_normal_count = 0
            ase_ffi.free_document(doc)

            # Phase 5: Save texture files after the ASE is written
            if self.export_textures and self._texture_queue:
                self._save_textures(output_dir or '.')

            print("ASE Export: Scene export completed successfully")

            return True

        except PermissionError as e:
            error_msg = f"Permission denied writing to {filepath}: {str(e)}"
            print(f"ASE Export Error: {error_msg}")
            raise Exception(error_msg)

        except OSError as e:
            error_msg = f"File system error: {str(e)}"
            print(f"ASE Export Error: {error_msg}")
            raise Exception(error_msg)

        except Exception as e:
            error_msg = f"ASE Export failed: {str(e)}"
            print(f"ASE Export Error: {error_msg}")
            print("Full traceback:")
            traceback.print_exc()
            raise Exception(error_msg)

    # -------------------------------------------------------------------
    # Scene preprocessing
    # -------------------------------------------------------------------

    def preprocess_scene(self):
        """Count nodes and prepare materials"""
        self.material_keeper = MaterialKeeper()
        self.total_node_count = 0

        for obj in self.scene.objects:
            if self.is_exportable_object(obj) and self._is_visible(obj):
                self.total_node_count += 1

                # Register object materials
                if obj.type == 'MESH' and obj.data.materials:
                    self.material_keeper.add_object_materials(obj)

        # Sort materials by IR index so export order matches .3dp order
        self.material_keeper.sort_by_ir_index()

    def is_exportable_object(self, obj):
        """Check if object should be exported"""
        return obj.type in ('MESH', 'CAMERA', 'LIGHT', 'CURVE', 'EMPTY')

    # -------------------------------------------------------------------
    # Material population
    # -------------------------------------------------------------------

    def _populate_materials(self, doc):
        """Fill doc.materials as Multi/Sub-Object parents, each with up to 64 submaterials.

        OED's EnsureMaterialBucket deduplicates faces by submaterial name,
        so using Multi/Sub-Object parents with named submaterials produces one
        rendering bucket per unique material instead of one per face.

        OED hardcodes a 64-submaterial limit per parent, but supports 512
        top-level material slots.  We split across ceil(N/64) slots.
        """
        total = self.material_keeper.count()
        if total == 0:
            return

        has_skinned = bool(doc.skinned_flags)
        num_slots = math.ceil(total / self.SUBS_PER_SLOT)

        for slot_idx in range(num_slots):
            start = slot_idx * self.SUBS_PER_SLOT
            end = min(start + self.SUBS_PER_SLOT, total)
            count_in_slot = end - start

            parent = doc.materials[slot_idx]
            parent.name = f"Scene_Materials_{slot_idx}".encode('utf-8')[:31]
            ase_ffi.alloc_submaterials(parent, count_in_slot)

        from pyopennova.ase_material_writer import populate_ase_submaterial

        used_tex_names: dict[str, str] = {}

        for i in range(total):
            material = self.material_keeper.get_material(i)
            slot_idx = i // self.SUBS_PER_SLOT
            local_idx = i % self.SUBS_PER_SLOT
            sub = doc.materials[slot_idx].submaterials[local_idx]

            desc = self._collect_material_descriptor(material, has_skinned, i)
            populate_ase_submaterial(sub, desc, used_tex_names=used_tex_names)

            # Blender-driven material colors override the shared writer's
            # defaults so the .ase reflects what the artist set in Blender.
            if material and not MaterialKeeper._is_source_material(material):
                diff = self._get_material_diffuse(material)
                sub.diffuse[0], sub.diffuse[1], sub.diffuse[2] = diff
                if not (desc.glass and any(desc.reflect_color[:3])):
                    sub.ambient[0] = diff[0] * 0.1
                    sub.ambient[1] = diff[1] * 0.1
                    sub.ambient[2] = diff[2] * 0.1
                spec = self._get_material_specular(material)
                sub.specular[0], sub.specular[1], sub.specular[2] = spec
                sub.shine = self._get_material_shine(material)
                sub.transparency = self._get_material_transparency(material)

            print(
                f"ASE Export: Submaterial {i} -> shader={desc.shader} "
                f"name={desc.name} shading={'Phong' if sub.shading == 1 else 'Blinn'}"
                f"{' detail=' + desc.detail.name if desc.detail.name else ''}"
            )

    def _collect_material_descriptor(self, material, has_skinned: bool, index: int):
        """Build a descriptor from visible Blender material state."""
        from pyopennova.materials import (
            MATERIAL_BLEND_ALPHA,
            MATERIAL_BLEND_OPAQUE,
            MaterialDescriptor,
            TextureDescriptor,
            THREEDI_MATERIAL_FLAG_ALPHA_TEST,
            classify_material_shader,
        )

        diffuse_bitmap = ""
        diffuse_image = None
        if material and material.use_nodes and material.node_tree:
            found_name, found_image = self._find_bitmap_from_nodes(material)
            if found_image:
                diffuse_image = found_image
            if not diffuse_bitmap and found_name:
                diffuse_bitmap = found_name

        detail_bitmap = ""
        detail_image = None
        if material and material.use_nodes and material.node_tree:
            node_detail_bitmap, node_detail_image = self._find_detail_from_nodes(material)
            if node_detail_bitmap and not detail_bitmap:
                detail_bitmap = node_detail_bitmap
            if node_detail_image:
                detail_image = node_detail_image

        # Apply df4oed compatibility transforms to the names used in the .ase.
        diffuse_bitmap = self._fit_texture_name(self._fix_tex_ext(diffuse_bitmap))
        if detail_bitmap:
            detail_bitmap = self._fit_texture_name(self._fix_tex_ext(detail_bitmap))

        # Queue images for TGA export.
        if diffuse_bitmap and diffuse_image:
            self._texture_queue[diffuse_bitmap] = diffuse_image
        if detail_bitmap and detail_image:
            self._texture_queue[detail_bitmap] = detail_image

        shader_code = self._shader_from_material_name(material)
        if not shader_code:
            shader_code = self._derive_opennova_shader(material, has_skinned)

        material_flags = 0
        alpha_threshold = 0.0
        renderer_blend = MATERIAL_BLEND_OPAQUE
        if material:
            blend_method = getattr(material, "blend_method", "OPAQUE")
            if blend_method == "CLIP":
                material_flags |= THREEDI_MATERIAL_FLAG_ALPHA_TEST
                alpha_threshold = float(getattr(material, "alpha_threshold", 0.5))
            elif blend_method not in ("OPAQUE", None):
                renderer_blend = MATERIAL_BLEND_ALPHA

        semantics = classify_material_shader(
            shader_code,
            material_flags=material_flags,
            alpha_test_value_byte=int(round(alpha_threshold * 255.0)),
        )
        if renderer_blend == MATERIAL_BLEND_OPAQUE:
            renderer_blend = semantics.blend

        u_tile, v_tile, has_custom_tiling = self._collect_uv_tiling(material)
        u1_tile, v1_tile = self._collect_detail_uv_tiling(material)
        reflect_color = (0.0, 0.0, 0.0, 0.0)
        if material and semantics.is_glass:
            diff = tuple(float(v) for v in material.diffuse_color[:4])
            if any(abs(diff[i] - 0.588) > 1e-4 for i in range(3)):
                reflect_color = diff

        return MaterialDescriptor(
            index=index,
            shader=shader_code,
            name=self._material_export_name(material, index, shader_code),
            diffuse=TextureDescriptor("diffuse", diffuse_bitmap or ""),
            detail=TextureDescriptor("detail", detail_bitmap or ""),
            material_flags=material_flags,
            source_material_flags=material_flags,
            alpha_test_value_byte=int(round(alpha_threshold * 255.0)),
            alpha_threshold=alpha_threshold,
            renderer_blend=renderer_blend,
            alpha_test=bool(material_flags & THREEDI_MATERIAL_FLAG_ALPHA_TEST),
            two_sided=bool(material and not getattr(material, "use_backface_culling", True)),
            emissive=semantics.is_emissive,
            glass=semantics.is_glass,
            reflect_color=reflect_color,
            has_detail_slot=semantics.has_detail or bool(detail_bitmap),
            phong_shader=semantics.family in ("phong", "environment", "glass"),
            known_shader=semantics.known_shader,
            shader_family=semantics.family,
            resolved_shader=semantics.resolved_shader,
            needs_normal_map=semantics.needs_normal_map,
            normal_space=semantics.normal_space,
            normal_uses_uv2=semantics.normal_uses_uv2,
            uses_specular=semantics.uses_specular,
            uses_environment=semantics.uses_environment,
            is_luminance=semantics.is_luminance,
            is_skinned=semantics.is_skinned,
            u_tiling=0.0 if (u_tile == 1.0 and v_tile == 1.0) else u_tile,
            v_tiling=0.0 if (u_tile == 1.0 and v_tile == 1.0) else v_tile,
            effective_u_tiling=u_tile,
            effective_v_tiling=v_tile,
            effective_u1_tiling=u1_tile,
            effective_v1_tiling=v1_tile,
            has_custom_tiling=has_custom_tiling,
        )

    @staticmethod
    def _collect_uv_tiling(material):
        """Read diffuse UV tiling from Blender Mapping nodes."""
        if not material or not material.use_nodes or not material.node_tree:
            return 1.0, 1.0, False

        for node in material.node_tree.nodes:
            if node.type != 'MAPPING':
                continue
            marker = f"{node.name} {getattr(node, 'label', '')}".lower()
            if "detail" in marker:
                continue
            scale_input = node.inputs.get("Scale")
            if not scale_input:
                continue
            value = scale_input.default_value
            u_tile = float(value[0])
            v_tile = float(value[1])
            has_custom = abs(u_tile - 1.0) > 1e-6 or abs(v_tile - 1.0) > 1e-6
            return u_tile, v_tile, has_custom

        return 1.0, 1.0, False

    @staticmethod
    def _collect_detail_uv_tiling(material):
        """Read detail/lightmap UV tiling from the detail Mapping node."""
        if not material or not material.use_nodes or not material.node_tree:
            return 1.0, 1.0

        for node in material.node_tree.nodes:
            if node.type != 'MAPPING':
                continue
            marker = f"{node.name} {getattr(node, 'label', '')}".lower()
            if "detail" not in marker:
                continue
            scale_input = node.inputs.get("Scale")
            if not scale_input:
                continue
            value = scale_input.default_value
            return float(value[0]), float(value[1])

        for node in material.node_tree.nodes:
            if node.type != 'TEX_IMAGE' or not node.image:
                continue
            marker = f"{node.name} {getattr(node, 'label', '')}".lower()
            if "detail" not in marker:
                continue
            vector_input = node.inputs.get("Vector")
            if vector_input and vector_input.is_linked:
                from_node = vector_input.links[0].from_node
                if from_node.type == 'MAPPING':
                    scale_input = from_node.inputs.get("Scale")
                    if scale_input:
                        value = scale_input.default_value
                        return float(value[0]), float(value[1])

        return 1.0, 1.0

    # -------------------------------------------------------------------
    # Geometry population
    # -------------------------------------------------------------------

    def _populate_geometry(self, ase_obj, obj):
        """Fill an AseObject from a Blender mesh object."""
        mesh_eval, bm, temp_mesh, neg_scale, orig_edge_keys = \
            self._prepare_triangulated_mesh(obj)

        try:
            vert_count = len(temp_mesh.vertices)
            face_count = len(temp_mesh.loop_triangles)
            print(f"ASE Export: Triangulated mesh has {vert_count} vertices, "
                  f"{face_count} triangles (neg_scale={neg_scale})")

            # Collect UV data (need count before allocation)
            uv_coords, uv_face_indices = self._collect_uv_data(temp_mesh, neg_scale)
            uv_count = len(uv_coords)

            # Collect color data (need count before allocation)
            color_list, color_face_indices = self._collect_color_data(
                temp_mesh, neg_scale)
            color_count = len(color_list)

            # Collect weight data
            weight_list = self._collect_weight_data(obj, temp_mesh)
            weight_count = len(weight_list)

            # Allocate C arrays
            ase_ffi.alloc_object(ase_obj, vert_count, uv_count, face_count,
                                color_count, weight_count)

            export_name = self._export_name(obj.name)
            ase_obj.name = self.fixup_name(export_name).encode('utf-8')[:63]
            if obj.parent:
                parent_name = self._export_name(obj.parent.name)
                ase_obj.parent_name = self.fixup_name(parent_name).encode('utf-8')[:63]
            ase_obj.node_id = -1
            if obj.name.startswith("BN") and len(obj.name) >= 4 and obj.name[2:4].isdigit():
                try:
                    ase_obj.node_id = int(obj.name[2:4]) - 1
                except ValueError:
                    pass
            # ASE writer emits *MESH_WEIGHTS only when object.skinned is set.
            # Without this flag, weighted meshes silently lose skin data.
            ase_obj.skinned = 1 if weight_count > 0 else 0
            # Compute which Multi/Sub-Object slot this object references.
            # material_ref selects the top-level slot; face.material_id selects
            # the submaterial within it.
            if (obj.data.materials and obj.data.materials[0] is not None
                    and MaterialKeeper._is_source_material(obj.data.materials[0])):
                global_idx = self.material_keeper.get_global_index(obj.data.materials[0])
                ase_obj.material_ref = global_idx // self.SUBS_PER_SLOT
            elif self._is_helper_mesh(obj):
                ase_obj.material_ref = -1
            else:
                ase_obj.material_ref = 0

            # Build per-slot material_id lookup for multi-material meshes
            _slot_mat_ids = []
            for slot_mat in obj.data.materials:
                if slot_mat is not None and MaterialKeeper._is_source_material(slot_mat):
                    _slot_mat_ids.append(
                        self.material_keeper.get_global_index(slot_mat) % self.SUBS_PER_SLOT)
                else:
                    _slot_mat_ids.append(0)
            tm_matrix = (
                obj.parent.matrix_world
                if self._uses_absolute_render_mesh_vertices(obj)
                else obj.matrix_world
            )
            self._set_object_tm(ase_obj, tm_matrix)
            clean_name = self._clean_blender_duplicate_suffix(obj.name)
            if clean_name.startswith("UP") or clean_name.startswith("USR"):
                if (
                    ase_obj.tm_row[0][2] == 0.0
                    and ase_obj.tm_row[0][1] == 0.0
                    and ase_obj.tm_row[0][0] > 0.999999
                ):
                    ase_obj.tm_row[0][2] = -0.0
                if (
                    ase_obj.tm_row[2][1] == 0.0
                    and ase_obj.tm_row[2][0] == 0.0
                    and ase_obj.tm_row[2][2] > 0.999999
                ):
                    ase_obj.tm_row[2][1] = -0.0

            # Vertices (world-space, scaled)
            transform = obj.matrix_world
            marker_verts_are_unrotated = self._is_unrotated_marker_mesh(obj)
            marker_origin = transform.translation
            for i, v in enumerate(temp_mesh.vertices):
                if marker_verts_are_unrotated:
                    co = marker_origin + v.co
                else:
                    co = transform @ v.co
                ase_obj.verts[i * 3] = co.x * self.scale
                ase_obj.verts[i * 3 + 1] = self._ase_y(co.y * self.scale)
                ase_obj.verts[i * 3 + 2] = co.z * self.scale

            # Faces
            sg_attr = (temp_mesh.attributes.get('smoothing_group')
                       if hasattr(temp_mesh, 'attributes') else None)
            sg_is_face = sg_attr and sg_attr.domain == 'FACE'

            for i, tri in enumerate(temp_mesh.loop_triangles):
                face = ase_obj.faces[i]

                if neg_scale:
                    face.vert[0] = int(tri.vertices[2])
                    face.vert[1] = int(tri.vertices[1])
                    face.vert[2] = int(tri.vertices[0])
                else:
                    face.vert[0] = int(tri.vertices[0])
                    face.vert[1] = int(tri.vertices[1])
                    face.vert[2] = int(tri.vertices[2])

                # Map face to the local submaterial index within its
                # Multi/Sub-Object slot, supporting multi-material meshes.
                slot_idx = tri.material_index if hasattr(tri, 'material_index') else 0
                if slot_idx < len(_slot_mat_ids):
                    face.material_id = _slot_mat_ids[slot_idx]
                elif _slot_mat_ids:
                    face.material_id = _slot_mat_ids[0]
                else:
                    face.material_id = 0

                if sg_is_face:
                    face.smoothing_mask = sg_attr.data[i].value
                else:
                    face.smoothing_mask = 1 if tri.use_smooth else 0

                v0, v1, v2 = face.vert[0], face.vert[1], face.vert[2]
                if orig_edge_keys:
                    face.edge_visibility[0] = (
                        1 if tuple(sorted((v0, v1))) in orig_edge_keys else 0)
                    face.edge_visibility[1] = (
                        1 if tuple(sorted((v1, v2))) in orig_edge_keys else 0)
                    face.edge_visibility[2] = (
                        1 if tuple(sorted((v2, v0))) in orig_edge_keys else 0)
                else:
                    face.edge_visibility[0] = 1
                    face.edge_visibility[1] = 1
                    face.edge_visibility[2] = 1

            # UVs
            for i, (u, v) in enumerate(uv_coords):
                ase_obj.uvs[i].u = u
                ase_obj.uvs[i].v = v
                ase_obj.uvs[i].w = 0.0
            for i, (t0, t1, t2) in enumerate(uv_face_indices):
                ase_obj.faces[i].uv[0] = t0
                ase_obj.faces[i].uv[1] = t1
                ase_obj.faces[i].uv[2] = t2

            # Vertex colors
            for i, rgb in enumerate(color_list):
                r, g, b = rgb[0], rgb[1], rgb[2]
                ase_obj.colors[i] = ((min(255, int(r * 255)) << 16) |
                                     (min(255, int(g * 255)) << 8) |
                                     min(255, int(b * 255)))
            if color_count > 0:
                ase_obj.color_face_count = face_count
            for i, (c0, c1, c2) in enumerate(color_face_indices):
                ase_obj.faces[i].color[0] = c0
                ase_obj.faces[i].color[1] = c1
                ase_obj.faces[i].color[2] = c2

            # Weights
            for i, (influences, wts) in enumerate(weight_list):
                for j in range(4):
                    ase_obj.weights[i].bone_index[j] = influences[j]
                    ase_obj.weights[i].weight[j] = wts[j]

            # Pre-computed per-face-vertex normals from custom split normals.
            # These bypass smoothing-group recomputation in the vertex builder,
            # giving exact normal values from the original IR.
            self._populate_face_normals(ase_obj, temp_mesh, neg_scale, obj.matrix_world)

        finally:
            if bm is not None:
                bm.free()
            bpy.data.meshes.remove(temp_mesh)

    def _populate_face_normals(self, ase_obj, temp_mesh, neg_scale, world_matrix):
        """Populate pre-computed per-face-vertex normals on the ase_Object.

        Reads Blender's custom split normals (which carry the original IR
        normals through the roundtrip) and stores them in Blender world space
        (same as vertex positions). The ASE parser's swizzle_vec3 will handle
        the coordinate conversion to internal space when reading back.
        """
        face_count = len(temp_mesh.loop_triangles)
        if face_count == 0:
            return

        normal_attr = (temp_mesh.attributes.get('ase_corner_normals')
                       if hasattr(temp_mesh, 'attributes') else None)
        if normal_attr and normal_attr.domain == 'CORNER':
            self._populate_face_normals_from_attribute(
                ase_obj, temp_mesh, neg_scale, world_matrix, normal_attr)
            return

        # Check if custom split normals are available
        has_custom = hasattr(temp_mesh, 'has_custom_normals') and temp_mesh.has_custom_normals
        if not has_custom:
            return

        # Get the rotation part of the world matrix for transforming normals
        rot = world_matrix.to_3x3().normalized()

        # Allocate the float array: face_count * 9 floats
        FloatArray = ctypes.c_float * (face_count * 9)
        normals_array = FloatArray()

        for i, tri in enumerate(temp_mesh.loop_triangles):
            # Match winding reversal with face vertex order
            loops = list(reversed(tri.loops)) if neg_scale else list(tri.loops)

            for j, loop_idx in enumerate(loops):
                loop = temp_mesh.loops[loop_idx]
                # Get the custom split normal in object space, then world space
                n = Vector(loop.normal)
                n = rot @ n
                n.normalize()

                # Write in Blender world space (no swizzle — parser handles it)
                base = i * 9 + j * 3
                normals_array[base + 0] = n.x
                normals_array[base + 1] = n.y
                normals_array[base + 2] = n.z

        # Store on the ase_Object — keep a reference to prevent GC
        ase_obj.face_normal_count = face_count
        ase_obj.face_normals = ctypes.cast(normals_array, ctypes.POINTER(ctypes.c_float))
        # Prevent garbage collection of the backing array
        if not hasattr(self, '_face_normal_arrays'):
            self._face_normal_arrays = []
        self._face_normal_arrays.append(normals_array)

    def _populate_face_normals_from_attribute(
        self, ase_obj, temp_mesh, neg_scale, world_matrix, normal_attr
    ):
        face_count = len(temp_mesh.loop_triangles)
        FloatArray = ctypes.c_float * (face_count * 9)
        normals_array = FloatArray()

        rot = world_matrix.to_3x3().normalized()
        identity_rot = all(
            abs(rot[r][c] - (1.0 if r == c else 0.0)) <= 1e-8
            for r in range(3)
            for c in range(3)
        )

        for i, tri in enumerate(temp_mesh.loop_triangles):
            loops = list(reversed(tri.loops)) if neg_scale else list(tri.loops)

            for j, loop_idx in enumerate(loops):
                vec = normal_attr.data[loop_idx].vector
                if identity_rot:
                    x = float(vec[0])
                    y = self._ase_y(float(vec[1]))
                    z = float(vec[2])
                else:
                    n = rot @ Vector((vec[0], vec[1], vec[2]))
                    if n.length_squared > 1e-12:
                        n.normalize()
                    x = float(n.x)
                    y = self._ase_y(float(n.y))
                    z = float(n.z)

                base = i * 9 + j * 3
                normals_array[base + 0] = x
                normals_array[base + 1] = y
                normals_array[base + 2] = z

        ase_obj.face_normal_count = face_count
        ase_obj.face_normals = ctypes.cast(normals_array, ctypes.POINTER(ctypes.c_float))
        if not hasattr(self, '_face_normal_arrays'):
            self._face_normal_arrays = []
        self._face_normal_arrays.append(normals_array)

    def _collect_uv_data(self, temp_mesh, neg_scale):
        """Collect per-face-corner UV coordinates and per-face UV indices.

        Returns (uv_coords, uv_face_indices) where uv_coords is a list of
        (u, v) tuples and uv_face_indices is a list of (t0, t1, t2)
        tuples indexing into uv_coords.
        """
        if not self.include_uvs or not temp_mesh.uv_layers:
            return [], []

        uv_layer = temp_mesh.uv_layers.active
        if not uv_layer:
            return [], []

        uv_coords = []
        uv_faces = []

        for tri in temp_mesh.loop_triangles:
            face_uvs = []
            # Reverse loop order for negative scale to match winding reversal
            loops = list(reversed(tri.loops)) if neg_scale else list(tri.loops)
            for loop_index in loops:
                uv = uv_layer.data[loop_index].uv
                # Match direct IR -> ASE: one TVERT per face corner.
                face_uvs.append(len(uv_coords))
                uv_coords.append((uv.x, uv.y))

            uv_faces.append(tuple(face_uvs))

        return uv_coords, uv_faces

    def _collect_color_data(self, temp_mesh, neg_scale):
        """Collect deduplicated vertex colors and per-face color indices.

        Returns (color_list, color_face_indices) where color_list is a list of
        (r, g, b) float tuples and color_face_indices is a list of (c0, c1, c2)
        tuples indexing into color_list.
        """
        if not self.include_vertex_colors:
            return [], []
        if not hasattr(temp_mesh, 'color_attributes') or not temp_mesh.color_attributes:
            return [], []

        color_layer = temp_mesh.color_attributes.active_color
        if not color_layer:
            return [], []

        colors = []
        color_faces = []
        color_map = {}

        for tri in temp_mesh.loop_triangles:
            face_colors = []
            loops = (list(reversed(tri.loops)) if neg_scale
                     else list(tri.loops))
            for loop_index in loops:
                color = color_layer.data[loop_index].color
                color_key = tuple(round(c, 6) for c in color[:3])

                if color_key not in color_map:
                    color_map[color_key] = len(colors)
                    colors.append(color[:3])

                face_colors.append(color_map[color_key])

            color_faces.append(tuple(face_colors))

        return colors, color_faces

    def _collect_weight_data(self, obj, temp_mesh):
        """Collect bone weight data for all vertices.

        Returns list of (influences, weights) tuples per vertex where
        influences and weights are each 4-element lists. Returns empty
        list if no weights are available.
        """
        if not self.include_bone_weights or not obj.vertex_groups:
            return []

        # Check for armature modifier to get bone mapping
        armature_mod = None
        for mod in obj.modifiers:
            if mod.type == 'ARMATURE' and mod.object:
                armature_mod = mod
                break

        if not armature_mod:
            return []

        armature_obj = armature_mod.object
        print(f"ASE Export: Found armature '{armature_obj.name}' with "
              f"{len(armature_obj.pose.bones)} bones")

        # Create bone name to number mapping (BN01, BN02, etc.)
        bone_number_map = {}
        for bone_name in armature_obj.pose.bones.keys():
            if bone_name.startswith("BN") and len(bone_name) >= 4:
                try:
                    bone_number_map[bone_name] = int(bone_name[2:4]) - 1
                except ValueError:
                    pass

        def _group_bone_index(group):
            # Preferred mapping: armature BN## names.
            if group.name in bone_number_map:
                return bone_number_map[group.name]
            # Fallback: parse BN## directly from group name.
            if group.name.startswith("BN") and len(group.name) >= 4:
                try:
                    return int(group.name[2:4]) - 1
                except ValueError:
                    return None
            return None

        result = []
        weighted_count = 0
        for vertex in temp_mesh.vertices:
            influences = [-1, -1, -1, -1]
            weights = [0.0, 0.0, 0.0, 0.0]

            # Collect all vertex group influences for this vertex
            vertex_influences = []
            for group in obj.vertex_groups:
                bone_idx = _group_bone_index(group)
                if bone_idx is None or bone_idx < 0:
                    continue
                try:
                    w = group.weight(vertex.index)
                    if w > 0:
                        vertex_influences.append((bone_idx, w))
                except RuntimeError:
                    continue

            # Sort by bone index (ascending) and take top 4
            vertex_influences.sort(key=lambda x: x[0])
            vertex_influences = vertex_influences[:4]

            for j, (bone_num, w) in enumerate(vertex_influences):
                influences[j] = bone_num
                weights[j] = w

            if vertex_influences:
                weighted_count += 1

            result.append((influences, weights))

        print(f"ASE Export: Collected weights for {len(result)} vertices "
              f"({weighted_count} with bone influences)")
        return result

    # -------------------------------------------------------------------
    # PN dummy population
    # -------------------------------------------------------------------

    def _populate_part_dummy_object(self, ase_obj, obj):
        """Fill a PN## dummy cube from a Blender part Empty."""
        half = 0.0005
        verts = [
            (-half, -half, -half),
            ( half, -half, -half),
            ( half,  half, -half),
            (-half,  half, -half),
            (-half, -half,  half),
            ( half, -half,  half),
            ( half,  half,  half),
            (-half,  half,  half),
        ]
        faces = [
            (0, 1, 2), (0, 2, 3),
            (4, 7, 6), (4, 6, 5),
            (0, 4, 5), (0, 5, 1),
            (2, 6, 7), (2, 7, 3),
            (1, 5, 6), (1, 6, 2),
            (0, 3, 7), (0, 7, 4),
        ]

        ase_ffi.alloc_object(ase_obj, len(verts), 0, len(faces), 0, 0)
        export_name = self._clean_blender_duplicate_suffix(obj.name)
        ase_obj.name = self.fixup_name(export_name).encode('utf-8')[:63]
        ase_obj.parent_name = b""
        ase_obj.node_id = -1
        ase_obj.material_ref = -1
        ase_obj.skinned = 0
        self._set_object_tm(ase_obj, obj.matrix_world)

        origin = obj.matrix_world.translation
        for i, v in enumerate(verts):
            ase_obj.verts[i * 3] = (origin.x + v[0]) * self.scale
            ase_obj.verts[i * 3 + 1] = self._ase_y((origin.y + v[1]) * self.scale)
            ase_obj.verts[i * 3 + 2] = (origin.z + v[2]) * self.scale

        for i, (a, b, c) in enumerate(faces):
            face = ase_obj.faces[i]
            face.vert[0], face.vert[1], face.vert[2] = a, b, c
            face.smoothing_mask = 0
            face.material_id = 0
            face.edge_visibility[0] = 1
            face.edge_visibility[1] = 1
            face.edge_visibility[2] = 1

    # -------------------------------------------------------------------
    # Bone object population
    # -------------------------------------------------------------------

    def _populate_bone_object(self, ase_obj, armature_obj, pose_bone):
        """Fill an AseObject for a bone with a small bone mesh."""
        bone_name = self._bone_export_name(pose_bone.name)
        if pose_bone.parent:
            parent_name = self._bone_export_name(pose_bone.parent.name)
        else:
            parent_name = ""

        origin = self._bone_export_origin(armature_obj, pose_bone, bone_name)

        # Bone mesh geometry (9 verts, 14 faces)
        base = 0.01
        tip = 0.001
        base_z = 0.01
        tip_z = 0.10

        verts_local = [
            ( base,  base, base_z),
            ( base, -base, base_z),
            (-base, -base, base_z),
            (-base,  base, base_z),
            ( tip,  tip,  tip_z),
            ( tip, -tip,  tip_z),
            (-tip, -tip,  tip_z),
            (-tip,  tip,  tip_z),
            (0.0, 0.0, 0.0),
        ]

        face_indices = [
            (8, 0, 1), (8, 1, 2), (8, 2, 3), (8, 3, 0),
            (0, 1, 5), (0, 5, 4), (1, 2, 6), (1, 6, 5),
            (2, 3, 7), (2, 7, 6), (3, 0, 4), (3, 4, 7),
            (4, 5, 6), (4, 6, 7),
        ]

        ase_ffi.alloc_object(ase_obj, len(verts_local), 0, len(face_indices),
                             0, 0)

        ase_obj.name = self.fixup_name(bone_name).encode('utf-8')[:63]
        ase_obj.parent_name = self.fixup_name(parent_name).encode('utf-8')[:63]

        ase_obj.node_id = -1
        if (bone_name.startswith("BN") and len(bone_name) >= 4
                and bone_name[2:4].isdigit()):
            ase_obj.node_id = int(bone_name[2:4]) - 1
        ase_obj.material_ref = -1

        self._set_identity_tm(ase_obj, origin)

        # Direct 3DI ASE uses an unrotated marker mesh offset by bone origin.
        for i, v in enumerate(verts_local):
            ase_obj.verts[i * 3] = (origin.x + v[0]) * self.scale
            ase_obj.verts[i * 3 + 1] = (origin.y + v[1]) * self.scale
            ase_obj.verts[i * 3 + 2] = (origin.z + v[2]) * self.scale

        # Faces
        for i, (a, b, c) in enumerate(face_indices):
            face = ase_obj.faces[i]
            face.vert[0], face.vert[1], face.vert[2] = a, b, c
            face.smoothing_mask = 0
            face.material_id = 0
            face.edge_visibility[0] = 1
            face.edge_visibility[1] = 1
            face.edge_visibility[2] = 1

    # -------------------------------------------------------------------
    # Light population
    # -------------------------------------------------------------------

    def _populate_light(self, ase_light, obj):
        """Fill an AseLight from a Blender light object."""
        ase_light.name = self.fixup_name(obj.name).encode('utf-8')[:63]
        light_data = obj.data
        ase_light.type = 1 if getattr(light_data, "type", "POINT") == "SPOT" else 0

        # The direct 3DI path emits light offsets by adding the local light
        # position to the part origin.  Match that scene contract instead of
        # asking Blender to compose the full child matrix, which can introduce
        # small transform drift and would rotate local offsets under PN nodes.
        pos = self._light_export_position(obj)
        ase_light.pos[0] = pos.x * self.scale
        ase_light.pos[1] = self._ase_y(pos.y * self.scale)
        ase_light.pos[2] = pos.z * self.scale

        ase_light.color[0] = light_data.color[0]
        ase_light.color[1] = light_data.color[1]
        ase_light.color[2] = light_data.color[2]
        ase_light.intensity = 0.0
        ase_light.atten_start = 0.0
        ase_light.atten_end = 0.0
        if hasattr(light_data, 'use_custom_distance') and light_data.use_custom_distance:
            ase_light.atten_end = light_data.cutoff_distance

        ase_light.near_atten_start = 0.0
        if getattr(light_data, "type", "POINT") == "SPOT":
            ase_light.falloff = math.degrees(float(light_data.spot_size)) * 0.5
        else:
            ase_light.falloff = 0.0

        direction = obj.matrix_world.to_3x3() @ Vector((0.0, 0.0, -1.0))
        if direction.length_squared <= 1e-8:
            direction = Vector((0.0, 0.0, -1.0))
        direction.normalize()
        ase_light.tm_row2[0] = self._positive_zero(-direction.x)
        ase_light.tm_row2[1] = self._positive_zero(-direction.y)
        ase_light.tm_row2[2] = self._positive_zero(-direction.z)

    @staticmethod
    def _light_export_position(obj):
        parent = obj.parent
        if parent is None:
            return obj.matrix_world.translation

        parent_pos = parent.matrix_world.translation
        local_pos = obj.location
        return Vector((
            AseExporter._zero_tiny_parent_offset(parent_pos.x) + local_pos.x,
            AseExporter._zero_tiny_parent_offset(parent_pos.y) + local_pos.y,
            AseExporter._zero_tiny_parent_offset(parent_pos.z) + local_pos.z,
        ))

    # -------------------------------------------------------------------
    # Transform helpers
    # -------------------------------------------------------------------

    def _set_object_tm(self, ase_obj, matrix):
        """Set tm_row[4][3] from a Blender 4x4 matrix."""
        rot = matrix.to_3x3().transposed()
        for r in range(3):
            for c in range(3):
                ase_obj.tm_row[r][c] = rot[r][c]
        ase_obj.tm_row[3][0] = matrix.translation.x * self.scale
        ase_obj.tm_row[3][1] = self._ase_y(matrix.translation.y * self.scale)
        ase_obj.tm_row[3][2] = matrix.translation.z * self.scale

    def _set_identity_tm(self, ase_obj, origin):
        """Set an identity transform row table at origin."""
        ase_obj.tm_row[0][0] = 1.0
        ase_obj.tm_row[0][1] = 0.0
        ase_obj.tm_row[0][2] = 0.0
        ase_obj.tm_row[1][0] = 0.0
        ase_obj.tm_row[1][1] = 1.0
        ase_obj.tm_row[1][2] = 0.0
        ase_obj.tm_row[2][0] = 0.0
        ase_obj.tm_row[2][1] = 0.0
        ase_obj.tm_row[2][2] = 1.0
        ase_obj.tm_row[3][0] = origin.x * self.scale
        ase_obj.tm_row[3][1] = self._ase_y(origin.y * self.scale)
        ase_obj.tm_row[3][2] = origin.z * self.scale

    def _bone_export_origin(self, armature_obj, pose_bone, bone_name):
        if "root_motion" not in armature_obj.pose.bones:
            pn_name = self._part_name_for_bone(bone_name)
            if pn_name:
                part_obj = bpy.data.objects.get(pn_name)
                if part_obj is not None and self._is_visible(part_obj):
                    return part_obj.matrix_world.translation

        rest_matrix_world = armature_obj.matrix_world @ pose_bone.bone.matrix_local
        return rest_matrix_world.translation

    @staticmethod
    def _part_name_for_bone(bone_name):
        if bone_name.startswith("BN") and len(bone_name) >= 4 and bone_name[2:4].isdigit():
            return f"PN{bone_name[2:4]}"
        return None

    @staticmethod
    def _ase_y(value):
        return -0.0 if value == 0.0 else value

    @staticmethod
    def _positive_zero(value):
        return 0.0 if value == 0.0 else value

    @staticmethod
    def _zero_tiny_parent_offset(value):
        return 0.0 if abs(value) <= 1.0e-7 else value

    # -------------------------------------------------------------------
    # Mesh preparation (unchanged from original)
    # -------------------------------------------------------------------

    def _prepare_triangulated_mesh(self, obj):
        """Prepare a triangulated temp mesh.

        Returns (mesh_eval, bm, temp_mesh, neg_scale, orig_edge_keys).
        """
        mesh = obj.data

        if self._has_armature_modifier(obj):
            mesh_eval = mesh
        else:
            depsgraph = bpy.context.evaluated_depsgraph_get()
            obj_eval = obj.evaluated_get(depsgraph)
            mesh_eval = obj_eval.data

        bm = None
        if all(len(poly.vertices) == 3 for poly in mesh_eval.polygons):
            # Preserve original polygon/loop ordering when the mesh is already
            # triangulated. Re-triangulating with bmesh can reshuffle triangles
            # and shift face-normal insertion order in OED collision export.
            temp_mesh = mesh_eval.copy()
        else:
            bm = bmesh.new()
            bm.from_mesh(mesh_eval)
            bmesh.ops.triangulate(bm, faces=bm.faces)
            temp_mesh = bpy.data.meshes.new("temp_export")
            bm.to_mesh(temp_mesh)
        temp_mesh.calc_loop_triangles()
        self._ensure_split_normals(temp_mesh)

        neg_scale = obj.matrix_world.determinant() < 0
        orig_edge_keys = {tuple(sorted(edge.vertices)) for edge in mesh_eval.edges}

        return mesh_eval, bm, temp_mesh, neg_scale, orig_edge_keys

    @staticmethod
    def _has_armature_modifier(obj):
        return any(getattr(mod, "type", None) == 'ARMATURE' for mod in obj.modifiers)

    def _ensure_split_normals(self, mesh):
        """Ensure split normals are available across Blender versions."""
        if hasattr(mesh, "calc_normals_split"):
            mesh.calc_normals_split()
            return True
        if hasattr(mesh, "calc_normals"):
            mesh.calc_normals()
        return False

    # -------------------------------------------------------------------
    # Name mapping (unchanged from original)
    # -------------------------------------------------------------------

    def _export_name(self, name):
        """Map Blender object name to ASE node name.

        PN## helpers (part nodes) must be exported as bare numbers ("01", "02", ...)
        so that df4oed's classification loop recognises the first digit character and
        assigns them to the correct numbered group.
        """
        name = self._clean_blender_duplicate_suffix(name)
        if name.startswith("PN") and len(name) >= 4 and name[2:4].isdigit():
            return name[2:]  # "PN01" -> "01", "PN40" -> "40"
        return name

    def _bone_export_name(self, name):
        """Trim bone names like 'BN01 Hips' to 'BN01' for export."""
        if name.startswith("BN") and len(name) >= 4 and name[2:4].isdigit():
            return name[:4]
        return name

    def fixup_name(self, name):
        """Fix up object name for ASE format (matches 3ds Max FixupName)"""
        # Replace " with ' and control chars (<=31) with _ (reference export.cpp:1723-1740)
        result = []
        for ch in name:
            if ch == '"':
                result.append("'")
            elif ord(ch) <= 31:
                result.append('_')
            else:
                result.append(ch)
        return ''.join(result)

    # -------------------------------------------------------------------
    # Texture helpers (unchanged from original)
    # -------------------------------------------------------------------

    def _fix_tex_ext(self, name):
        """Fix texture extensions for df4oed compatibility.

        df4oed only supports TGA/PCX/MDT in ASE files.
        DDS textures are auto-loaded as fallback, so we map .dds -> .tga
        """
        if not name:
            return name
        name = os.path.basename(name)
        root, ext = os.path.splitext(name)
        if ext.upper() in ('.TGA', '.PCX', '.MDT'):
            return root + ext
        return root + '.tga'

    def _fit_texture_name(self, name):
        """Shorten a texture filename to fit OED's 15-char limit.

        Truncates the stem, preserving the extension.  Appends a digit
        suffix when truncation would create a duplicate.

        Returns the (possibly shortened) filename.
        """
        if not name:
            return name
        if len(name) <= self.MAX_TEX_FILENAME:
            self._used_tex_names[name.lower()] = name.lower()
            return name

        root, ext = os.path.splitext(name)
        max_stem = self.MAX_TEX_FILENAME - len(ext)

        candidate = root[:max_stem] + ext
        key = candidate.lower()

        # Deduplicate: if this short name is already taken by a DIFFERENT
        # original name, shorten further and append a digit.
        if key in self._used_tex_names and self._used_tex_names[key] != name.lower():
            for i in range(2, 100):
                suffix = str(i)
                candidate = root[:max_stem - len(suffix)] + suffix + ext
                key = candidate.lower()
                if key not in self._used_tex_names:
                    break

        self._used_tex_names[key] = name.lower()
        if candidate != name:
            print(f"ASE Export: Texture name shortened: '{name}' -> '{candidate}'")
        return candidate

    def _find_bitmap_from_nodes(self, material):
        """Extract a bitmap path and Image object from the Blender shader node tree.

        Returns (path_string, bpy.types.Image or None).
        """
        def find_image_from_socket(socket, visited=None):
            if not socket or not socket.is_linked:
                return None
            return find_image_from_node(socket.links[0].from_node, visited)

        def find_image_from_node(node, visited=None):
            if visited is None:
                visited = set()
            if id(node) in visited:
                return None
            visited.add(id(node))
            if node.type == 'TEX_IMAGE' and node.image:
                return node.image
            if node.type == 'NORMAL_MAP':
                return find_image_from_socket(node.inputs.get('Color'), visited)
            for inp in node.inputs:
                if inp.is_linked:
                    img = find_image_from_socket(inp, visited)
                    if img:
                        return img
            return None

        principled = None
        for node in material.node_tree.nodes:
            if node.type == 'BSDF_PRINCIPLED':
                principled = node
                break

        image = None
        if principled:
            image = find_image_from_socket(principled.inputs.get('Base Color'))
        if image is None:
            for node in material.node_tree.nodes:
                if node.type == 'TEX_IMAGE' and node.image:
                    image = node.image
                    break

        if image:
            path = image.filepath or image.filepath_raw or image.name or ""
            if path:
                path = bpy.path.abspath(path)
            return path, image
        return "", None

    @staticmethod
    def _clean_blender_duplicate_suffix(name: str) -> str:
        if len(name) > 4 and name[-4] == "." and name[-3:].isdigit():
            return name[:-4]
        return name

    def _shader_from_material_name(self, material):
        if not material:
            return ""
        name = self._clean_blender_duplicate_suffix(material.name)
        if not name.startswith("Material_"):
            return ""
        rest = name[len("Material_"):]
        parts = rest.split("_", 1)
        if len(parts) != 2:
            return ""
        try:
            int(parts[0])
        except ValueError:
            return ""
        return parts[1] or ""

    def _material_export_name(self, material, index: int, shader_code: str) -> str:
        if material:
            name = self._clean_blender_duplicate_suffix(material.name)
            if name.startswith("Material_"):
                return name
        return f"Material_{index}_{shader_code}"

    def _derive_opennova_shader(self, material, is_skinned):
        """Derive OED shader code from Blender material's node tree.

        Inspects the Principled BSDF node for bump, specular, emission,
        alpha, glass, and detail texture presence to select the appropriate
        OED shader. Returns the shader code string (e.g. 'VS_PHONGT').
        """
        if not material or not material.use_nodes or not material.node_tree:
            return "VS_SKBASIC" if is_skinned else "FF_ST_OP"

        nodes = material.node_tree.nodes
        links = material.node_tree.links

        # Find Principled BSDF
        bsdf = None
        for node in nodes:
            if node.type == 'BSDF_PRINCIPLED':
                bsdf = node
                break
        if not bsdf:
            return "VS_SKBASIC" if is_skinned else "FF_ST_OP"

        # Detect features from node tree
        has_bump = False
        normal_input = bsdf.inputs.get("Normal")
        if normal_input and normal_input.is_linked:
            from_node = normal_input.links[0].from_node
            if from_node.type == 'BUMP':
                has_bump = True

        has_specular = False
        spec_input = bsdf.inputs.get("Specular IOR Level") or bsdf.inputs.get("Specular")
        if spec_input and not spec_input.is_linked:
            has_specular = spec_input.default_value > 0

        is_emissive = False
        emission_input = bsdf.inputs.get("Emission Strength")
        if emission_input and not emission_input.is_linked:
            is_emissive = emission_input.default_value > 0

        is_alpha = False
        if hasattr(material, 'blend_method'):
            is_alpha = material.blend_method not in ("OPAQUE", "CLIP")
        alpha_input = bsdf.inputs.get("Alpha")
        if alpha_input and alpha_input.is_linked:
            is_alpha = True

        is_glass = False
        trans_input = (bsdf.inputs.get("Transmission Weight")
                       or bsdf.inputs.get("Transmission"))
        if trans_input and not trans_input.is_linked:
            is_glass = trans_input.default_value > 0

        # Count connected texture images
        tex_count = 0
        for node in nodes:
            if node.type == 'TEX_IMAGE' and node.image:
                # Only count textures that feed into the material
                for output in node.outputs:
                    if output.is_linked:
                        tex_count += 1
                        break

        # Detect detail texture (MixRGB Multiply feeding Base Color)
        has_detail = self._has_mix_multiply_detail(material)

        # Shader selection logic
        if is_glass:
            return "VS_SKGLASS" if is_skinned else "FFP_GLASS"

        if has_bump:
            if has_specular:
                return "VS_SKBUMPPHONGT" if is_skinned else "VS_PHONGT"
            else:
                return "VS_SKBUMPDIFFT" if is_skinned else "VS_DOT3DIFF"

        if has_detail or tex_count >= 2:
            if is_emissive:
                return "FF_MT_OP_LUM"
            elif is_alpha:
                return "FF_MT_AB"
            else:
                return "FF_MT_OP"

        # Single texture (or no texture)
        if is_skinned:
            return "VS_SKBASIC"

        if is_emissive:
            return "FF_ST_OP_LUM"
        elif is_alpha:
            return "FF_ST_AB"
        else:
            return "FF_ST_OP"

    def _has_mix_multiply_detail(self, material):
        """Check if material has a MixRGB/Mix Multiply node feeding Base Color."""
        if not material.use_nodes or not material.node_tree:
            return False

        bsdf = None
        for node in material.node_tree.nodes:
            if node.type == 'BSDF_PRINCIPLED':
                bsdf = node
                break
        if not bsdf:
            return self._find_named_detail_image(material) is not None

        base_color = bsdf.inputs.get("Base Color")
        if not base_color or not base_color.is_linked:
            return self._find_named_detail_image(material) is not None

        from_node = base_color.links[0].from_node
        # ShaderNodeMixRGB (Blender 3.x) or ShaderNodeMix (Blender 4.x)
        if from_node.type == 'MIX_RGB' and from_node.blend_type == 'MULTIPLY':
            return True
        if from_node.type == 'MIX' and hasattr(from_node, 'data_type'):
            if from_node.data_type == 'RGBA' and from_node.blend_type == 'MULTIPLY':
                return True
        return self._find_named_detail_image(material) is not None

    @staticmethod
    def _find_named_detail_image(material):
        for node in material.node_tree.nodes:
            if node.type != 'TEX_IMAGE' or not node.image:
                continue
            label = getattr(node, "label", "") or ""
            marker = f"{node.name} {label}".lower()
            if "detail" in marker:
                return node.image
        return None

    @staticmethod
    def _image_path(image):
        path = image.filepath or image.filepath_raw or image.name or ""
        if path:
            path = bpy.path.abspath(path)
        return path

    def _find_detail_from_nodes(self, material):
        """Extract detail/lightmap texture from Blender material nodes.

        Returns (path_string, bpy.types.Image or None).
        """
        if not material.use_nodes or not material.node_tree:
            return "", None

        bsdf = None
        for node in material.node_tree.nodes:
            if node.type == 'BSDF_PRINCIPLED':
                bsdf = node
                break
        if not bsdf:
            return "", None

        base_color = bsdf.inputs.get("Base Color")
        if not base_color or not base_color.is_linked:
            image = self._find_named_detail_image(material)
            if image:
                return self._image_path(image), image
            return "", None

        mix_node = base_color.links[0].from_node
        is_multiply = False
        if mix_node.type == 'MIX_RGB' and mix_node.blend_type == 'MULTIPLY':
            is_multiply = True
        elif (mix_node.type == 'MIX' and hasattr(mix_node, 'data_type')
              and mix_node.data_type == 'RGBA'
              and mix_node.blend_type == 'MULTIPLY'):
            is_multiply = True

        if not is_multiply:
            image = self._find_named_detail_image(material)
            if image:
                return self._image_path(image), image
            return "", None

        # The second input of MixRGB is the detail/lightmap texture.
        # For MIX_RGB: inputs[1]=Color1 (diffuse), inputs[2]=Color2 (detail)
        # For MIX (4.x): inputs["B"] is the second color
        detail_input = None
        if mix_node.type == 'MIX_RGB':
            detail_input = mix_node.inputs[2] if len(mix_node.inputs) > 2 else None
        elif mix_node.type == 'MIX':
            detail_input = mix_node.inputs.get("B")

        if not detail_input or not detail_input.is_linked:
            image = self._find_named_detail_image(material)
            if image:
                return self._image_path(image), image
            return "", None

        tex_node = detail_input.links[0].from_node
        if tex_node.type == 'TEX_IMAGE' and tex_node.image:
            image = tex_node.image
            return self._image_path(image), image

        image = self._find_named_detail_image(material)
        if image:
            return self._image_path(image), image
        return "", None

    def _get_material_diffuse(self, material):
        """Extract diffuse color from a Blender material. Returns (r, g, b)."""
        if material.use_nodes and material.node_tree:
            for node in material.node_tree.nodes:
                if node.type == 'BSDF_PRINCIPLED':
                    inp = node.inputs.get('Base Color')
                    if inp and not inp.is_linked:
                        return (inp.default_value[0], inp.default_value[1],
                                inp.default_value[2])
                    break
        return (material.diffuse_color[0], material.diffuse_color[1],
                material.diffuse_color[2])

    def _get_material_specular(self, material):
        """Extract specular color from a Blender material. Returns (r, g, b)."""
        if material.use_nodes and material.node_tree:
            for node in material.node_tree.nodes:
                if node.type == 'BSDF_PRINCIPLED':
                    inp = node.inputs.get('Specular IOR Level')
                    if inp and not inp.is_linked:
                        s = inp.default_value
                        return (s, s, s)
                    break
        return (0.9, 0.9, 0.9)

    def _get_material_shine(self, material):
        """Extract shine (glossiness) from a Blender material. Returns float 0..1."""
        if material.use_nodes and material.node_tree:
            for node in material.node_tree.nodes:
                if node.type == 'BSDF_PRINCIPLED':
                    inp = node.inputs.get('Roughness')
                    if inp and not inp.is_linked:
                        return 1.0 - inp.default_value  # invert roughness
                    break
        return 0.1

    def _get_material_transparency(self, material):
        """Extract transparency from a Blender material. Returns float 0..1."""
        if material.use_nodes and material.node_tree:
            for node in material.node_tree.nodes:
                if node.type == 'BSDF_PRINCIPLED':
                    inp = node.inputs.get('Alpha')
                    if inp and not inp.is_linked:
                        return 1.0 - inp.default_value  # alpha to transparency
                    break
        return 0.0

    def _save_textures(self, output_dir):
        """Save queued texture images as TGA files alongside the ASE."""
        for filename, image in self._texture_queue.items():
            dest = os.path.join(output_dir, filename)
            if os.path.exists(dest):
                print(f"ASE Export: Texture already exists, skipping: {filename}")
                continue

            try:
                # Save via a temporary settings override to force TGA output.
                orig_path = image.filepath_raw
                orig_format = image.file_format

                image.filepath_raw = dest
                image.file_format = 'TARGA_RAW'  # uncompressed — avoids RLE+top-origin issues in stb_image
                image.save()

                # Restore original values
                image.filepath_raw = orig_path
                image.file_format = orig_format

                print(f"ASE Export: Saved texture {filename}")
            except Exception as e:
                print(f"ASE Export: Failed to save texture {filename}: {e}")
