"""
ASE Token Definitions - Blender ASE Exporter
Based on 3ds Max ASCII Scene Export format tokens
"""

# Version and file format
VERSION = 200
FILE_EXTENSION = ".ase"

# Top level category IDs
ID_FILEID = "*3DSMAX_ASCIIEXPORT"
ID_COMMENT = "*COMMENT"
ID_SCENE = "*SCENE"
ID_GEOMETRY = "*GEOMOBJECT"
ID_SHAPE = "*SHAPEOBJECT"
ID_CAMERA = "*CAMERAOBJECT"
ID_LIGHT = "*LIGHTOBJECT"
ID_HELPER = "*HELPEROBJECT"
ID_MATERIAL_LIST = "*MATERIAL_LIST"

# Hierarchy
ID_GROUP = "*GROUP"

# Node related IDs
ID_NODE_TM = "*NODE_TM"
ID_NODE_NAME = "*NODE_NAME"
ID_NODE_PARENT = "*NODE_PARENT"

# Transform matrix IDs
ID_TM_ROW0 = "*TM_ROW0"
ID_TM_ROW1 = "*TM_ROW1"
ID_TM_ROW2 = "*TM_ROW2"
ID_TM_ROW3 = "*TM_ROW3"
ID_TM_POS = "*TM_POS"
ID_TM_ROTAXIS = "*TM_ROTAXIS"
ID_TM_ROTANGLE = "*TM_ROTANGLE"
ID_TM_SCALE = "*TM_SCALE"
ID_TM_SCALEAXIS = "*TM_SCALEAXIS"
ID_TM_SCALEAXISANG = "*TM_SCALEAXISANG"

# Object (node) properties
ID_PROP_MOTIONBLUR = "*PROP_MOTIONBLUR"
ID_PROP_CASTSHADOW = "*PROP_CASTSHADOW"
ID_PROP_RECVSHADOW = "*PROP_RECVSHADOW"

# Scene information
ID_FILENAME = "*SCENE_FILENAME"
ID_FIRSTFRAME = "*SCENE_FIRSTFRAME"
ID_LASTFRAME = "*SCENE_LASTFRAME"
ID_FRAMESPEED = "*SCENE_FRAMESPEED"
ID_TICKSPERFRAME = "*SCENE_TICKSPERFRAME"
ID_STATICBGCOLOR = "*SCENE_BACKGROUND_STATIC"
ID_ANIMBGCOLOR = "*SCENE_BACKGROUND_ANIM"
ID_ANIMAMBIENT = "*SCENE_AMBIENT_ANIM"
ID_STATICAMBIENT = "*SCENE_AMBIENT_STATIC"

# Mesh related IDs
ID_MESH = "*MESH"
ID_MESH_NORMALS = "*MESH_NORMALS"
ID_MESH_NUMVERTEX = "*MESH_NUMVERTEX"
ID_MESH_NUMFACES = "*MESH_NUMFACES"
ID_MESH_VERTEX_LIST = "*MESH_VERTEX_LIST"
ID_MESH_VERTEX = "*MESH_VERTEX"
ID_MESH_FACE_LIST = "*MESH_FACE_LIST"
ID_MESH_FACE = "*MESH_FACE"
ID_MESH_SMOOTHING = "*MESH_SMOOTHING"
ID_MESH_MTLID = "*MESH_MTLID"

# Skin/Weight related IDs
ID_MESH_WEIGHTS = "*MESH_WEIGHTS"
ID_MESH_WEIGHTSVERTEX = "*MESH_WEIGHTSVERTEX"
ID_NODE_BONENUMBER = "*NODE_BONENUMBER"

# UV mapping IDs
ID_MESH_NUMTVERTEX = "*MESH_NUMTVERTEX"
ID_MESH_NUMTVFACES = "*MESH_NUMTVFACES"
ID_MESH_TVERTLIST = "*MESH_TVERTLIST"
ID_MESH_TVERT = "*MESH_TVERT"
ID_MESH_TFACELIST = "*MESH_TFACELIST"
ID_MESH_TFACE = "*MESH_TFACE"

# Vertex color IDs
ID_MESH_NUMCVERTEX = "*MESH_NUMCVERTEX"
ID_MESH_NUMCVFACES = "*MESH_NUMCVFACES"
ID_MESH_CVERTLIST = "*MESH_CVERTLIST"
ID_MESH_VERTCOL = "*MESH_VERTCOL"
ID_MESH_CFACELIST = "*MESH_CFACELIST"
ID_MESH_CFACE = "*MESH_CFACE"

# Mapping channel support (R3+)
ID_MESH_MAPPINGCHANNEL = "*MESH_MAPPINGCHANNEL"

# Face map IDs
ID_MESH_FACEMAPLIST = "*MESH_FACEMAPLIST"
ID_MESH_FACEMAP = "*MESH_FACEMAP"
ID_MESH_FACEVERT = "*MESH_FACEMAPVERT"

# Normal IDs
ID_MESH_FACENORMAL = "*MESH_FACENORMAL"
ID_MESH_VERTEXNORMAL = "*MESH_VERTEXNORMAL"

# Animation IDs
ID_MESH_ANIMATION = "*MESH_ANIMATION"
ID_TIMEVALUE = "*TIMEVALUE"

# Animation keys
ID_CONTROL_POS_TRACK = "*CONTROL_POS_TRACK"
ID_CONTROL_ROT_TRACK = "*CONTROL_ROT_TRACK"
ID_CONTROL_SCALE_TRACK = "*CONTROL_SCALE_TRACK"
ID_CONTROL_POS_SAMPLE = "*CONTROL_POS_SAMPLE"
ID_CONTROL_ROT_SAMPLE = "*CONTROL_ROT_SAMPLE"
ID_CONTROL_SCALE_SAMPLE = "*CONTROL_SCALE_SAMPLE"

# Material IDs
ID_MATERIAL = "*MATERIAL"
ID_MATERIAL_NAME = "*MATERIAL_NAME"
ID_MATERIAL_CLASS = "*MATERIAL_CLASS"
ID_MATERIAL_AMBIENT = "*MATERIAL_AMBIENT"
ID_MATERIAL_DIFFUSE = "*MATERIAL_DIFFUSE"
ID_MATERIAL_SPECULAR = "*MATERIAL_SPECULAR"
ID_MATERIAL_SHINE = "*MATERIAL_SHINE"
ID_MATERIAL_SHINESTRENGTH = "*MATERIAL_SHINESTRENGTH"
ID_MATERIAL_TRANSPARENCY = "*MATERIAL_TRANSPARENCY"
ID_MATERIAL_WIRESIZE = "*MATERIAL_WIRESIZE"
ID_MATERIAL_SHADING = "*MATERIAL_SHADING"
ID_MATERIAL_XP_FALLOFF = "*MATERIAL_XP_FALLOFF"
ID_MATERIAL_SELFILLUM = "*MATERIAL_SELFILLUM"
ID_MATERIAL_FALLOFF = "*MATERIAL_FALLOFF"
ID_MATERIAL_XP_TYPE = "*MATERIAL_XP_TYPE"
ID_MATERIAL_TWOSIDED = "*MATERIAL_TWOSIDED"
ID_MATERIAL_WIRE = "*MATERIAL_WIRE"
ID_MATERIAL_WIREUNITS = "*MATERIAL_WIREUNITS"
ID_MATERIAL_FACEMAP = "*MATERIAL_FACEMAP"
ID_MATERIAL_SOFTEN = "*MATERIAL_SOFTEN"

# Submaterial IDs
ID_NUMSUBMTLS = "*NUMSUBMTLS"
ID_SUBMATERIAL = "*SUBMATERIAL"

# Map IDs
ID_MAP_DIFFUSE = "*MAP_DIFFUSE"
ID_MAP_AMBIENT = "*MAP_AMBIENT"
ID_MAP_SPECULAR = "*MAP_SPECULAR"
ID_MAP_SHINE = "*MAP_SHINE"
ID_MAP_SHINESTRENGTH = "*MAP_SHINESTRENGTH"
ID_MAP_SELFILLUM = "*MAP_SELFILLUM"
ID_MAP_OPACITY = "*MAP_OPACITY"
ID_MAP_FILTERCOLOR = "*MAP_FILTERCOLOR"
ID_MAP_BUMP = "*MAP_BUMP"
ID_MAP_REFLECT = "*MAP_REFLECT"
ID_MAP_REFRACT = "*MAP_REFRACT"
ID_MAP_GENERIC = "*MAP_GENERIC"

# Bitmap IDs
ID_BITMAP = "*BITMAP"
ID_MAP_NAME = "*MAP_NAME"
ID_MAP_CLASS = "*MAP_CLASS"
ID_MAP_SUBNO = "*MAP_SUBNO"
ID_MAP_AMOUNT = "*MAP_AMOUNT"
ID_MAP_TYPE = "*MAP_TYPE"
ID_BITMAP_FILTER = "*BITMAP_FILTER"

# UV Generator IDs
ID_UVW_U_OFFSET = "*UVW_U_OFFSET"
ID_UVW_V_OFFSET = "*UVW_V_OFFSET"
ID_UVW_U_TILING = "*UVW_U_TILING"
ID_UVW_V_TILING = "*UVW_V_TILING"
ID_UVW_ANGLE = "*UVW_ANGLE"
ID_UVW_BLUR = "*UVW_BLUR"
ID_UVW_BLUR_OFFSET = "*UVW_BLUR_OFFSET"
ID_UVW_NOUSE_AMT = "*UVW_NOUSE_AMT"
ID_UVW_NOISE_SIZE = "*UVW_NOISE_SIZE"
ID_UVW_NOISE_LEVEL = "*UVW_NOISE_LEVEL"
ID_UVW_NOISE_PHASE = "*UVW_NOISE_PHASE"

# Light IDs
ID_LIGHT_SETTINGS = "*LIGHT_SETTINGS"
ID_LIGHT_TYPE = "*LIGHT_TYPE"
ID_LIGHT_SHADOWS = "*LIGHT_SHADOWS"
ID_LIGHT_USELIGHT = "*LIGHT_USELIGHT"
ID_LIGHT_SPOTSHAPE = "*LIGHT_SPOTSHAPE"
ID_LIGHT_USEGLOBAL = "*LIGHT_USEGLOBAL"
ID_LIGHT_ABSMAPBIAS = "*LIGHT_ABSMAPBIAS"
ID_LIGHT_OVERSHOOT = "*LIGHT_OVERSHOOT"

# Light color and intensity
ID_LIGHT_COLOR = "*LIGHT_COLOR"
ID_LIGHT_INTENS = "*LIGHT_INTENS"
ID_LIGHT_ASPECT = "*LIGHT_ASPECT"
ID_LIGHT_HOTSPOT = "*LIGHT_HOTSPOT"
ID_LIGHT_FALLOFF = "*LIGHT_FALLOFF"
ID_LIGHT_TDIST = "*LIGHT_TDIST"
ID_LIGHT_MAPBIAS = "*LIGHT_MAPBIAS"
ID_LIGHT_MAPRANGE = "*LIGHT_MAPRANGE"
ID_LIGHT_MAPSIZE = "*LIGHT_MAPSIZE"
ID_LIGHT_RAYBIAS = "*LIGHT_RAYBIAS"
ID_LIGHT_ATTNSTART = "*LIGHT_ATTNSTART"
ID_LIGHT_ATTNEND = "*LIGHT_ATTNEND"

# Camera IDs
ID_CAMERA_SETTINGS = "*CAMERA_SETTINGS"
ID_CAMERA_TYPE = "*CAMERA_TYPE"
ID_CAMERA_HITHER = "*CAMERA_HITHER"
ID_CAMERA_YON = "*CAMERA_YON"
ID_CAMERA_NEAR = "*CAMERA_NEAR"
ID_CAMERA_FAR = "*CAMERA_FAR"
ID_CAMERA_FOV = "*CAMERA_FOV"
ID_CAMERA_TDIST = "*CAMERA_TDIST"

# Shape IDs
ID_SHAPE_LINECOUNT = "*SHAPE_LINECOUNT"
ID_SHAPE_LINE = "*SHAPE_LINE"
ID_SHAPE_VERTEX_KNOT = "*SHAPE_VERTEX_KNOT"
ID_SHAPE_VERTEX_INTERP = "*SHAPE_VERTEX_INTERP"
ID_SHAPE_VERTEXCOUNT = "*SHAPE_VERTEXCOUNT"
ID_SHAPE_CLOSED = "*SHAPE_CLOSED"

# Helper IDs
ID_HELPER_CLASS = "*HELPER_CLASS"
ID_BOUNDINGBOX_MIN = "*BOUNDINGBOX_MIN"
ID_BOUNDINGBOX_MAX = "*BOUNDINGBOX_MAX"

# Visibility track
ID_VISIBILITY_TRACK = "*VISIBILITY_TRACK"

# Wireframe color
ID_WIREFRAME_COLOR = "*WIREFRAME_COLOR"

# Standard shading modes
SHADING_CONST = "Constant"
SHADING_PHONG = "Phong"
SHADING_METAL = "Metal"
SHADING_BLINN = "Blinn"