schema_version = "1.0.0"

id = "opennova_blender"
version = "0.0.3"
name = "OpenNova Blender Addon"
tagline = "Export Novalogic ASE files"
maintainer = "Taylor Finnell <noreply@anthropic.com>"
type = "add-on"

tags = ["Import-Export"]

blender_version_min = "5.0.0"
license = ["SPDX:GPL-2.0-or-later"]

platforms = ["windows-x64", "linux-x64"]

wheels = []

[permissions]
files = "Export Novalogic ASE files"
