schema_version = "1.0.0"

id = "opennova_blender"
version = "0.0.1"
name = "OpenNova Blender Addon"
tagline = "Export Novalogic ASE files and animations; import Mixamo FBX for animation workflow"
maintainer = "Taylor Finnell <noreply@anthropic.com>"
type = "add-on"

tags = ["Import-Export", "3D View", "Animation"]

blender_version_min = "5.0.0"
license = ["SPDX:GPL-2.0-or-later"]

platforms = ["windows-x64", "linux-x64"]

wheels = []

[permissions]
files = "Import/export 3DI and ASE files"
