#!/bin/sh
# Regenerates web/cloudflare-realip.conf, the portal nginx's real-IP setup, from the
# address ranges Cloudflare publishes (https://www.cloudflare.com/ips/). Run it from
# anywhere, review the diff and commit it; the web image picks the file up on its next
# build. Cloudflare changes the list rarely and announces changes ahead of time, so a
# refresh before each web-image release is plenty.
set -eu

out="$(dirname "$0")/cloudflare-realip.conf"
v4="$(curl -fsS https://www.cloudflare.com/ips-v4)"
v6="$(curl -fsS https://www.cloudflare.com/ips-v6)"
[ -n "$v4" ] && [ -n "$v6" ] || { echo "empty range list from Cloudflare" >&2; exit 1; }

{
	echo "# GENERATED by web/cloudflare-realip.sh on $(date -u +%Y-%m-%d) from"
	echo "# https://www.cloudflare.com/ips-v4 and /ips-v6. Do not edit by hand: rerun the script."
	echo "#"
	echo "# The site's DNS records are proxied through Cloudflare (infra/aws), so the peer nginx"
	echo "# sees is a Cloudflare edge. For a peer inside these ranges, and only for one, nginx"
	echo "# takes the client address from CF-Connecting-IP; \$remote_addr, and with it the"
	echo "# X-Real-IP / X-Forwarded-For the NovaWorld server keys its rate limits and session"
	echo "# addresses by, is then the visitor's. A request that reaches the origin directly keeps"
	echo "# its own peer address, so the header cannot be forged from outside Cloudflare."
	echo "# CF-Connecting-IP holds one address, so real_ip_recursive stays off."
	for range in $v4; do echo "set_real_ip_from $range;"; done
	for range in $v6; do echo "set_real_ip_from $range;"; done
	echo "real_ip_header CF-Connecting-IP;"
} > "$out"
echo "wrote $out"
