#!/bin/sh
# Regenerates web/cloudflare-realip.conf, the portal nginx's real-IP setup, from the
# address ranges Cloudflare publishes (https://www.cloudflare.com/ips/). Run it from
# anywhere, review the diff and commit it; the web image picks the file up on its next
# build. Cloudflare changes the list rarely and announces changes ahead of time, so a
# refresh before each web-image release is plenty. Every entry must be an IPv4 or IPv6
# CIDR, or nothing is written; the file is replaced in one rename.
set -eu
set -f # no glob expansion of anything fetched

out="$(dirname "$0")/cloudflare-realip.conf"
tmp="$out.tmp.$$"
trap 'rm -f "$tmp"' EXIT

v4="$(curl -fsS https://www.cloudflare.com/ips-v4)"
v6="$(curl -fsS https://www.cloudflare.com/ips-v6)"

cidr_v4='^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[12][0-9]|3[0-2])$'
cidr_v6='^[0-9A-Fa-f:]*:[0-9A-Fa-f:]*/([0-9]|[1-9][0-9]|1[01][0-9]|12[0-8])$'

emit() { # $1 = the fetched list, $2 = the regex every entry must match
	count=0
	while IFS= read -r range; do
		[ -n "$range" ] || continue
		if ! printf '%s\n' "$range" | grep -Eq "$2"; then
			echo "refusing a range that is not a CIDR: '$range'" >&2
			exit 1
		fi
		printf 'set_real_ip_from %s;\n' "$range"
		count=$((count + 1))
	done <<EOF
$1
EOF
	[ "$count" -gt 0 ] || { echo "empty range list from Cloudflare" >&2; exit 1; }
}

{
	echo "# GENERATED by web/cloudflare-realip.sh on $(date -u +%Y-%m-%d) from"
	echo "# https://www.cloudflare.com/ips-v4 and /ips-v6. Do not edit by hand: rerun the script."
	echo "#"
	echo "# The site's DNS records are proxied through Cloudflare (infra/aws), so the peer nginx"
	echo "# sees is a Cloudflare edge. For a peer inside these ranges, and only for one, nginx"
	echo "# takes the client address from CF-Connecting-IP; \$remote_addr, and with it the"
	echo "# X-Real-IP / X-Forwarded-For the NovaWorld server keys its website login and register"
	echo "# rate limits and session addresses by, is then the visitor's. A request reaching the"
	echo "# origin directly keeps its own peer address. Cloudflare itself does not vouch for the"
	echo "# header: a Worker on any zone can fetch this origin from a Cloudflare edge with a"
	echo "# CF-Connecting-IP of its choosing, until edge authentication (nginx.conf, DEPLOY.md)"
	echo "# is on. CF-Connecting-IP holds one address, so real_ip_recursive stays off."
	emit "$v4" "$cidr_v4"
	emit "$v6" "$cidr_v6"
	echo "real_ip_header CF-Connecting-IP;"
} > "$tmp"
mv -f "$tmp" "$out"
trap - EXIT
echo "wrote $out"
